// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	constants "github.com/g8e-ai/g8e/services/g8eo/internal/constants"

	mock "github.com/stretchr/testify/mock"
)

// ExecutionHandler is an autogenerated mock type for the ExecutionHandler type
type ExecutionHandler struct {
	mock.Mock
}

// ExecuteVerifiedTransaction provides a mock function with given fields: ctx, eventType, cmdMsg
func (_m *ExecutionHandler) ExecuteVerifiedTransaction(ctx context.Context, eventType constants.EventType, cmdMsg interface{}) (string, error) {
	ret := _m.Called(ctx, eventType, cmdMsg)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteVerifiedTransaction")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, constants.EventType, interface{}) (string, error)); ok {
		return rf(ctx, eventType, cmdMsg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, constants.EventType, interface{}) string); ok {
		r0 = rf(ctx, eventType, cmdMsg)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, constants.EventType, interface{}) error); ok {
		r1 = rf(ctx, eventType, cmdMsg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewExecutionHandler creates a new instance of ExecutionHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutionHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExecutionHandler {
	mock := &ExecutionHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
