# Copyright (c) 2026 Lateralus Labs, LLC.
# Use of this source code is governed by the Business Source License
# included in the LICENSE file.
#
# As of the Change Date listed in the LICENSE file, this software is
# released under the Apache License, Version 2.0.

# Code generated by protocol/python/scripts/generate_enum_stubs.py. DO NOT EDIT.

"""Type stubs for dynamically-generated protocol enums."""

from enum import IntEnum, StrEnum
from typing import Any

__all__: list[str]

class CaseInsensitiveStrEnum(StrEnum):
    @classmethod
    def _missing_(cls, value: object) -> Any: ...


class ActionType(CaseInsensitiveStrEnum):
    A2A_CALL = 'A2A_CALL'
    CANCEL = 'CANCEL'
    EVAL_ANSWER = 'EVAL_ANSWER'
    EXECUTE_BASH = 'EXECUTE_BASH'
    FETCH_FILE_DIFF = 'FETCH_FILE_DIFF'
    FETCH_FILE_HISTORY = 'FETCH_FILE_HISTORY'
    FETCH_HISTORY = 'FETCH_HISTORY'
    FETCH_LOGS = 'FETCH_LOGS'
    FILE_EDIT = 'FILE_EDIT'
    FS_GREP = 'FS_GREP'
    FS_LIST = 'FS_LIST'
    FS_READ = 'FS_READ'
    HEARTBEAT = 'HEARTBEAT'
    INFERENCE = 'INFERENCE'
    PROVIDER_BOUNDARY_OBSERVATION = 'PROVIDER_BOUNDARY_OBSERVATION'
    MODEL_PROVENANCE_OBSERVATION = 'MODEL_PROVENANCE_OBSERVATION'
    DOCUMENT_UPDATE = 'DOCUMENT_UPDATE'
    DOCUMENT_DELETE = 'DOCUMENT_DELETE'
    MCP_CALL = 'MCP_CALL'
    MCP_PROMPT_GET = 'MCP_PROMPT_GET'
    MCP_PROMPT_LIST = 'MCP_PROMPT_LIST'
    MCP_RESOURCE_LIST = 'MCP_RESOURCE_LIST'
    MCP_RESOURCE_READ = 'MCP_RESOURCE_READ'
    PLATFORM_ENROLLMENT_CREATE = 'PLATFORM_ENROLLMENT_CREATE'
    PLATFORM_ENROLLMENT_DECIDE = 'PLATFORM_ENROLLMENT_DECIDE'
    PLATFORM_ENROLLMENT_ISSUE = 'PLATFORM_ENROLLMENT_ISSUE'
    PLATFORM_ENROLLMENT_PERSIST_POLICY = 'PLATFORM_ENROLLMENT_PERSIST_POLICY'
    PLATFORM_ENROLLMENT_CREATE_SESSION = 'PLATFORM_ENROLLMENT_CREATE_SESSION'
    PLATFORM_ENROLLMENT_REVOKE = 'PLATFORM_ENROLLMENT_REVOKE'
    PORT_CHECK = 'PORT_CHECK'
    OLLAMA_MODEL_INVENTORY = 'OLLAMA_MODEL_INVENTORY'
    OLLAMA_MODEL_RESIDENCY = 'OLLAMA_MODEL_RESIDENCY'
    RESTORE_FILE = 'RESTORE_FILE'
    SHUTDOWN = 'SHUTDOWN'


class AiSource(CaseInsensitiveStrEnum):
    TERMINAL_ANCHORED = 'ai.terminal.anchored'
    TERMINAL_DIRECT = 'ai.terminal.direct'
    TOOL_CALL = 'ai.tool.call'


class AiTaskId(CaseInsensitiveStrEnum):
    AGENT_CONTINUE = 'ai.agent.continue'
    CHAT = 'ai.chat'
    COMMAND = 'ai.command'
    DIRECT_COMMAND = 'ai.direct.command'
    FETCH_FILE_DIFF = 'ai.fetch.file.diff'
    FETCH_FILE_HISTORY = 'ai.fetch.file.history'
    FETCH_HISTORY = 'ai.fetch.history'
    FETCH_LOGS = 'ai.fetch.logs'
    FILE_EDIT = 'ai.file.edit'
    FS_LIST = 'ai.fs.list'
    FS_READ = 'ai.fs.read'
    INTENT_GRANT = 'ai.intent.grant'
    INTENT_REVOKE = 'ai.intent.revoke'
    PORT_CHECK = 'ai.port.check'
    RECURSIVE_GREP = 'ai.recursive.grep'
    RESTORE_FILE = 'ai.restore.file'
    CASE = 'ai.case'
    MEMORY = 'ai.memory'
    COMMAND_EXECUTION = 'ai.command.execution'
    FILE_OPERATION = 'ai.file.operation'
    INVESTIGATION_QUERY = 'ai.investigation.query'


class ApprovalErrorType(CaseInsensitiveStrEnum):
    APPROVAL_EXCEPTION = 'approval.exception'
    APPROVAL_PUBLISH_FAILURE = 'approval.publish.failure'
    APPROVAL_TIMEOUT = 'approval.timeout'
    INTENT_APPROVAL_EXCEPTION = 'intent.approval.exception'
    INVALID_INTENT = 'invalid.intent'


class ApprovalType(CaseInsensitiveStrEnum):
    AGENT_CONTINUE = 'agent.continue'
    COMMAND = 'command'
    FILE_EDIT = 'file.edit'
    INTENT = 'intent'


class AttachmentType(CaseInsensitiveStrEnum):
    IMAGE = 'image'
    OTHER = 'other'
    PDF = 'pdf'
    TEXT = 'text'


class AuditEventSource(CaseInsensitiveStrEnum):
    CONVERSATION = 'conversation'


class AuditEventType(CaseInsensitiveStrEnum):
    COMMAND_APPROVED = 'command.approved'
    COMMAND_DENIED = 'command.denied'
    COMMAND_EXECUTED = 'command.executed'
    COMMAND_STARTED = 'command.started'
    CONFIG_CHANGED = 'config.changed'
    ESCALATION_APPROVED = 'escalation.approved'
    ESCALATION_REQUESTED = 'escalation.requested'
    FILE_CREATED = 'file.created'
    FILE_DELETED = 'file.deleted'
    FILE_MODIFIED = 'file.modified'
    G8E_BOUND = 'g8e.bound'
    MESSAGE = 'message'
    PERMISSION_GRANTED = 'permission.granted'
    PERMISSION_REVOKED = 'permission.revoked'
    SESSION_STARTED = 'session.started'


class AuditSseEventType(CaseInsensitiveStrEnum):
    COMPLETE = 'audit.complete'
    CONNECTED = 'audit.connected'
    ERROR = 'audit.error'
    EVENT = 'audit.event'
    METADATA = 'audit.metadata'


class AuditorReason(CaseInsensitiveStrEnum):
    OK = 'ok'
    REVISED = 'revised'
    REVISED_FROM_DISSENT = 'revised_from_dissent'
    SWAPPED_TO_DISSENTER = 'swapped_to_dissenter'
    WHITELIST_VIOLATION = 'whitelist_violation'
    NO_VALID_REVISION = 'no_valid_revision'
    AUDITOR_ERROR = 'auditor_error'
    EMPTY_RESPONSE = 'empty_response'
    CONTEXT_OVERFLOW = 'context_overflow'


class AuthAuditEventType(CaseInsensitiveStrEnum):
    AUTH_FAILED = 'auth_failed'
    AUTH_SUCCESS = 'auth_success'


class AuthAuditResult(CaseInsensitiveStrEnum):
    FAILURE = 'failure'
    INVALID_API_KEY = 'invalid_api_key'
    SUCCESS = 'success'


class AuthMethod(CaseInsensitiveStrEnum):
    KV_PUBSUB = 'kv_pubsub'
    SESSION = 'session'
    PROXY = 'proxy'
    OPERATOR_SESSION = 'operator_session'
    TEST = 'test'


class AuthProvider(CaseInsensitiveStrEnum):
    JWT = 'jwt'
    LOCAL = 'local'
    PASSKEY = 'passkey'


class CaseStatus(CaseInsensitiveStrEnum):
    CLOSED = 'Closed'
    ESCALATED = 'Escalated'
    HUMAN_REVIEW = 'HumanReview'
    IN_PROGRESS = 'InProgress'
    NEW = 'New'
    RESOLVED = 'Resolved'
    TRIAGE = 'Triage'
    WAITING_FOR_CUSTOMER = 'WaitingForCustomer'


class Channel(CaseInsensitiveStrEnum):
    GOVERNANCE = 'governance'
    ERROR = 'error'
    MESSAGE = 'message'
    OPERATOR_DEVICE = 'operator_device'
    OPERATOR_INTENT = 'operator_intent'
    P_MESSAGE = 'pmessage'
    P_SUBSCRIBE = 'psubscribe'
    PUBLISH = 'publish'
    SSE_EVENT = 'sse_event'
    STORAGE_BLOB = 'storage_blob'
    STORAGE_DOCUMENT = 'storage_document'
    STORAGE_KV = 'storage_kv'
    SUBSCRIBE = 'subscribe'
    SUBSCRIBED = 'subscribed'
    UNSUBSCRIBED = 'unsubscribed'
    UNSUBSCRIBE = 'unsubscribe'
    PREFIX_AUDIT = 'audit'
    PREFIX_CMD = 'cmd'
    PREFIX_HEARTBEAT = 'heartbeat'
    PREFIX_RECEIPTS = 'receipts'
    PREFIX_RESULTS = 'results'


class CitationLayout(IntEnum):
    SENTENCE_LOOKAHEAD_CHARS = 120
    FAVICON_SIZE_PX = 16
    PARAGRAPH_LOOKAHEAD_CHARS = 200
    HOVER_CARD_WIDTH_PX = 360
    HEADING_SEGMENT_MAX_LENGTH = 60
    HOVER_CARD_VIEWPORT_MARGIN_PX = 8


class Collection(CaseInsensitiveStrEnum):
    ACCOUNT_LOCKS = 'account_locks'
    AGENT_ACTIVITY_METADATA = 'agent_activity_metadata'
    APP_POLICIES = 'app_policies'
    AUTH_ADMIN_AUDIT = 'auth_admin_audit'
    BOUND_SESSIONS = 'bound_sessions'
    CASES = 'cases'
    CLI_SESSIONS = 'cli_sessions'
    CONSOLE_AUDIT = 'console_audit'
    INVESTIGATIONS = 'investigations'
    LOGIN_AUDIT = 'login_audit'
    MEMORIES = 'memories'
    OPERATOR_SESSIONS = 'operator_sessions'
    OPERATOR_USAGE = 'operator_usage'
    OPERATORS = 'operators'
    ORGANIZATIONS = 'organizations'
    PASSKEY_CHALLENGES = 'passkey_challenges'
    PLATFORM_ENROLLMENTS = 'platform_enrollments'
    PERSONAS = 'personas'
    REPUTATION_COMMITMENTS = 'reputation_commitments'
    REPUTATION_STATE = 'reputation_state'
    REVOKED_CERTIFICATES = 'revoked_certificates'
    SETTINGS = 'settings'
    STAKE_RESOLUTIONS = 'stake_resolutions'
    TASKS = 'tasks'
    TRUSTED_SIGNERS = 'trusted_signers'
    USERS = 'users'
    WEB_SESSIONS = 'web_sessions'
    OBSERVE_AGENT_STATES = 'observe_agent_states'
    OBSERVE_RUNS = 'observe_runs'
    OBSERVE_EVALS = 'observe_evals'
    OBSERVE_DOWNLOADS = 'observe_downloads'


class CommandCategory(CaseInsensitiveStrEnum):
    CSV_WHITELIST = 'csv_whitelist'
    NETWORK_DIAGNOSTICS = 'network_diagnostics'
    SYSTEM_DIAGNOSTICS = 'system_diagnostics'


class CommandErrorType(CaseInsensitiveStrEnum):
    AGENT_CONFLICT = 'agent.conflict'
    APPROVAL_DENIED = 'approval.denied'
    APPROVAL_TIMEOUT = 'approval.timeout'
    BINDING_VIOLATION = 'binding.violation'
    BLACKLIST_VIOLATION = 'blacklist.violation'
    CLOUD_OPERATOR_REQUIRED = 'cloud.operator.required'
    COMMAND_EXECUTION_FAILED = 'command.execution.failed'
    COMMAND_TIMEOUT = 'command.timeout'
    CONFIGURATION_ERROR = 'configuration.error'
    EXECUTION_ERROR = 'execution.error'
    EXECUTION_FAILED = 'execution.failed'
    FETCH_FILE_DIFF_FAILED = 'fetch.file.diff.failed'
    FETCH_FILE_HISTORY_FAILED = 'fetch.file.history.failed'
    FETCH_HISTORY_FAILED = 'fetch.history.failed'
    FETCH_LOGS_FAILED = 'fetch.logs.failed'
    FS_LIST_FAILED = 'fs.list.failed'
    FS_READ_FAILED = 'fs.read.failed'
    G8E_RESOLUTION_ERROR = 'g8e.resolution.error'
    INVALID_INTENT = 'invalid.intent'
    MISSING_OPERATOR_ID = 'missing.operator.id'
    NO_OPERATORS_AVAILABLE = 'no.operators.available'
    OPERATION_TIMEOUT = 'operation.timeout'
    PARTIAL_IAM_DETACH_FAILED = 'partial.iam.detach.failed'
    PARTIAL_IAM_UPDATE_FAILED = 'partial.iam.update.failed'
    PERMISSION_DENIED = 'permission.denied'
    PERMISSION_ERROR = 'permission.error'
    PORT_CHECK_FAILED = 'port.check.failed'
    PUBSUB_SUBSCRIPTION_NOT_READY = 'pubsub.subscription.not.ready'
    RESTORE_FILE_FAILED = 'restore.file.failed'
    RISK_ANALYSIS_BLOCKED = 'risk.analysis.blocked'
    SECURITY_ERROR = 'security.error'
    SECURITY_VIOLATION = 'security.violation'
    UNKNOWN_TOOL = 'unknown.tool'
    USER_CANCELLED = 'user.cancelled'
    USER_DENIED = 'user.denied'
    USER_FEEDBACK = 'user.feedback'
    VALIDATION_ERROR = 'validation.error'
    WHITELIST_VIOLATION = 'whitelist.violation'


class CommandStatus(CaseInsensitiveStrEnum):
    CANCELLED = 'cancelled'
    COMPLETED = 'completed'
    EXECUTING = 'executing'
    FAILED = 'failed'
    OUTPUT = 'output'
    PENDING = 'pending'
    TIMEOUT = 'timeout'


class ComponentName(CaseInsensitiveStrEnum):
    CLIENT = 'client'
    G8EO = 'g8eo'
    G8EO_GATEWAY = 'g8eo-gateway'


class ComponentStatus(CaseInsensitiveStrEnum):
    ACTIVE = 'active'
    ERROR = 'error'
    INACTIVE = 'inactive'
    MAINTENANCE = 'maintenance'
    DEGRADED = 'degraded'


class ConnectionState(CaseInsensitiveStrEnum):
    CLOSED = 'closed'
    CONNECTED = 'connected'
    CONNECTING = 'connecting'
    DISCONNECTED = 'disconnected'
    ERROR = 'error'
    RECONNECTING = 'reconnecting'


class ConsensusAuditMode(CaseInsensitiveStrEnum):
    UNANIMOUS = 'unanimous'
    MAJORITY = 'majority'
    TIED = 'tied'


class ConsensusAuditStatus(CaseInsensitiveStrEnum):
    OK = 'ok'
    REVISED = 'revised'
    SWAP = 'swap'


class ConsensusMember(CaseInsensitiveStrEnum):
    AXIOM = 'axiom'
    CONCORD = 'concord'
    VARIANCE = 'variance'
    PRAGMA = 'pragma'
    NEMESIS = 'nemesis'


class ConversationStatus(CaseInsensitiveStrEnum):
    ACTIVE = 'active'
    COMPLETED = 'completed'
    INACTIVE = 'inactive'


class DownloadAuditEventType(CaseInsensitiveStrEnum):
    DOWNLOAD_TOKEN_FAILED = 'download_token_failed'
    DOWNLOAD_TOKEN_SUCCESS = 'download_token_success'


class Environment(CaseInsensitiveStrEnum):
    DEV = 'dev'
    PRODUCTION = 'production'
    TEST = 'test'


class ErrorCategory(CaseInsensitiveStrEnum):
    VALIDATION = 'validation'
    BUSINESS_LOGIC = 'business_logic'
    CONFIGURATION = 'configuration'
    AUTH = 'auth'
    PERMISSION = 'permission'
    RESOURCE_NOT_FOUND = 'resource_not_found'
    CONFLICT = 'conflict'
    RATE_LIMIT = 'rate_limit'
    SERVICE_UNAVAILABLE = 'service_unavailable'
    EXTERNAL_SERVICE = 'external_service'
    TIMEOUT = 'timeout'
    DATABASE = 'database'
    NETWORK = 'network'
    PUBSUB = 'pubsub'
    STORAGE = 'storage'
    INTERNAL = 'internal'
    DEPENDENCY = 'dependency'


class ErrorCode(CaseInsensitiveStrEnum):
    GENERIC_ERROR = 'G8E-1000'
    UNEXPECTED_ERROR = 'G8E-1001'
    NOT_IMPLEMENTED = 'G8E-1002'
    CONFIG_ERROR = 'G8E-1100'
    MISSING_ENV_VAR = 'G8E-1101'
    INVALID_SETTINGS = 'G8E-1102'
    SERVICE_INIT_ERROR = 'G8E-1103'
    AUTH_ERROR = 'G8E-1200'
    TOKEN_EXPIRED = 'G8E-1201'
    INVALID_TOKEN = 'G8E-1202'
    INSUFFICIENT_PERMISSIONS = 'G8E-1203'
    DB_CONNECTION_ERROR = 'G8E-1300'
    DB_QUERY_ERROR = 'G8E-1301'
    DB_DOCUMENT_NOT_FOUND = 'G8E-1302'
    DB_WRITE_ERROR = 'G8E-1303'
    DB_TRANSACTION_ERROR = 'G8E-1304'
    PUBSUB_CONNECTION_ERROR = 'G8E-1400'
    PUBSUB_PUBLISH_ERROR = 'G8E-1401'
    PUBSUB_SUBSCRIBE_ERROR = 'G8E-1402'
    PUBSUB_TOPIC_ERROR = 'G8E-1403'
    STORAGE_CONNECTION_ERROR = 'G8E-1500'
    STORAGE_READ_ERROR = 'G8E-1501'
    STORAGE_WRITE_ERROR = 'G8E-1502'
    STORAGE_DELETE_ERROR = 'G8E-1503'
    API_CONNECTION_ERROR = 'G8E-1600'
    API_TIMEOUT_ERROR = 'G8E-1601'
    API_RESPONSE_ERROR = 'G8E-1602'
    API_REQUEST_ERROR = 'G8E-1603'
    API_RATE_LIMIT_ERROR = 'G8E-1604'
    GENERIC_NOT_FOUND = 'G8E-1605'
    EXTERNAL_SERVICE_ERROR = 'G8E-1607'
    VALIDATION_ERROR = 'G8E-1700'
    MISSING_REQUIRED_FIELD = 'G8E-1701'
    INVALID_FIELD_FORMAT = 'G8E-1702'
    INVALID_FIELD_VALUE = 'G8E-1703'
    INVALID_FIELD_TYPE = 'G8E-1704'
    SCHEMA_VALIDATION_FAILED = 'G8E-1705'
    SCHEMA_NOT_FOUND = 'G8E-1706'
    INVALID_INPUT = 'G8E-1707'
    BUSINESS_LOGIC_ERROR = 'G8E-1800'
    WORKFLOW_ERROR = 'G8E-1801'
    STATE_TRANSITION_ERROR = 'G8E-1802'
    RESOURCE_CONFLICT = 'G8E-1803'
    TASK_CREATION_FAILED = 'G8E-1804'
    OPERATION_FAILED = 'G8E-1805'
    GOVERNANCE_REJECTED = 'G8E-1806'
    MODEL_CAPABILITY_UNSUPPORTED = 'G8E-1807'
    SERVICE_UNAVAILABLE_ERROR = 'G8E-1900'


class ErrorSeverity(CaseInsensitiveStrEnum):
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'
    CRITICAL = 'critical'
    INFO = 'info'


class EscalationRisk(CaseInsensitiveStrEnum):
    CRITICAL = 'critical'
    HIGH = 'high'
    LOW = 'low'
    MEDIUM = 'medium'


class EventType(CaseInsensitiveStrEnum):
    AI_AGENT_CONFLICT_DETECTED = 'g8e.v1.ai.agent.conflict.detected'
    AI_AGENT_CONFLICT_RESOLVED = 'g8e.v1.ai.agent.conflict.resolved'
    AI_AGENT_CONTINUE_APPROVAL_GRANTED = 'g8e.v1.ai.agent.continue.approval.granted'
    AI_AGENT_CONTINUE_APPROVAL_REJECTED = 'g8e.v1.ai.agent.continue.approval.rejected'
    AI_AGENT_CONTINUE_APPROVAL_REQUESTED = 'g8e.v1.ai.agent.continue.approval.requested'
    AI_CONSENSUS_SESSION_AUDITOR_FAILED = 'g8e.v1.ai.consensus.session.auditor.failed'
    AI_CONSENSUS_SESSION_COMPLETED = 'g8e.v1.ai.consensus.session.completed'
    AI_CONSENSUS_SESSION_DISABLED = 'g8e.v1.ai.consensus.session.disabled'
    AI_CONSENSUS_SESSION_GENERATION_FAILED = 'g8e.v1.ai.consensus.session.generation.failed'
    AI_CONSENSUS_SESSION_MARSHAL_BLOCKED = 'g8e.v1.ai.consensus.session.marshal.blocked'
    AI_CONSENSUS_SESSION_MODEL_NOT_CONFIGURED = 'g8e.v1.ai.consensus.session.model.not.configured'
    AI_CONSENSUS_SESSION_PROVIDER_UNAVAILABLE = 'g8e.v1.ai.consensus.session.provider.unavailable'
    AI_CONSENSUS_SESSION_STARTED = 'g8e.v1.ai.consensus.session.started'
    AI_CONSENSUS_SESSION_SYSTEM_ERROR = 'g8e.v1.ai.consensus.session.system.error'
    AI_CONSENSUS_VOTING_AUDIT_COMPLETED = 'g8e.v1.ai.consensus.voting.audit.completed'
    AI_CONSENSUS_VOTING_AUDIT_STARTED = 'g8e.v1.ai.consensus.voting.audit.started'
    AI_CONSENSUS_VOTING_CONSENSUS_FAILED = 'g8e.v1.ai.consensus.voting.consensus.failed'
    AI_CONSENSUS_VOTING_CONSENSUS_NOT_REACHED = 'g8e.v1.ai.consensus.voting.consensus.not.reached'
    AI_CONSENSUS_VOTING_CONSENSUS_REACHED = 'g8e.v1.ai.consensus.voting.consensus.reached'
    AI_CONSENSUS_VOTING_DISSENT_RECORDED = 'g8e.v1.ai.consensus.voting.dissent.recorded'
    AI_CONSENSUS_VOTING_PASS_COMPLETED = 'g8e.v1.ai.consensus.voting.pass.completed'
    AI_CONSENSUS_VOTING_ROUND_2_CONSENSUS_FAILED = 'g8e.v1.ai.consensus.voting.round.2.consensus.failed'
    AI_CONSENSUS_VOTING_ROUND_2_CONSENSUS_REACHED = 'g8e.v1.ai.consensus.voting.round.2.consensus.reached'
    AI_CONSENSUS_VOTING_ROUND_2_STARTED = 'g8e.v1.ai.consensus.voting.round.2.started'
    AI_CONSENSUS_VOTING_ROUND_COMPLETED = 'g8e.v1.ai.consensus.voting.round.completed'
    AI_CONSENSUS_VOTING_ROUND_STARTED = 'g8e.v1.ai.consensus.voting.round.started'
    AI_EVAL_ASSIGNMENT_COMPLETED = 'g8e.v1.ai.eval.assignment.completed'
    AI_EVAL_ASSIGNMENT_STARTED = 'g8e.v1.ai.eval.assignment.started'
    AI_EVAL_CYCLE_COMPLETED = 'g8e.v1.ai.eval.cycle.completed'
    AI_EVAL_CYCLE_STARTED = 'g8e.v1.ai.eval.cycle.started'
    AI_EVAL_HEARTBEAT = 'g8e.v1.ai.eval.heartbeat'
    AI_EVAL_METRIC_AVAILABLE = 'g8e.v1.ai.eval.metric.available'
    AI_EVAL_METRIC_RECORDED = 'g8e.v1.ai.eval.metric.recorded'
    AI_EVAL_MODEL_ROLE_INVOKED = 'g8e.v1.ai.eval.model_role.invoked'
    AI_EVAL_PROOF_AVAILABLE = 'g8e.v1.ai.eval.proof.available'
    AI_EVAL_PUBLICATION_COMPLETED = 'g8e.v1.ai.eval.publication.completed'
    AI_EVAL_RUN_COMPLETED = 'g8e.v1.ai.eval.run.completed'
    AI_EVAL_STOP_REQUESTED = 'g8e.v1.ai.eval.stop.requested'
    AI_EVAL_VERIFIER_COMPLETED = 'g8e.v1.ai.eval.verifier.completed'
    AI_LLM_CHAT_FILTER_EVENT = 'g8e.v1.ai.llm.chat.filter.updated'
    AI_LLM_CHAT_ITERATION_CITATIONS_RECEIVED = 'g8e.v1.ai.llm.chat.iteration.citations.received'
    AI_LLM_CHAT_ITERATION_COMPLETED = 'g8e.v1.ai.llm.chat.iteration.completed'
    AI_LLM_CHAT_ITERATION_FAILED = 'g8e.v1.ai.llm.chat.iteration.failed'
    AI_LLM_CHAT_ITERATION_RETRY = 'g8e.v1.ai.llm.chat.iteration.retry'
    AI_LLM_CHAT_ITERATION_STARTED = 'g8e.v1.ai.llm.chat.iteration.started'
    AI_LLM_CHAT_ITERATION_STOPPED = 'g8e.v1.ai.llm.chat.iteration.stopped'
    AI_LLM_CHAT_ITERATION_STREAM_COMPLETED = 'g8e.v1.ai.llm.chat.iteration.stream.completed'
    AI_LLM_CHAT_ITERATION_STREAM_DELTA_RECEIVED = 'g8e.v1.ai.llm.chat.iteration.stream.delta.received'
    AI_LLM_CHAT_ITERATION_STREAM_FAILED = 'g8e.v1.ai.llm.chat.iteration.stream.failed'
    AI_LLM_CHAT_ITERATION_STREAM_STARTED = 'g8e.v1.ai.llm.chat.iteration.stream.started'
    AI_LLM_CHAT_ITERATION_TEXT_CHUNK_RECEIVED = 'g8e.v1.ai.llm.chat.iteration.text.chunk.received'
    AI_LLM_CHAT_ITERATION_TEXT_COMPLETED = 'g8e.v1.ai.llm.chat.iteration.text.completed'
    AI_LLM_CHAT_ITERATION_TEXT_RECEIVED = 'g8e.v1.ai.llm.chat.iteration.text.received'
    AI_LLM_CHAT_ITERATION_TEXT_TRUNCATED = 'g8e.v1.ai.llm.chat.iteration.text.truncated'
    AI_LLM_CHAT_ITERATION_THINKING_END = 'g8e.v1.ai.llm.chat.iteration.thinking.end'
    AI_LLM_CHAT_ITERATION_THINKING_STARTED = 'g8e.v1.ai.llm.chat.iteration.thinking.started'
    AI_LLM_CHAT_ITERATION_THINKING_UPDATE = 'g8e.v1.ai.llm.chat.iteration.thinking.update'
    AI_LLM_CHAT_MESSAGE_DEAD_LETTERED = 'g8e.v1.ai.llm.chat.message.dead.lettered'
    AI_LLM_CHAT_MESSAGE_PROCESSING_FAILED = 'g8e.v1.ai.llm.chat.message.processing.failed'
    AI_LLM_CHAT_MESSAGE_REPLAYED = 'g8e.v1.ai.llm.chat.message.replayed'
    AI_LLM_CHAT_MESSAGE_SENT = 'g8e.v1.ai.llm.chat.message.sent'
    AI_LLM_CHAT_SUBMITTED = 'g8e.v1.ai.llm.chat.submitted'
    AI_LLM_CONFIG_FAILED = 'g8e.v1.ai.llm.config.failed'
    AI_LLM_CONFIG_RECEIVED = 'g8e.v1.ai.llm.config.received'
    AI_LLM_CONFIG_REQUESTED = 'g8e.v1.ai.llm.config.requested'
    AI_LLM_LIFECYCLE_COMPLETED = 'g8e.v1.ai.llm.lifecycle.completed'
    AI_LLM_LIFECYCLE_ERROR_OCCURRED = 'g8e.v1.ai.llm.lifecycle.error.occurred'
    AI_LLM_LIFECYCLE_FAILED = 'g8e.v1.ai.llm.lifecycle.failed'
    AI_LLM_LIFECYCLE_REQUESTED = 'g8e.v1.ai.llm.lifecycle.requested'
    AI_LLM_LIFECYCLE_STARTED = 'g8e.v1.ai.llm.lifecycle.started'
    AI_LLM_LIFECYCLE_STOPPED = 'g8e.v1.ai.llm.lifecycle.stopped'
    AI_LLM_TOOL_G8E_COMMAND_CONSTRAINTS_COMPLETED = 'g8e.v1.ai.llm.tool.g8e.command.constraints.completed'
    AI_LLM_TOOL_G8E_COMMAND_CONSTRAINTS_FAILED = 'g8e.v1.ai.llm.tool.g8e.command.constraints.failed'
    AI_LLM_TOOL_G8E_COMMAND_CONSTRAINTS_RECEIVED = 'g8e.v1.ai.llm.tool.g8e.command.constraints.received'
    AI_LLM_TOOL_G8E_COMMAND_CONSTRAINTS_REQUESTED = 'g8e.v1.ai.llm.tool.g8e.command.constraints.requested'
    AI_LLM_TOOL_G8E_INVESTIGATION_QUERY_COMPLETED = 'g8e.v1.ai.llm.tool.g8e.investigation.query.completed'
    AI_LLM_TOOL_G8E_INVESTIGATION_QUERY_FAILED = 'g8e.v1.ai.llm.tool.g8e.investigation.query.failed'
    AI_LLM_TOOL_G8E_INVESTIGATION_QUERY_RECEIVED = 'g8e.v1.ai.llm.tool.g8e.investigation.query.received'
    AI_LLM_TOOL_G8E_INVESTIGATION_QUERY_REQUESTED = 'g8e.v1.ai.llm.tool.g8e.investigation.query.requested'
    AI_LLM_TOOL_G8E_WEB_SEARCH_COMPLETED = 'g8e.v1.ai.llm.tool.g8e.web.search.completed'
    AI_LLM_TOOL_G8E_WEB_SEARCH_FAILED = 'g8e.v1.ai.llm.tool.g8e.web.search.failed'
    AI_LLM_TOOL_G8E_WEB_SEARCH_RECEIVED = 'g8e.v1.ai.llm.tool.g8e.web.search.received'
    AI_LLM_TOOL_G8E_WEB_SEARCH_REQUESTED = 'g8e.v1.ai.llm.tool.g8e.web.search.requested'
    AI_LLM_CHAT_ITERATION_THINKING_STOPPED = 'g8e.v1.ai.llm.chat.iteration.thinking.stopped'
    AI_REPUTATION_STATE_UPDATED = 'g8e.v1.ai.reputation.state.updated'
    AI_TRIAGE_CLARIFICATION_ANSWERED = 'g8e.v1.ai.triage.clarification.answered'
    AI_TRIAGE_CLARIFICATION_QUESTIONS = 'g8e.v1.ai.triage.clarification.questions'
    AI_TRIAGE_CLARIFICATION_SKIPPED = 'g8e.v1.ai.triage.clarification.skipped'
    AI_TRIAGE_CLARIFICATION_TIMEOUT = 'g8e.v1.ai.triage.clarification.timeout'
    APP_AGENT_ACTIVITY_RECORD_REQUESTED = 'g8e.v1.app.agent.activity.record.requested'
    APP_AGENT_ACTIVITY_RECORDED = 'g8e.v1.app.agent.activity.recorded'
    APP_AGENT_STATUS_UPDATED = 'g8e.v1.app.agent.status.updated'
    APP_CASE_ASSIGNED = 'g8e.v1.app.case.assigned'
    APP_CASE_CLEARED = 'g8e.v1.app.case.cleared'
    APP_CASE_CLOSED = 'g8e.v1.app.case.closed'
    APP_CASE_CREATE_REQUESTED = 'g8e.v1.app.case.create.requested'
    APP_CASE_CREATED = 'g8e.v1.app.case.created'
    APP_CASE_DELETE_REQUESTED = 'g8e.v1.app.case.delete.requested'
    APP_CASE_DELETED = 'g8e.v1.app.case.deleted'
    APP_CASE_ESCALATED = 'g8e.v1.app.case.escalated'
    APP_CASE_RESOLVED = 'g8e.v1.app.case.resolved'
    APP_CASE_SELECTED = 'g8e.v1.app.case.selected'
    APP_CASE_SWITCHED = 'g8e.v1.app.case.switched'
    APP_CASE_UPDATE_REQUESTED = 'g8e.v1.app.case.update.requested'
    APP_CASE_UPDATED = 'g8e.v1.app.case.updated'
    APP_DOCUMENT_DELETE_REQUESTED = 'g8e.v1.app.document.delete.requested'
    APP_DOCUMENT_UPDATE_REQUESTED = 'g8e.v1.app.document.update.requested'
    APP_INVESTIGATION_CHAT_MESSAGE_AI = 'g8e.v1.app.investigation.chat.message.ai'
    APP_INVESTIGATION_CHAT_MESSAGE_SYSTEM = 'g8e.v1.app.investigation.chat.message.system'
    APP_INVESTIGATION_CHAT_MESSAGE_USER = 'g8e.v1.app.investigation.chat.message.user'
    APP_INVESTIGATION_CLOSED = 'g8e.v1.app.investigation.closed'
    APP_INVESTIGATION_CREATE_REQUESTED = 'g8e.v1.app.investigation.create.requested'
    APP_INVESTIGATION_CREATED = 'g8e.v1.app.investigation.created'
    APP_INVESTIGATION_DELETE_REQUESTED = 'g8e.v1.app.investigation.delete.requested'
    APP_INVESTIGATION_DELETED = 'g8e.v1.app.investigation.deleted'
    APP_INVESTIGATION_ESCALATED = 'g8e.v1.app.investigation.escalated'
    APP_INVESTIGATION_LIST_COMPLETED = 'g8e.v1.app.investigation.list.completed'
    APP_INVESTIGATION_LIST_FAILED = 'g8e.v1.app.investigation.list.failed'
    APP_INVESTIGATION_LIST_RECEIVED = 'g8e.v1.app.investigation.list.received'
    APP_INVESTIGATION_LIST_REQUESTED = 'g8e.v1.app.investigation.list.requested'
    APP_INVESTIGATION_LOADED = 'g8e.v1.app.investigation.loaded'
    APP_INVESTIGATION_REQUESTED = 'g8e.v1.app.investigation.requested'
    APP_INVESTIGATION_STARTED = 'g8e.v1.app.investigation.started'
    APP_INVESTIGATION_STATUS_UPDATED_CLOSED = 'g8e.v1.app.investigation.status.updated.closed'
    APP_INVESTIGATION_STATUS_UPDATED_ESCALATED = 'g8e.v1.app.investigation.status.updated.escalated'
    APP_INVESTIGATION_STATUS_UPDATED_OPEN = 'g8e.v1.app.investigation.status.updated.open'
    APP_INVESTIGATION_STATUS_UPDATED_RESOLVED = 'g8e.v1.app.investigation.status.updated.resolved'
    APP_INVESTIGATION_UPDATE_REQUESTED = 'g8e.v1.app.investigation.update.requested'
    APP_INVESTIGATION_UPDATED = 'g8e.v1.app.investigation.updated'
    APP_MEMORY_CREATE_REQUESTED = 'g8e.v1.app.memory.create.requested'
    APP_MEMORY_CREATED = 'g8e.v1.app.memory.created'
    APP_MEMORY_UPDATE_REQUESTED = 'g8e.v1.app.memory.update.requested'
    APP_MEMORY_UPDATED = 'g8e.v1.app.memory.updated'
    APP_REPUTATION_COMMITMENT_CREATE_REQUESTED = 'g8e.v1.app.reputation.commitment.create.requested'
    APP_REPUTATION_STAKE_RESOLUTION_CREATE_REQUESTED = 'g8e.v1.app.reputation.stake.resolution.create.requested'
    APP_RUN_STATUS_UPDATED = 'g8e.v1.app.run.status.updated'
    APP_TASK_ASSIGNED = 'g8e.v1.app.task.assigned'
    APP_TASK_COMPLETED = 'g8e.v1.app.task.completed'
    APP_TASK_CREATED = 'g8e.v1.app.task.created'
    APP_TASK_FAILED = 'g8e.v1.app.task.failed'
    APP_TASK_STARTED = 'g8e.v1.app.task.started'
    APP_TASK_UPDATED = 'g8e.v1.app.task.updated'
    OPERATOR_A2A_CALL_REQUESTED = 'g8e.v1.operator.a2a.call.requested'
    OPERATOR_AUDIT_AI_RECORD_REQUESTED = 'g8e.v1.operator.audit.ai.record.requested'
    OPERATOR_AUDIT_AI_RECORDED = 'g8e.v1.operator.audit.ai.recorded'
    OPERATOR_AUDIT_COMMAND_RECORD_REQUESTED = 'g8e.v1.operator.audit.command.record.requested'
    OPERATOR_AUDIT_COMMAND_RECORDED = 'g8e.v1.operator.audit.command.recorded'
    OPERATOR_AUDIT_DIRECT_COMMAND_RECORD_REQUESTED = 'g8e.v1.operator.audit.direct.command.record.requested'
    OPERATOR_AUDIT_DIRECT_COMMAND_RECORDED = 'g8e.v1.operator.audit.direct.command.recorded'
    OPERATOR_AUDIT_DIRECT_COMMAND_RESULT_RECORD_REQUESTED = 'g8e.v1.operator.audit.direct.command.result.record.requested'
    OPERATOR_AUDIT_DIRECT_COMMAND_RESULT_RECORDED = 'g8e.v1.operator.audit.direct.command.result.recorded'
    OPERATOR_AUDIT_MCP_CALL_RECORD_REQUESTED = 'g8e.v1.operator.audit.mcp.call.record.requested'
    OPERATOR_AUDIT_MCP_CALL_RECORDED = 'g8e.v1.operator.audit.mcp.call.recorded'
    OPERATOR_AUDIT_USER_RECORD_REQUESTED = 'g8e.v1.operator.audit.user.record.requested'
    OPERATOR_AUDIT_USER_RECORDED = 'g8e.v1.operator.audit.user.recorded'
    OPERATOR_BOOTSTRAP_COMPLETED = 'g8e.v1.operator.bootstrap.completed'
    OPERATOR_BOOTSTRAP_CONFIG_RECEIVED = 'g8e.v1.operator.bootstrap.config.received'
    OPERATOR_BOOTSTRAP_FAILED = 'g8e.v1.operator.bootstrap.failed'
    OPERATOR_BOOTSTRAP_RECEIVED = 'g8e.v1.operator.bootstrap.received'
    OPERATOR_BOOTSTRAP_REQUESTED = 'g8e.v1.operator.bootstrap.requested'
    OPERATOR_BOUND = 'g8e.v1.operator.bound'
    OPERATOR_COMMAND_APPROVAL_GRANTED = 'g8e.v1.operator.command.approval.granted'
    OPERATOR_COMMAND_APPROVAL_PREPARING = 'g8e.v1.operator.command.approval.preparing'
    OPERATOR_COMMAND_APPROVAL_REJECTED = 'g8e.v1.operator.command.approval.rejected'
    OPERATOR_COMMAND_APPROVAL_REQUESTED = 'g8e.v1.operator.command.approval.requested'
    OPERATOR_COMMAND_CANCEL_ACKNOWLEDGED = 'g8e.v1.operator.command.cancel.acknowledged'
    OPERATOR_COMMAND_CANCEL_FAILED = 'g8e.v1.operator.command.cancel.failed'
    OPERATOR_COMMAND_CANCEL_REQUESTED = 'g8e.v1.operator.command.cancel.requested'
    OPERATOR_COMMAND_CANCELLED = 'g8e.v1.operator.command.cancelled'
    OPERATOR_COMMAND_COMPLETED = 'g8e.v1.operator.command.completed'
    OPERATOR_COMMAND_EXECUTION = 'g8e.v1.operator.command.execution.started'
    OPERATOR_COMMAND_FAILED = 'g8e.v1.operator.command.failed'
    OPERATOR_COMMAND_OUTPUT_RECEIVED = 'g8e.v1.operator.command.output.received'
    OPERATOR_COMMAND_REQUESTED = 'g8e.v1.operator.command.requested'
    OPERATOR_COMMAND_RESULT = 'g8e.v1.operator.command.result.completed'
    OPERATOR_COMMAND_STARTED = 'g8e.v1.operator.command.started'
    OPERATOR_COMMAND_STATUS_UPDATED_CANCELLED = 'g8e.v1.operator.command.status.updated.cancelled'
    OPERATOR_COMMAND_STATUS_UPDATED_COMPLETED = 'g8e.v1.operator.command.status.updated.completed'
    OPERATOR_COMMAND_STATUS_UPDATED_FAILED = 'g8e.v1.operator.command.status.updated.failed'
    OPERATOR_COMMAND_STATUS_UPDATED_QUEUED = 'g8e.v1.operator.command.status.updated.queued'
    OPERATOR_COMMAND_STATUS_UPDATED_RUNNING = 'g8e.v1.operator.command.status.updated.running'
    OPERATOR_CONTEXT_CHANGED = 'g8e.v1.operator.context.changed'
    OPERATOR_DEVICE_REGISTERED = 'g8e.v1.operator.device.registered'
    OPERATOR_EVAL_ANSWER_REQUESTED = 'g8e.v1.operator.eval.answer.requested'
    OPERATOR_FIELD_READ_ACCESS_DENIED = 'g8e.v1.operator.field.read.access.denied'
    OPERATOR_FIELD_READ_ACCESS_GRANTED = 'g8e.v1.operator.field.read.access.granted'
    OPERATOR_FIELD_READ_REQUESTED = 'g8e.v1.operator.field.read.requested'
    OPERATOR_FILE_DIFF_FETCH_COMPLETED = 'g8e.v1.operator.file.diff.fetch.completed'
    OPERATOR_FILE_DIFF_FETCH_FAILED = 'g8e.v1.operator.file.diff.fetch.failed'
    OPERATOR_FILE_DIFF_FETCH_RECEIVED = 'g8e.v1.operator.file.diff.fetch.received'
    OPERATOR_FILE_DIFF_FETCH_REQUESTED = 'g8e.v1.operator.file.diff.fetch.requested'
    OPERATOR_FILE_DIFF_FETCH_STARTED = 'g8e.v1.operator.file.diff.fetch.started'
    OPERATOR_FILE_EDIT_APPROVAL_FEEDBACK = 'g8e.v1.operator.file.edit.approval.feedback'
    OPERATOR_FILE_EDIT_APPROVAL_GRANTED = 'g8e.v1.operator.file.edit.approval.granted'
    OPERATOR_FILE_EDIT_APPROVAL_REJECTED = 'g8e.v1.operator.file.edit.approval.rejected'
    OPERATOR_FILE_EDIT_APPROVAL_REQUESTED = 'g8e.v1.operator.file.edit.approval.requested'
    OPERATOR_FILE_EDIT_COMPLETED = 'g8e.v1.operator.file.edit.completed'
    OPERATOR_FILE_EDIT_FAILED = 'g8e.v1.operator.file.edit.failed'
    OPERATOR_FILE_EDIT_REQUESTED = 'g8e.v1.operator.file.edit.requested'
    OPERATOR_FILE_EDIT_STARTED = 'g8e.v1.operator.file.edit.started'
    OPERATOR_FILE_EDIT_TIMEOUT = 'g8e.v1.operator.file.edit.timeout'
    OPERATOR_FILE_HISTORY_FETCH_COMPLETED = 'g8e.v1.operator.file.history.fetch.completed'
    OPERATOR_FILE_HISTORY_FETCH_FAILED = 'g8e.v1.operator.file.history.fetch.failed'
    OPERATOR_FILE_HISTORY_FETCH_RECEIVED = 'g8e.v1.operator.file.history.fetch.received'
    OPERATOR_FILE_HISTORY_FETCH_REQUESTED = 'g8e.v1.operator.file.history.fetch.requested'
    OPERATOR_FILE_HISTORY_FETCH_STARTED = 'g8e.v1.operator.file.history.fetch.started'
    OPERATOR_FILE_RESTORE_COMPLETED = 'g8e.v1.operator.file.restore.completed'
    OPERATOR_FILE_RESTORE_FAILED = 'g8e.v1.operator.file.restore.failed'
    OPERATOR_FILE_RESTORE_RECEIVED = 'g8e.v1.operator.file.restore.received'
    OPERATOR_FILE_RESTORE_REQUESTED = 'g8e.v1.operator.file.restore.requested'
    OPERATOR_FILESYSTEM_GREP_COMPLETED = 'g8e.v1.operator.filesystem.grep.completed'
    OPERATOR_FILESYSTEM_GREP_FAILED = 'g8e.v1.operator.filesystem.grep.failed'
    OPERATOR_FILESYSTEM_GREP_RECEIVED = 'g8e.v1.operator.filesystem.grep.received'
    OPERATOR_FILESYSTEM_GREP_REQUESTED = 'g8e.v1.operator.filesystem.grep.requested'
    OPERATOR_FILESYSTEM_GREP_STARTED = 'g8e.v1.operator.filesystem.grep.started'
    OPERATOR_FILESYSTEM_LIST_COMPLETED = 'g8e.v1.operator.filesystem.list.completed'
    OPERATOR_FILESYSTEM_LIST_FAILED = 'g8e.v1.operator.filesystem.list.failed'
    OPERATOR_FILESYSTEM_LIST_RECEIVED = 'g8e.v1.operator.filesystem.list.received'
    OPERATOR_FILESYSTEM_LIST_REQUESTED = 'g8e.v1.operator.filesystem.list.requested'
    OPERATOR_FILESYSTEM_LIST_STARTED = 'g8e.v1.operator.filesystem.list.started'
    OPERATOR_FILESYSTEM_READ_COMPLETED = 'g8e.v1.operator.filesystem.read.completed'
    OPERATOR_FILESYSTEM_READ_FAILED = 'g8e.v1.operator.filesystem.read.failed'
    OPERATOR_FILESYSTEM_READ_RECEIVED = 'g8e.v1.operator.filesystem.read.received'
    OPERATOR_FILESYSTEM_READ_REQUESTED = 'g8e.v1.operator.filesystem.read.requested'
    OPERATOR_FILESYSTEM_READ_STARTED = 'g8e.v1.operator.filesystem.read.started'
    OPERATOR_HEARTBEAT_MISSED = 'g8e.v1.operator.heartbeat.missed'
    OPERATOR_HEARTBEAT_RECEIVED = 'g8e.v1.operator.heartbeat.received'
    OPERATOR_HEARTBEAT_REQUESTED = 'g8e.v1.operator.heartbeat.requested'
    OPERATOR_HEARTBEAT_SENT = 'g8e.v1.operator.heartbeat.sent'
    OPERATOR_HISTORY_FETCH_COMPLETED = 'g8e.v1.operator.history.fetch.completed'
    OPERATOR_HISTORY_FETCH_FAILED = 'g8e.v1.operator.history.fetch.failed'
    OPERATOR_HISTORY_FETCH_RECEIVED = 'g8e.v1.operator.history.fetch.received'
    OPERATOR_HISTORY_FETCH_REQUESTED = 'g8e.v1.operator.history.fetch.requested'
    OPERATOR_INFERENCE_COMPLETED = 'g8e.v1.operator.inference.completed'
    OPERATOR_INFERENCE_FAILED = 'g8e.v1.operator.inference.failed'
    OPERATOR_INFERENCE_PROGRESS_UPDATED = 'g8e.v1.operator.inference.progress.updated'
    OPERATOR_INFERENCE_REQUESTED = 'g8e.v1.operator.inference.requested'
    OPERATOR_INTENT_APPROVAL_GRANTED = 'g8e.v1.operator.intent.approval.granted'
    OPERATOR_INTENT_APPROVAL_REJECTED = 'g8e.v1.operator.intent.approval.rejected'
    OPERATOR_INTENT_APPROVAL_REQUESTED = 'g8e.v1.operator.intent.approval.requested'
    OPERATOR_INTENT_DENIED = 'g8e.v1.operator.intent.denied'
    OPERATOR_INTENT_GRANTED = 'g8e.v1.operator.intent.granted'
    OPERATOR_INTENT_REQUESTED = 'g8e.v1.operator.intent.requested'
    OPERATOR_INTENT_REVOKE_REQUESTED = 'g8e.v1.operator.intent.revoke.requested'
    OPERATOR_INTENT_REVOKED = 'g8e.v1.operator.intent.revoked'
    OPERATOR_LOGS_FETCH_COMPLETED = 'g8e.v1.operator.logs.fetch.completed'
    OPERATOR_LOGS_FETCH_FAILED = 'g8e.v1.operator.logs.fetch.failed'
    OPERATOR_LOGS_FETCH_RECEIVED = 'g8e.v1.operator.logs.fetch.received'
    OPERATOR_LOGS_FETCH_REQUESTED = 'g8e.v1.operator.logs.fetch.requested'
    OPERATOR_MCP_CALL_REQUESTED = 'g8e.v1.operator.mcp.call.requested'
    OPERATOR_MCP_PROMPT_GET_REQUESTED = 'g8e.v1.operator.mcp.prompt.get.requested'
    OPERATOR_MCP_PROMPT_LIST_REQUESTED = 'g8e.v1.operator.mcp.prompt.list.requested'
    OPERATOR_MCP_RESOURCE_LIST_REQUESTED = 'g8e.v1.operator.mcp.resource.list.requested'
    OPERATOR_MCP_RESOURCE_READ_REQUESTED = 'g8e.v1.operator.mcp.resource.read.requested'
    OPERATOR_MODEL_PROVENANCE_OBSERVATION_COMPLETED = 'g8e.v1.operator.model.provenance.observation.completed'
    OPERATOR_MODEL_PROVENANCE_OBSERVATION_REQUESTED = 'g8e.v1.operator.model.provenance.observation.requested'
    OPERATOR_NETWORK_PING_COMPLETED = 'g8e.v1.operator.network.ping.completed'
    OPERATOR_NETWORK_PING_FAILED = 'g8e.v1.operator.network.ping.failed'
    OPERATOR_NETWORK_PING_RECEIVED = 'g8e.v1.operator.network.ping.received'
    OPERATOR_NETWORK_PING_REQUESTED = 'g8e.v1.operator.network.ping.requested'
    OPERATOR_NETWORK_PORT_CHECK_COMPLETED = 'g8e.v1.operator.network.port.check.completed'
    OPERATOR_NETWORK_PORT_CHECK_FAILED = 'g8e.v1.operator.network.port.check.failed'
    OPERATOR_NETWORK_PORT_CHECK_RECEIVED = 'g8e.v1.operator.network.port.check.received'
    OPERATOR_NETWORK_PORT_CHECK_REQUESTED = 'g8e.v1.operator.network.port.check.requested'
    OPERATOR_NETWORK_PORT_CHECK_STARTED = 'g8e.v1.operator.network.port.check.started'
    OPERATOR_NOTARY_APPROVAL_REQUESTED = 'g8e.v1.operator.notary.approval.requested'
    OPERATOR_NOTARY_TRANSACTION_EXPIRED = 'g8e.v1.operator.notary.transaction.expired'
    OPERATOR_OLLAMA_MODEL_INVENTORY_COMPLETED = 'g8e.v1.operator.ollama.model.inventory.completed'
    OPERATOR_OLLAMA_MODEL_INVENTORY_FAILED = 'g8e.v1.operator.ollama.model.inventory.failed'
    OPERATOR_OLLAMA_MODEL_INVENTORY_REQUESTED = 'g8e.v1.operator.ollama.model.inventory.requested'
    OPERATOR_OLLAMA_MODEL_RESIDENCY_COMPLETED = 'g8e.v1.operator.ollama.model.residency.completed'
    OPERATOR_OLLAMA_MODEL_RESIDENCY_FAILED = 'g8e.v1.operator.ollama.model.residency.failed'
    OPERATOR_OLLAMA_MODEL_RESIDENCY_REQUESTED = 'g8e.v1.operator.ollama.model.residency.requested'
    OPERATOR_PANEL_LIST_UPDATED = 'g8e.v1.operator.panel.list.updated'
    OPERATOR_PROVIDER_BOUNDARY_OBSERVATION_COMPLETED = 'g8e.v1.operator.provider.boundary.observation.completed'
    OPERATOR_PROVIDER_BOUNDARY_OBSERVATION_REQUESTED = 'g8e.v1.operator.provider.boundary.observation.requested'
    OPERATOR_RECEIPT_RECORDED = 'g8e.v1.operator.receipt.recorded'
    OPERATOR_REPUTATION_COMMITMENT_CREATED = 'g8e.v1.operator.reputation.commitment.created'
    OPERATOR_REPUTATION_COMMITMENT_FAILED = 'g8e.v1.operator.reputation.commitment.failed'
    OPERATOR_REPUTATION_COMMITMENT_VERIFIED = 'g8e.v1.operator.reputation.commitment.verified'
    OPERATOR_REPUTATION_SLASH_TIER_1 = 'g8e.v1.operator.reputation.slash.tier1'
    OPERATOR_REPUTATION_SLASH_TIER_2 = 'g8e.v1.operator.reputation.slash.tier2'
    OPERATOR_REPUTATION_SLASH_TIER_3 = 'g8e.v1.operator.reputation.slash.tier3'
    OPERATOR_REPUTATION_STAKE_RESOLUTION_CREATED = 'g8e.v1.operator.reputation.stake.resolution.created'
    OPERATOR_REPUTATION_STATE_UPDATE_REQUESTED = 'g8e.v1.operator.reputation.state.update.requested'
    OPERATOR_REPUTATION_STATE_UPDATED = 'g8e.v1.operator.reputation.state.updated'
    OPERATOR_SHUTDOWN_ACKNOWLEDGED = 'g8e.v1.operator.shutdown.acknowledged'
    OPERATOR_SHUTDOWN_REQUESTED = 'g8e.v1.operator.shutdown.requested'
    OPERATOR_SLOT_INITIALIZATION_FAILED = 'g8e.v1.operator.slot.initialization.failed'
    OPERATOR_STATUS_UPDATED_ACTIVE = 'g8e.v1.operator.status.updated.active'
    OPERATOR_STATUS_UPDATED_AVAILABLE = 'g8e.v1.operator.status.updated.available'
    OPERATOR_STATUS_UPDATED_BOUND = 'g8e.v1.operator.status.updated.bound'
    OPERATOR_STATUS_UPDATED_OFFLINE = 'g8e.v1.operator.status.updated.offline'
    OPERATOR_STATUS_UPDATED_STALE = 'g8e.v1.operator.status.updated.stale'
    OPERATOR_STATUS_UPDATED_STOPPED = 'g8e.v1.operator.status.updated.stopped'
    OPERATOR_STATUS_UPDATED_TERMINATED = 'g8e.v1.operator.status.updated.terminated'
    OPERATOR_STATUS_UPDATED_UNAVAILABLE = 'g8e.v1.operator.status.updated.unavailable'
    OPERATOR_TERMINAL_APPROVAL_DENIED = 'g8e.v1.operator.terminal.approval.denied'
    OPERATOR_TERMINAL_AUTH_STATE_CHANGED = 'g8e.v1.operator.terminal.auth.state.changed'
    OPERATOR_TERMINAL_THINKING_APPEND = 'g8e.v1.operator.terminal.thinking.append'
    OPERATOR_TERMINAL_THINKING_COMPLETE = 'g8e.v1.operator.terminal.thinking.complete'
    OPERATOR_UNBOUND = 'g8e.v1.operator.unbound'
    PLATFORM_AUDIT_CHAIN_CHECKPOINTED = 'g8e.v1.platform.audit.chain.checkpointed'
    PLATFORM_AUTH_INFO = 'g8e.v1.platform.auth.info.updated'
    PLATFORM_AUTH_LOGIN_FAILED = 'g8e.v1.platform.auth.login.failed'
    PLATFORM_AUTH_LOGIN_REQUESTED = 'g8e.v1.platform.auth.login.requested'
    PLATFORM_AUTH_LOGIN_SUCCEEDED = 'g8e.v1.platform.auth.login.succeeded'
    PLATFORM_AUTH_LOGOUT_FAILED = 'g8e.v1.platform.auth.logout.failed'
    PLATFORM_AUTH_LOGOUT_REQUESTED = 'g8e.v1.platform.auth.logout.requested'
    PLATFORM_AUTH_LOGOUT_SUCCEEDED = 'g8e.v1.platform.auth.logout.succeeded'
    PLATFORM_AUTH_SESSION_EXPIRED = 'g8e.v1.platform.auth.session.expired'
    PLATFORM_AUTH_SESSION_VALIDATION_FAILED = 'g8e.v1.platform.auth.session.validation.failed'
    PLATFORM_AUTH_SESSION_VALIDATION_REQUESTED = 'g8e.v1.platform.auth.session.validation.requested'
    PLATFORM_AUTH_SESSION_VALIDATION_SUCCEEDED = 'g8e.v1.platform.auth.session.validation.succeeded'
    PLATFORM_AUTH_USER_AUTHENTICATED = 'g8e.v1.platform.auth.user.authenticated'
    PLATFORM_AUTH_USER_UNAUTHENTICATED = 'g8e.v1.platform.auth.user.unauthenticated'
    PLATFORM_CONSOLE_LOG_CONNECTED_CONFIRMED = 'g8e.v1.platform.console.log.connected.confirmed'
    PLATFORM_CONSOLE_LOG_ENTRY_RECEIVED = 'g8e.v1.platform.console.log.entry.received'
    MODEL_PROVENANCE_PREFLIGHT_PROGRESS = 'g8e.v1.inference.model.provenance.preflight.updated'
    PLATFORM_APPROVALS_CHANGED = 'g8e.v1.platform.approvals.changed'
    PLATFORM_ENROLLMENT_CREATE_REQUESTED = 'g8e.v1.platform.enrollment.create.requested'
    PLATFORM_ENROLLMENT_CREATE_SESSION_REQUESTED = 'g8e.v1.platform.enrollment.create_session.requested'
    PLATFORM_ENROLLMENT_DECIDE_REQUESTED = 'g8e.v1.platform.enrollment.decide.requested'
    PLATFORM_ENROLLMENT_ISSUE_REQUESTED = 'g8e.v1.platform.enrollment.issue.requested'
    PLATFORM_ENROLLMENT_PERSIST_POLICY_REQUESTED = 'g8e.v1.platform.enrollment.persist_policy.requested'
    PLATFORM_ENROLLMENT_REVOKE_REQUESTED = 'g8e.v1.platform.enrollment.revoke.requested'
    PLATFORM_EXTERNAL_SERVICE_CONFIGURED = 'g8e.v1.platform.external.service.configured'
    PLATFORM_NOTIFICATION = 'g8e.v1.platform.notification.sent'
    PLATFORM_SSE_CONNECTION_CLOSED = 'g8e.v1.platform.sse.connection.closed'
    PLATFORM_SSE_CONNECTION_ERROR = 'g8e.v1.platform.sse.connection.error'
    PLATFORM_SSE_CONNECTION_ESTABLISHED = 'g8e.v1.platform.sse.connection.established'
    PLATFORM_SSE_CONNECTION_FAILED = 'g8e.v1.platform.sse.connection.failed'
    PLATFORM_SSE_CONNECTION_OPENED = 'g8e.v1.platform.sse.connection.opened'
    PLATFORM_SSE_KEEPALIVE_SENT = 'g8e.v1.platform.sse.keepalive.sent'
    PLATFORM_TELEMETRY_AUDIT_LOGGED = 'g8e.v1.platform.telemetry.audit.logged'
    PLATFORM_TELEMETRY_ERROR_LOGGED = 'g8e.v1.platform.telemetry.error.logged'
    PLATFORM_TELEMETRY_HEALTH_REPORTED = 'g8e.v1.platform.telemetry.health.reported'
    PLATFORM_TELEMETRY_PERFORMANCE_RECORDED = 'g8e.v1.platform.telemetry.performance.recorded'
    PLATFORM_USAGE_UPDATED = 'g8e.v1.platform.usage.updated'
    PLATFORM_VAULT_MODE_CHANGED = 'g8e.v1.platform.sentinel.mode.changed'
    PUBLIC_FEED_BATCH_ACKNOWLEDGED = 'g8e.v1.public.feed.batch.acknowledged'
    PUBLIC_FEED_BATCH_EXPORTED = 'g8e.v1.public.feed.batch.exported'
    PUBLIC_FEED_KEY_ROTATED = 'g8e.v1.public.feed.key.rotated'
    PUBLIC_FEED_PROOF_PUBLISHED = 'g8e.v1.public.feed.proof.published'


class ExecutionStatus(CaseInsensitiveStrEnum):
    CANCEL_REQUESTED = 'cancel_requested'
    CANCELLED = 'cancelled'
    COMPLETED = 'completed'
    DENIED = 'denied'
    EXECUTING = 'executing'
    FAILED = 'failed'
    FEEDBACK = 'feedback'
    PENDING = 'pending'
    TIMEOUT = 'timeout'


class FileOperation(CaseInsensitiveStrEnum):
    CREATE = 'create'
    DELETE = 'delete'
    INSERT = 'insert'
    PATCH = 'patch'
    READ = 'read'
    REPLACE = 'replace'
    UPDATE = 'update'
    WRITE = 'write'


class G8eAvailability(CaseInsensitiveStrEnum):
    OFFLINE = 'OFFLINE'
    ONLINE = 'ONLINE'


class GatewayMode(CaseInsensitiveStrEnum):
    GATEWAY = 'gateway'
    STATUS_OK = 'ok'


class HealthStatus(CaseInsensitiveStrEnum):
    HEALTHY = 'healthy'
    UNHEALTHY = 'unhealthy'


class HeartbeatType(CaseInsensitiveStrEnum):
    AUTOMATIC = 'automatic'
    BOOTSTRAP = 'bootstrap'
    REQUESTED = 'requested'


class HistoryActor(CaseInsensitiveStrEnum):
    NONE = ''
    G8EO = 'g8eo'
    SYSTEM = 'system'
    USER = 'user'


class InfrastructureStatus(CaseInsensitiveStrEnum):
    CRITICAL = 'critical'
    DEGRADED = 'degraded'
    HEALTHY = 'healthy'
    STABLE = 'stable'
    UNKNOWN = 'unknown'
    OPERATIONAL = 'operational'
    DOWN = 'down'


class Intent(CaseInsensitiveStrEnum):
    APIGATEWAY_DISCOVERY = 'apigateway_discovery'
    ACM_DISCOVERY = 'acm_discovery'
    ATHENA_DISCOVERY = 'athena_discovery'
    ATHENA_QUERY_EXECUTION = 'athena_query_execution'
    AURORA_CLONING = 'aurora_cloning'
    AURORA_CLUSTER_MANAGEMENT = 'aurora_cluster_management'
    AURORA_GLOBAL_DATABASE = 'aurora_global_database'
    AURORA_SCALING = 'aurora_scaling'
    AUTOSCALING_DISCOVERY = 'autoscaling_discovery'
    AUTOSCALING_MANAGEMENT = 'autoscaling_management'
    CLOUDFORMATION_DEPLOYMENT = 'cloudformation_deployment'
    CLOUDFRONT_DISCOVERY = 'cloudfront_discovery'
    CLOUDWATCH_LOGS = 'cloudwatch_logs'
    CLOUDWATCH_METRICS = 'cloudwatch_metrics'
    CODEDEPLOY_DISCOVERY = 'codedeploy_discovery'
    COST_EXPLORER = 'cost_explorer'
    DYNAMODB_DISCOVERY = 'dynamodb_discovery'
    DYNAMODB_READ = 'dynamodb_read'
    DYNAMODB_WRITE = 'dynamodb_write'
    EC_2_DISCOVERY = 'ec2_discovery'
    EC_2_MANAGEMENT = 'ec2_management'
    EC_2_SNAPSHOT_MANAGEMENT = 'ec2_snapshot_management'
    ECS_DISCOVERY = 'ecs_discovery'
    ECS_MANAGEMENT = 'ecs_management'
    EKS_DISCOVERY = 'eks_discovery'
    ELASTICACHE_DISCOVERY = 'elasticache_discovery'
    ELB_DISCOVERY = 'elb_discovery'
    EVENTBRIDGE_DISCOVERY = 'eventbridge_discovery'
    GLUE_DISCOVERY = 'glue_discovery'
    IAM_DISCOVERY = 'iam_discovery'
    KMS_CRYPTO = 'kms_crypto'
    KMS_DISCOVERY = 'kms_discovery'
    LAMBDA_DISCOVERY = 'lambda_discovery'
    LAMBDA_INVOKE = 'lambda_invoke'
    RDS_DISCOVERY = 'rds_discovery'
    RDS_MANAGEMENT = 'rds_management'
    RDS_SNAPSHOT_MANAGEMENT = 'rds_snapshot_management'
    ROUTE_53_DISCOVERY = 'route53_discovery'
    ROUTE_53_MANAGEMENT = 'route53_management'
    S3_BUCKET_DISCOVERY = 's3_bucket_discovery'
    S3_DELETE = 's3_delete'
    S3_READ = 's3_read'
    S3_WRITE = 's3_write'
    SECRETS_READ = 'secrets_read'
    SNS_DISCOVERY = 'sns_discovery'
    SNS_PUBLISH = 'sns_publish'
    SQS_DISCOVERY = 'sqs_discovery'
    SQS_MANAGEMENT = 'sqs_management'
    STEPFUNCTIONS_DISCOVERY = 'stepfunctions_discovery'
    STEPFUNCTIONS_EXECUTION = 'stepfunctions_execution'
    TERRAFORM_STATE = 'terraform_state'
    VPC_DISCOVERY = 'vpc_discovery'


class InvestigationStatus(CaseInsensitiveStrEnum):
    CLOSED = 'Closed'
    ESCALATED = 'Escalated'
    OPEN = 'Open'
    RESOLVED = 'Resolved'


class KVKey(CaseInsensitiveStrEnum):
    CACHE_PREFIX = 'g8e'
    CACHE_DOC = 'g8e:cache:doc:{collection}:{id}'
    CACHE_QUERY = 'g8e:cache:query:{collection}:{hash}'
    SESSION_WEB = 'g8e:sessions:{session.type}:{session.id}'
    SESSION_OPERATOR = 'g8e:sessions:operator:{operator.session.id}'
    SESSION_OPERATOR_BIND = 'g8e:sessions:operator:{operator.session.id}:bind'
    SESSION_WEB_BIND = 'g8e:sessions:web:{web.session.id}:bind'
    OPERATOR_FIRST_DEPLOYED = 'g8e:operator:{operator.id}:first.deployed'
    OPERATOR_TRACKED_STATUS = 'g8e:operator:{operator.id}:tracked.status'
    USER_OPERATORS = 'g8e:user:{user.id}:operators'
    USER_WEB_SESSIONS = 'g8e:user:{user.id}:web_sessions'
    USER_MEMORIES = 'g8e:user:{user.id}:memories'
    INVESTIGATION_ATTACHMENT = 'g8e:investigation:{investigation.id}:attachment:{attachment.id}'
    INVESTIGATION_ATTACHMENT_INDEX = 'g8e:investigation:{investigation.id}:attachment.index'
    AUTH_NONCE = 'g8e:auth:nonce:{nonce}'
    AUTH_TOKEN_DOWNLOAD = 'g8e:auth:token:download:{token}'
    AUTH_TOKEN_DEVICE = 'g8e:auth:token:device:{token}'
    AUTH_TOKEN_DEVICE_USES = 'g8e:auth:token:device:{token}:uses'
    AUTH_TOKEN_DEVICE_FINGERPRINTS = 'g8e:auth:token:device:{token}:fingerprints'
    AUTH_TOKEN_DEVICE_REG_LOCK = 'g8e:auth:token:device:{token}:reg.lock'
    AUTH_DEVICE_LIST = 'g8e:auth:device.list:{user.id}'
    AUTH_LOGIN_FAILED = 'g8e:auth:login:{identifier}:failed'
    AUTH_LOGIN_LOCK = 'g8e:auth:login:{identifier}:lock'
    AUTH_LOGIN_IP_ACCOUNTS = 'g8e:auth:login:ip:{ip}:accounts'
    EXECUTION_PENDING_CMD = 'g8e:execution:{execution.id}:pending.cmd'


class LlmModels(CaseInsensitiveStrEnum):
    ANTHROPIC_CLAUDE_4_5_HAIKU = 'claude-haiku-4-5'
    ANTHROPIC_CLAUDE_4_6_OPUS = 'claude-opus-4-6'
    ANTHROPIC_CLAUDE_4_6_SONNET = 'claude-sonnet-4-6'
    GEMINI_3_FLASH = 'gemini-3-flash-preview'
    GEMINI_3_1_FLASH_LITE = 'gemini-3.1-flash-lite'
    GEMINI_3_1_PRO = 'gemini-3.1-pro-preview'
    OLLAMA_GEMMA4_12B = 'gemma4:12b'
    OLLAMA_GEMMA4_E2B = 'gemma4:e2b'
    OLLAMA_GEMMA4_E4B = 'gemma4:e4b'
    LLAMACPP_GEMMA4_E2B = 'google_gemma-4-E2B-it-Q4_K_M.gguf'
    OPENAI_GPT_5_4 = 'gpt-5.4'
    OPENAI_GPT_5_4_MINI = 'gpt-5.4-mini'
    OPENAI_GPT_5_4_NANO = 'gpt-5.4-nano'
    OPENAI_GPT_5_4_PRO = 'gpt-5.4-pro'
    OLLAMA_GRANITE4_2_3B = 'granite4.2:3b'
    OLLAMA_GRANITE4_2_8B = 'granite4.2:8b'
    OLLAMA_LLAMA_3_2_3B = 'llama3.2:3b'
    OLLAMA_QWEN3_5_2B = 'qwen3.5:2b'


class LoginAuditEventType(CaseInsensitiveStrEnum):
    ACCOUNT_LOCKED = 'account_locked'
    ACCOUNT_UNLOCKED = 'account_unlocked'
    LOGIN_ANOMALY = 'login_anomaly'
    LOGIN_FAILED = 'login_failed'
    LOGIN_SUCCESS = 'login_success'


class NetworkProtocol(CaseInsensitiveStrEnum):
    TCP = 'tcp'
    UDP = 'udp'


class OperatorHistoryEventType(CaseInsensitiveStrEnum):
    API_KEY_REFRESHED = 'api.key.refreshed'
    AUTHENTICATED = 'authenticated'
    BOUND = 'bound'
    CLAIMED = 'claimed'
    CREATED = 'created'
    CREATED_FROM_REFRESH = 'created.from.refresh'
    DEACTIVATED = 'deactivated'
    HEARTBEAT_RECEIVED = 'heartbeat.received'
    RECONNECTED = 'reconnected'
    REGISTERED = 'registered'
    RESET = 'reset'
    SHUTDOWN_REQUESTED = 'shutdown.requested'
    SLOT_CONSUMED = 'slot.consumed'
    SLOT_CREATED = 'slot.created'
    SLOT_RELEASED = 'slot.released'
    STATUS_CHANGED = 'status.changed'
    STOPPED = 'stopped'
    TERMINATED = 'terminated'
    TERMINATED_FOR_REFRESH = 'terminated.for.refresh'
    UNBOUND = 'unbound'


class OperatorRole(CaseInsensitiveStrEnum):
    EMBEDDED = 'embedded'
    DATA = 'data'
    INFERENCE = 'inference'
    PROVENANCE = 'provenance'
    OBSERVER = 'observer'


class OperatorStatus(CaseInsensitiveStrEnum):
    ACTIVE = 'active'
    AVAILABLE = 'available'
    BOUND = 'bound'
    OFFLINE = 'offline'
    STALE = 'stale'
    STOPPED = 'stopped'
    TERMINATED = 'terminated'
    UNAVAILABLE = 'unavailable'


class OperatorToolName(CaseInsensitiveStrEnum):
    CHECK_PORT = 'check_port_status'
    FETCH_EXECUTION_OUTPUT = 'fetch_execution_output'
    FETCH_FILE_DIFF = 'fetch_file_diff'
    FETCH_FILE_HISTORY = 'fetch_file_history'
    FETCH_SESSION_HISTORY = 'fetch_session_history'
    FILE_CREATE = 'file_create_on_operator'
    FILE_READ = 'file_read_on_operator'
    FILE_UPDATE = 'file_update_on_operator'
    FILE_WRITE = 'file_write_on_operator'
    G8E_SEARCH_WEB = 'g8e_web_search'
    GET_COMMAND_CONSTRAINTS = 'get_command_constraints'
    GRANT_INTENT = 'grant_intent_permission'
    LIST_FILES = 'list_files_and_directories_with_detailed_metadata'
    SSH_INVENTORY = 'list_ssh_inventory'
    QUERY_INVESTIGATION_CONTEXT = 'query_investigation_context'
    READ_FILE_CONTENT = 'read_file_content'
    RECURSIVE_GREP = 'recursive_grep_search'
    RESTORE_FILE = 'restore_file'
    REVOKE_INTENT = 'revoke_intent_permission'
    RUN_COMMANDS = 'run_commands_with_operator'


class OperatorType(CaseInsensitiveStrEnum):
    EMBEDDED = 'embedded'
    REMOTE = 'remote'


class Platform(CaseInsensitiveStrEnum):
    DARWIN = 'darwin'
    LINUX = 'linux'
    WINDOWS = 'windows'


class Priority(IntEnum):
    LOW = 1
    MEDIUM = 2
    HIGH = 3
    CRITICAL = 4


class Prompt(CaseInsensitiveStrEnum):
    AGENT_MODE_CLOUD_OPERATOR_BOUND = 'g8e.cloud.bound'
    AGENT_MODE_G8E_BOUND = 'g8e.bound'
    AGENT_MODE_G8E_NOT_BOUND = 'g8e.not.bound'
    SECTION_AGENT_PERSONA = 'agent_persona'
    SECTION_CAPABILITIES = 'capabilities'
    SECTION_DISSENT = 'dissent'
    SECTION_DOCS = 'docs'
    SECTION_EXECUTION = 'execution'
    SECTION_IDENTITY = 'identity'
    SECTION_INVESTIGATION_CONTEXT = 'investigation_context'
    SECTION_LEARNED_CONTEXT = 'learned_context'
    SECTION_LOYALTY = 'loyalty'
    SECTION_RESPONSE_CONSTRAINTS = 'response_constraints'
    SECTION_SAFETY = 'safety'
    SECTION_VAULT_MODE = 'sentinel_mode'
    SECTION_SYSTEM_CONTEXT = 'system_context'
    SECTION_TOOLS = 'tools'
    SECTION_TRIAGE_CONTEXT = 'triage_context'


class ReasoningAgent(CaseInsensitiveStrEnum):
    SAGE = 'sage'
    DASH = 'dash'


class RiskLevel(CaseInsensitiveStrEnum):
    HIGH = 'HIGH'
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'


class RiskThreshold(CaseInsensitiveStrEnum):
    HIGH = 'high'
    LOW = 'low'
    MEDIUM = 'medium'


class ScrubberPriority(IntEnum):
    EXACT_CREDENTIAL = 10
    URL_OR_CONNECTION = 20
    CONTEXTUAL_CREDENTIAL = 30
    GENERIC_PII = 40


class SentinelStatus(CaseInsensitiveStrEnum):
    ERROR = 'error'
    FAILURE = 'failure'
    INTERRUPTED = 'interrupted'
    INVALID_EXIT = 'invalid_exit'
    KILLED = 'killed'
    MISUSE = 'misuse'
    NOT_EXECUTABLE = 'not_executable'
    NOT_FOUND = 'not_found'
    SUCCESS = 'success'
    TERMINATED = 'terminated'


class SessionEndReason(CaseInsensitiveStrEnum):
    INTEGRITY_FAILURE = 'integrity_failure'
    INVALIDATE_ALL = 'invalidate_all'
    SESSION_REGENERATION = 'session_regeneration'
    TIMEOUT_ABSOLUTE = 'timeout_absolute'
    TIMEOUT_IDLE = 'timeout_idle'
    USER_DELETED = 'user_deleted'
    LOGOUT = 'user_logout'


class SessionEventType(CaseInsensitiveStrEnum):
    G8E_BOUND = 'g8e.bound'
    G8E_UNBOUND = 'g8e.unbound'
    SESSION_CREATED = 'session.created'
    SESSION_ENDED = 'session.ended'
    SESSION_REGENERATED = 'session.regenerated'
    SESSION_SUSPICIOUS_ACTIVITY = 'session.suspicious_activity'
    SESSION_TIMEOUT_ABSOLUTE = 'session.timeout.absolute'
    SESSION_TIMEOUT_IDLE = 'session.timeout.idle'


class SessionKeyPrefix(CaseInsensitiveStrEnum):
    CLI = 'cli_session'
    OPERATOR = 'operator_session'
    WEB = 'web_session'


class SessionSuspiciousReason(CaseInsensitiveStrEnum):
    EXCESSIVE_IP_CHANGES = 'excessive_ip_changes'


class SessionType(CaseInsensitiveStrEnum):
    CLI = 'cli'
    OPERATOR = 'operator'
    WEB = 'web'
    APP = 'app'


class Severity(IntEnum):
    LOW = 1
    MEDIUM = 2
    HIGH = 3
    CRITICAL = 4


class SlashTier(IntEnum):
    TIER_1 = 1
    TIER_2 = 2
    TIER_3 = 3


class StreamStatus(CaseInsensitiveStrEnum):
    CANCELLED = 'cancelled'
    COMPLETED = 'completed'
    EXITED = 'exited'
    FAILED = 'failed'
    SUMMARY = 'summary'


class SystemHealth(CaseInsensitiveStrEnum):
    DEGRADED = 'degraded'
    HEALTHY = 'healthy'
    UNHEALTHY = 'unhealthy'
    UNKNOWN = 'unknown'


class TaskStatus(CaseInsensitiveStrEnum):
    CANCELLED = 'cancelled'
    COMPLETED = 'completed'
    IN_PROGRESS = 'executing'
    FAILED = 'failed'
    PENDING = 'pending'


class ThinkingPhase(CaseInsensitiveStrEnum):
    END = 'end'
    START = 'start'
    UPDATE = 'update'


class TieBreakReason(CaseInsensitiveStrEnum):
    SHORTEST = 'shortest'
    EXCLUDED_NEMESIS = 'excluded_nemesis'


class ToolCallDefaults(CaseInsensitiveStrEnum):
    LABEL = 'Processing'
    CATEGORY = 'general'
    ICON = 'sync'


class ToolCallStatus(CaseInsensitiveStrEnum):
    COMPLETED = 'completed'
    FAILED = 'failed'
    STARTED = 'started'


class ToolDisplayCategory(CaseInsensitiveStrEnum):
    EXECUTION = 'execution'
    FILE = 'file'
    GENERAL = 'general'
    NETWORK = 'network'
    SEARCH = 'search'


class ToolScope(CaseInsensitiveStrEnum):
    OPERATOR_GATED = 'operator_gated'
    UNIVERSAL = 'universal'


class TriageComplexityClassification(CaseInsensitiveStrEnum):
    SIMPLE = 'simple'
    COMPLEX = 'complex'


class TriageConfidence(CaseInsensitiveStrEnum):
    HIGH = 'high'
    LOW = 'low'


class TriageIntentClassification(CaseInsensitiveStrEnum):
    ACTION = 'action'
    INFORMATION = 'information'
    UNKNOWN = 'unknown'


class TriageRequestPosture(CaseInsensitiveStrEnum):
    NORMAL = 'normal'
    ADVERSARIAL = 'adversarial'
    ESCALATED = 'escalated'
    CONFUSED = 'confused'


class UserRole(CaseInsensitiveStrEnum):
    ADMIN = 'admin'
    OPERATOR = 'operator'
    OWNER = 'owner'
    USER = 'user'


class UserStatus(CaseInsensitiveStrEnum):
    ACTIVE = 'active'
    DISABLED = 'disabled'


class VaultMode(CaseInsensitiveStrEnum):
    RAW = 'raw'
    SCRUBBED = 'scrubbed'


class VersionStability(CaseInsensitiveStrEnum):
    BETA = 'beta'
    DEV = 'dev'
    STABLE = 'stable'
    UNSTABLE = 'unstable'
    DEPRECATED = 'deprecated'


class WorkflowType(CaseInsensitiveStrEnum):
    G8E_BOUND = 'g8e.bound'
    G8E_CLOUD_BOUND = 'g8e.cloud.bound'
    G8E_NOT_BOUND = 'g8e.not.bound'
    TRIAGE = 'triage'
    INVESTIGATION = 'investigation'

AISource = AiSource
AITaskId = AiTaskId
