// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: pubsub.proto

package pubsubv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PubSubMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubSubMessage) Reset() {
	*x = PubSubMessage{}
	mi := &file_pubsub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubSubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSubMessage) ProtoMessage() {}

func (x *PubSubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pubsub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSubMessage.ProtoReflect.Descriptor instead.
func (*PubSubMessage) Descriptor() ([]byte, []int) {
	return file_pubsub_proto_rawDescGZIP(), []int{0}
}

func (x *PubSubMessage) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PubSubMessage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PubSubMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PubSubEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Pattern       string                 `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubSubEvent) Reset() {
	*x = PubSubEvent{}
	mi := &file_pubsub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubSubEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSubEvent) ProtoMessage() {}

func (x *PubSubEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pubsub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSubEvent.ProtoReflect.Descriptor instead.
func (*PubSubEvent) Descriptor() ([]byte, []int) {
	return file_pubsub_proto_rawDescGZIP(), []int{1}
}

func (x *PubSubEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PubSubEvent) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PubSubEvent) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *PubSubEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pubsub_proto protoreflect.FileDescriptor

const file_pubsub_proto_rawDesc = "" +
	"\n" +
	"\fpubsub.proto\x12\rg8e.pubsub.v1\"U\n" +
	"\rPubSubMessage\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"i\n" +
	"\vPubSubEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04dataB=Z;github.com/g8e-ai/g8e/components/g8eo/shared/proto/pubsubv1b\x06proto3"

var (
	file_pubsub_proto_rawDescOnce sync.Once
	file_pubsub_proto_rawDescData []byte
)

func file_pubsub_proto_rawDescGZIP() []byte {
	file_pubsub_proto_rawDescOnce.Do(func() {
		file_pubsub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pubsub_proto_rawDesc), len(file_pubsub_proto_rawDesc)))
	})
	return file_pubsub_proto_rawDescData
}

var file_pubsub_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pubsub_proto_goTypes = []any{
	(*PubSubMessage)(nil), // 0: g8e.pubsub.v1.PubSubMessage
	(*PubSubEvent)(nil),   // 1: g8e.pubsub.v1.PubSubEvent
}
var file_pubsub_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pubsub_proto_init() }
func file_pubsub_proto_init() {
	if File_pubsub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pubsub_proto_rawDesc), len(file_pubsub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pubsub_proto_goTypes,
		DependencyIndexes: file_pubsub_proto_depIdxs,
		MessageInfos:      file_pubsub_proto_msgTypes,
	}.Build()
	File_pubsub_proto = out.File
	file_pubsub_proto_goTypes = nil
	file_pubsub_proto_depIdxs = nil
}
