// Copyright (c) 2026 Lateralus Labs, LLC.
// Use of this source code is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date listed in the LICENSE file, this software is
// released under the Apache License, Version 2.0.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: g8e/pubsub/v1/pubsub.proto

package pubsubv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PubSubMessage is the client-to-server WebSocket frame for pub/sub operations.
// Clients send this message to subscribe, unsubscribe, or publish on a channel.
type PubSubMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`   // Operation to perform: "subscribe", "psubscribe", "unsubscribe", or "publish".
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"` // Target channel name. Follows the convention "{prefix}:{operator_id}:{session_id}".
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`       // Payload bytes for publish actions. Empty for subscribe/unsubscribe.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubSubMessage) Reset() {
	*x = PubSubMessage{}
	mi := &file_g8e_pubsub_v1_pubsub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubSubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSubMessage) ProtoMessage() {}

func (x *PubSubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_g8e_pubsub_v1_pubsub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSubMessage.ProtoReflect.Descriptor instead.
func (*PubSubMessage) Descriptor() ([]byte, []int) {
	return file_g8e_pubsub_v1_pubsub_proto_rawDescGZIP(), []int{0}
}

func (x *PubSubMessage) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PubSubMessage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PubSubMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PubSubEvent is the server-to-client WebSocket frame delivered to subscribers.
// The broker emits events for message delivery, subscription acknowledgments, and errors.
type PubSubEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // Event type: "message", "pmessage", "subscribed", "unsubscribed", or "error".
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"` // Channel the event pertains to.
	Pattern       string                 `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"` // Pattern matched for pmessage events. Empty for direct channel deliveries.
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`       // Message payload for message/pmessage events. Empty for acknowledgment events.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubSubEvent) Reset() {
	*x = PubSubEvent{}
	mi := &file_g8e_pubsub_v1_pubsub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubSubEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSubEvent) ProtoMessage() {}

func (x *PubSubEvent) ProtoReflect() protoreflect.Message {
	mi := &file_g8e_pubsub_v1_pubsub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSubEvent.ProtoReflect.Descriptor instead.
func (*PubSubEvent) Descriptor() ([]byte, []int) {
	return file_g8e_pubsub_v1_pubsub_proto_rawDescGZIP(), []int{1}
}

func (x *PubSubEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PubSubEvent) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PubSubEvent) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *PubSubEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_g8e_pubsub_v1_pubsub_proto protoreflect.FileDescriptor

const file_g8e_pubsub_v1_pubsub_proto_rawDesc = "" +
	"\n" +
	"\x1ag8e/pubsub/v1/pubsub.proto\x12\rg8e.pubsub.v1\"U\n" +
	"\rPubSubMessage\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"i\n" +
	"\vPubSubEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04dataB=Z;github.com/g8e-ai/g8e/protocol/proto/g8e/pubsub/v1;pubsubv1b\x06proto3"

var (
	file_g8e_pubsub_v1_pubsub_proto_rawDescOnce sync.Once
	file_g8e_pubsub_v1_pubsub_proto_rawDescData []byte
)

func file_g8e_pubsub_v1_pubsub_proto_rawDescGZIP() []byte {
	file_g8e_pubsub_v1_pubsub_proto_rawDescOnce.Do(func() {
		file_g8e_pubsub_v1_pubsub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_g8e_pubsub_v1_pubsub_proto_rawDesc), len(file_g8e_pubsub_v1_pubsub_proto_rawDesc)))
	})
	return file_g8e_pubsub_v1_pubsub_proto_rawDescData
}

var file_g8e_pubsub_v1_pubsub_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_g8e_pubsub_v1_pubsub_proto_goTypes = []any{
	(*PubSubMessage)(nil), // 0: g8e.pubsub.v1.PubSubMessage
	(*PubSubEvent)(nil),   // 1: g8e.pubsub.v1.PubSubEvent
}
var file_g8e_pubsub_v1_pubsub_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_g8e_pubsub_v1_pubsub_proto_init() }
func file_g8e_pubsub_v1_pubsub_proto_init() {
	if File_g8e_pubsub_v1_pubsub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_g8e_pubsub_v1_pubsub_proto_rawDesc), len(file_g8e_pubsub_v1_pubsub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_g8e_pubsub_v1_pubsub_proto_goTypes,
		DependencyIndexes: file_g8e_pubsub_v1_pubsub_proto_depIdxs,
		MessageInfos:      file_g8e_pubsub_v1_pubsub_proto_msgTypes,
	}.Build()
	File_g8e_pubsub_v1_pubsub_proto = out.File
	file_g8e_pubsub_v1_pubsub_proto_goTypes = nil
	file_g8e_pubsub_v1_pubsub_proto_depIdxs = nil
}
