# Copyright (c) 2026 Lateralus Labs, LLC.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging
from typing import TypeVar
from collections.abc import Awaitable
from uuid import uuid4

T = TypeVar("T")

from app.models.settings import G8eeAppSettings
from app.constants import (
    DB_COLLECTION_CASES,
    DB_COLLECTION_TASKS,
    CaseStatus,
    ComponentName,
    EntityType,
    ErrorCode,
    EventType,
    TaskStatus,
)
from app.errors import (
    BusinessLogicError,
    DatabaseError,
    ResourceNotFoundError,
    ValidationError,
    G8eError,
)
from app.models import (
    CaseCreateRequest,
    CaseEventPayload,
    CaseUpdateRequest,
)
from app.models.cache import FieldFilter
from app.models.cases import CaseModel, HistoryEntry
from app.models.events import SessionEvent
from app.models.db_queries import CaseHistoryQuery
from app.models.http_context import RequestContext
from app.services.cache.cache_aside import CacheAsideService
from app.services.infra.event_service import EventService
from app.utils.timestamp import now
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.clients.governance_client import GovernanceClient

logger = logging.getLogger(__name__)

class CaseDataService:
    """Domain service for Case and Task data management using CacheAsideService."""

    def __init__(
        self,
        settings: G8eeAppSettings,
        cache: CacheAsideService,
        event_service: EventService,
        governance_client: GovernanceClient,
    ):
        self.settings = settings
        self.cache = cache
        self.event_service = event_service
        self._governance_client = governance_client
        self.cases_collection = settings.database.cases_collection or DB_COLLECTION_CASES
        self.tasks_collection = settings.database.tasks_collection or DB_COLLECTION_TASKS

    async def _with_error_handling(
        self,
        coro: Awaitable[T],
        action_msg: str,
        case_id: str,
        error_code: str
    ) -> T:
        """Helper to centralize database error handling boilerplate."""
        try:
            return await coro
        except G8eError:
            raise
        except Exception as e:
            logger.error("Failed to %s %s: %s", action_msg, case_id, e, exc_info=True)
            raise DatabaseError(
                message=f"Failed to {action_msg}: {e}",
                code=error_code,
                details={"case_id": case_id},
                cause=e,
                component=ComponentName.G8EE
            ) from e

    async def create_case(self, case_data: CaseCreateRequest, generated_title: str | None = None) -> CaseModel:
        """
        Create a new case.

        SECURITY: Case ID is ALWAYS generated server-side. Never accept from client.
        Title is AI-generated by internal_router before calling this method.
        Description is derived from initial_message.

        Args:
            case_data: Case creation data (with server-injected session fields)
            generated_title: AI-generated title from initial_message (optional)

        Returns:
            Created CaseModel
        """
        case_id = str(uuid4())

        # Use AI title if available, otherwise fall back to model-derived title
        title = generated_title or case_data.generated_title
        description = case_data.generated_description

        logger.info("Creating case: %s", case_id, extra={
            "case_id": case_id,
            "user_id": case_data.user_id,
            "source": case_data.source,
            "title_source": "ai" if generated_title else "derived"
        })

        ts = now()
        case = CaseModel(
            id=case_id,
            title=title,
            description=description,
            user_id=case_data.user_id,
            user_email=case_data.user_email,
            web_session_id=case_data.web_session_id,
            status=CaseStatus.NEW,
            priority=case_data.priority,
            severity=case_data.severity,
            source=case_data.source,
            tags=[],
            metadata={},
            created_at=ts,
            updated_at=ts,
        )

        async def _create():
            from app.models.pubsub_messages import G8eMessage
            from app.models.command_request_payloads import DocumentUpdateRequestPayload
            from app.constants import EventType, AITaskId

            payload = DocumentUpdateRequestPayload(
                collection=self.cases_collection,
                document_id=case_id,
                updates=case.model_dump(mode="json"),
                merge=False,
            )

            message = G8eMessage(
                id=case_id,
                source_component=ComponentName.G8EE,
                event_type=EventType.APP_CASE_CREATED,
                case_id=case_id,
                task_id=AITaskId.CASE,
                web_session_id=case_data.web_session_id,
                user_id=case_data.user_id,
                payload=payload,
            )
            await self._governance_client.submit_envelope(message)
            logger.info("Case created: %s via governance envelope", case_id, extra={"case_id": case_id})
            return case

        return await self._with_error_handling(
            _create(),
            action_msg="create case",
            case_id=case_id,
            error_code=ErrorCode.DB_WRITE_ERROR
        )

    async def get_case(self, case_id: str) -> CaseModel:
        """
        Get a case by ID.

        Args:
            case_id: Case ID

        Returns:
            CaseModel
        """
        if not case_id:
            raise ValidationError("Case ID is required")

        logger.info("Retrieving case: %s", case_id, extra={"case_id": case_id})

        async def _get():
            doc_data = await self.cache.get_document_with_cache(
                collection=self.cases_collection,
                document_id=case_id,
            )
            if not doc_data:
                raise ResourceNotFoundError(
                    message="Case not found",
                    resource_type=EntityType.CASE,
                    resource_id=case_id,
                    component=ComponentName.G8EE
                )

            doc_data["id"] = case_id
            return CaseModel.model_validate(doc_data)

        return await self._with_error_handling(
            _get(),
            action_msg="retrieve case",
            case_id=case_id,
            error_code=ErrorCode.DB_QUERY_ERROR
        )

    async def update_case(self, case_id: str, updates: CaseUpdateRequest) -> CaseModel:
        """
        Update a case.

        Args:
            case_id: Case ID
            updates: Validated update request

        Returns:
            Updated CaseModel
        """
        # Exclude context from update_fields as it's used for business context propagation,
        # not for updating the case document itself.
        update_fields = updates.model_dump(mode="json", exclude={"context"}, exclude_unset=True)

        if not update_fields:
            raise BusinessLogicError(
                message="No updates provided",
                code=ErrorCode.MISSING_REQUIRED_FIELD,
                details={"case_id": case_id},
                component=ComponentName.G8EE
            )

        logger.info("Updating case: %s", case_id, extra={
            "case_id": case_id,
            "fields": list(update_fields.keys())
        })

        existing = await self.get_case(case_id)
        updated_at = now()

        updated = existing.model_copy(update={**update_fields, "updated_at": updated_at})

        async def _update():
            db_payload = updated.model_dump(mode="json")
            context = updates.context if hasattr(updates, "context") else None

            if context:
                await self._governance_client.update_governed_doc(
                    collection=self.cases_collection,
                    document_id=case_id,
                    updates=db_payload,
                    event_type=EventType.APP_CASE_UPDATED,
                    case_id=case_id,
                    web_session_id=context.web_session_id,
                    user_id=context.user_id,
                    operator_id=context.operator_id,
                    operator_session_id=context.operator_session_id,
                    merge=True,
                )
                logger.info("Case updated: %s via governance envelope", case_id, extra={"case_id": case_id})
            else:
                raise ValidationError("RequestContext is required for case updates")
            return updated

        return await self._with_error_handling(
            _update(),
            action_msg="update case",
            case_id=case_id,
            error_code=ErrorCode.DB_WRITE_ERROR
        )

    async def delete_case(self, case_id: str, context: RequestContext) -> None:
        """
        Delete a case.

        Args:
            case_id: Case ID
            context: RequestContext for governance envelope
        """
        logger.info("Deleting case: %s", case_id, extra={"case_id": case_id})

        await self.get_case(case_id)

        async def _delete():
            await self._governance_client.delete_governed_doc(
                collection=self.cases_collection,
                document_id=case_id,
                event_type=EventType.APP_CASE_DELETED,
                case_id=case_id,
                web_session_id=context.web_session_id,
                user_id=context.user_id,
                operator_id=context.operator_id,
                operator_session_id=context.operator_session_id,
            )
            logger.info("Case deleted: %s via governance envelope", case_id, extra={"case_id": case_id})

        return await self._with_error_handling(
            _delete(),
            action_msg="delete case",
            case_id=case_id,
            error_code=ErrorCode.DB_WRITE_ERROR
        )

    async def publish_case_update_sse(
        self,
        case_id: str,
        payload: CaseEventPayload,
        user_id: str,
        web_session_id: str | None = None,
        cli_session_id: str | None = None,
        event_type: EventType = EventType.APP_CASE_UPDATED
    ) -> None:
        """
        Publish SSE event when case data changes.

        Args:
            case_id: Case ID
            payload: Typed case event payload
            user_id: User ID
            web_session_id: WebSession ID for routing (optional)
            cli_session_id: CLISession ID for routing (optional)
            event_type: Event type
        """
        if not self.event_service:
            logger.warning("Event service not configured in CaseDataService, skipping SSE publish")
            return

        if not web_session_id and not cli_session_id:
            logger.warning("No session ID provided for case SSE update, skipping", extra={"case_id": case_id})
            return

        try:
            from app.models.http_context import RequestContext
            from app.constants import ComponentName
            ctx = RequestContext(
                web_session_id=web_session_id,
                cli_session_id=cli_session_id,
                user_id=user_id,
                case_id=case_id,
                source_component=ComponentName.G8EE,
            )
            await self.event_service.publish(
                SessionEvent.from_context(
                    context=ctx,
                    event_type=event_type,
                    payload=payload,
                )
            )

            logger.info("Published case SSE update", extra={
                "case_id": case_id,
                "web_session_id": (web_session_id[:8] + "...") if web_session_id else None,
                "cli_session_id": (cli_session_id[:8] + "...") if cli_session_id else None,
            })

        except Exception as e:
            logger.warning("Failed to publish case SSE: %s", e, extra={
                "case_id": case_id,
                "web_session_id": (web_session_id[:8] + "...") if web_session_id else None,
                "cli_session_id": (cli_session_id[:8] + "...") if cli_session_id else None,
            })

    async def get_case_history(self, query: CaseHistoryQuery) -> list[HistoryEntry]:
        filters = [
            FieldFilter(field="case_id", op="==", value=query.case_id)
        ]

        if query.start_time:
            filters.append(FieldFilter(field="created_at", op=">=", value=query.start_time))

        if query.end_time:
            filters.append(FieldFilter(field="created_at", op="<=", value=query.end_time))

        if query.event_type:
            filters.append(FieldFilter(field="event_type", op="==", value=query.event_type))

        results = await self.cache.query_documents(
            collection=self.cases_collection,
            field_filters=[f.model_dump(mode="json") for f in filters],
            order_by={"created_at": "asc"},
            limit=query.limit
        )

        return [HistoryEntry.model_validate(entry) for entry in results]

    async def get_case_tasks(self, case_id: str, task_status: TaskStatus) -> list[dict[str, object]]:
        if not case_id:
            raise ValidationError("Case ID is required")

        filters = [
            FieldFilter(field="case_id", op="==", value=case_id)
        ]

        if task_status:
            filters.append(FieldFilter(field="status", op="==", value=task_status))

        return await self.cache.query_documents(
            collection=self.tasks_collection,
            field_filters=[f.model_dump(mode="json") for f in filters],
            order_by={"created_at": "desc"}
        )
