// Copyright (c) 2026 Lateralus Labs, LLC.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"

	pubsub "github.com/g8e-ai/g8e/internal/services/pubsub"
)

// ResultsPublisher is an autogenerated mock type for the ResultsPublisher type
type ResultsPublisher struct {
	mock.Mock
}

// PublishCancellationResult provides a mock function with given fields: ctx, result, originalMsg
func (_m *ResultsPublisher) PublishCancellationResult(ctx context.Context, result protoreflect.ProtoMessage, originalMsg *pubsub.PubSubCommandMessage) error {
	ret := _m.Called(ctx, result, originalMsg)

	if len(ret) == 0 {
		panic("no return value specified for PublishCancellationResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protoreflect.ProtoMessage, *pubsub.PubSubCommandMessage) error); ok {
		r0 = rf(ctx, result, originalMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishExecutionResult provides a mock function with given fields: ctx, result, originalMsg
func (_m *ResultsPublisher) PublishExecutionResult(ctx context.Context, result protoreflect.ProtoMessage, originalMsg *pubsub.PubSubCommandMessage) error {
	ret := _m.Called(ctx, result, originalMsg)

	if len(ret) == 0 {
		panic("no return value specified for PublishExecutionResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protoreflect.ProtoMessage, *pubsub.PubSubCommandMessage) error); ok {
		r0 = rf(ctx, result, originalMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishExecutionStatus provides a mock function with given fields: ctx, status, originalMsg
func (_m *ResultsPublisher) PublishExecutionStatus(ctx context.Context, status protoreflect.ProtoMessage, originalMsg *pubsub.PubSubCommandMessage) error {
	ret := _m.Called(ctx, status, originalMsg)

	if len(ret) == 0 {
		panic("no return value specified for PublishExecutionStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protoreflect.ProtoMessage, *pubsub.PubSubCommandMessage) error); ok {
		r0 = rf(ctx, status, originalMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishFileEditResult provides a mock function with given fields: ctx, result, originalMsg
func (_m *ResultsPublisher) PublishFileEditResult(ctx context.Context, result protoreflect.ProtoMessage, originalMsg *pubsub.PubSubCommandMessage) error {
	ret := _m.Called(ctx, result, originalMsg)

	if len(ret) == 0 {
		panic("no return value specified for PublishFileEditResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protoreflect.ProtoMessage, *pubsub.PubSubCommandMessage) error); ok {
		r0 = rf(ctx, result, originalMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishFsGrepResult provides a mock function with given fields: ctx, result, originalMsg
func (_m *ResultsPublisher) PublishFsGrepResult(ctx context.Context, result protoreflect.ProtoMessage, originalMsg *pubsub.PubSubCommandMessage) error {
	ret := _m.Called(ctx, result, originalMsg)

	if len(ret) == 0 {
		panic("no return value specified for PublishFsGrepResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protoreflect.ProtoMessage, *pubsub.PubSubCommandMessage) error); ok {
		r0 = rf(ctx, result, originalMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishFsListResult provides a mock function with given fields: ctx, result, originalMsg
func (_m *ResultsPublisher) PublishFsListResult(ctx context.Context, result protoreflect.ProtoMessage, originalMsg *pubsub.PubSubCommandMessage) error {
	ret := _m.Called(ctx, result, originalMsg)

	if len(ret) == 0 {
		panic("no return value specified for PublishFsListResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protoreflect.ProtoMessage, *pubsub.PubSubCommandMessage) error); ok {
		r0 = rf(ctx, result, originalMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishHeartbeat provides a mock function with given fields: ctx, heartbeat
func (_m *ResultsPublisher) PublishHeartbeat(ctx context.Context, heartbeat protoreflect.ProtoMessage) error {
	ret := _m.Called(ctx, heartbeat)

	if len(ret) == 0 {
		panic("no return value specified for PublishHeartbeat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, protoreflect.ProtoMessage) error); ok {
		r0 = rf(ctx, heartbeat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewResultsPublisher creates a new instance of ResultsPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResultsPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResultsPublisher {
	mock := &ResultsPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
