// Copyright (c) 2026 Lateralus Labs, LLC.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// TransactionAuditStore is an autogenerated mock type for the TransactionAuditStore type
type TransactionAuditStore struct {
	mock.Mock
}

// DocSet provides a mock function with given fields: collection, id, data
func (_m *TransactionAuditStore) DocSet(collection string, id string, data json.RawMessage) error {
	ret := _m.Called(collection, id, data)

	if len(ret) == 0 {
		panic("no return value specified for DocSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, json.RawMessage) error); ok {
		r0 = rf(collection, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactionAuditStore creates a new instance of TransactionAuditStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionAuditStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionAuditStore {
	mock := &TransactionAuditStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
