# Code generated by services/g8eo/cmd/exporter. DO NOT EDIT.

UNSUBSCRIBE = "unsubscribe"
PUBLISH = "publish"
MESSAGE = "message"
P_MESSAGE = "pmessage"
SUBSCRIBED = "subscribed"
SUBSCRIBE = "subscribe"
P_SUBSCRIBE = "psubscribe"
