#!/usr/bin/env bash
# Code generated by services/g8eo/cmd/exporter. DO NOT EDIT.

export G8E_PATH_SECRETS_DIR=".g8e/secrets"
export G8E_PATH_CA_CERT_PATH=".g8e/pki/trust/hub-bundle.pem"
export G8E_PATH_PROTOCOL_DIR="/app/protocol"
export G8E_PATH_PROTOCOL_CONSTANTS_DIR="/app/protocol/constants"
export G8E_PATH_SSH_CONFIG_PATH="/etc/g8e/ssh_config"
export G8E_PATH_DB_PATH=".g8e/data/g8e.db"
export G8E_PATH_APP_CERT_DIR=".g8e/pki/issued/apps"
export G8E_PATH_DOCS_DIR="/docs"
export G8E_PATH_PROTOCOL_MODELS_DIR="/app/protocol/models"
export G8E_PATH_PKI_DIR=".g8e/pki"
