#!/bin/bash
# g8e SSH management.
#
# Subcommands:
#   ssh-config   Configure ~/.ssh/config for high-concurrency operator streaming.

set -euo pipefail

_footer() {
    local rc=$?
    [[ $rc -eq 0 ]] || return
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  setup-ssh.sh done"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
}
trap _footer EXIT

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  setup-ssh.sh $*"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# =============================================================================
# ssh-config subcommand
# =============================================================================

if [[ "${1:-}" == "ssh-config" ]]; then
    shift
    _print_only=false
    _force=false
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --print) _print_only=true; shift ;;
            --force) _force=true; shift ;;
            --help|-h)
                echo "Usage: setup-ssh.sh ssh-config [--print] [--force]"
                echo ""
                echo "Options:"
                echo "  --print  Print the stanza without writing anything"
                echo "  --force  Replace stanza even if g8e block already present"
                exit 0 ;;
            *) echo "Unknown option: $1" >&2; exit 1 ;;
        esac
    done

    _ssh_dir="$HOME/.ssh"
    _sockets_dir="${_ssh_dir}/sockets"
    _config_file="${_ssh_dir}/config"
    _marker="# BEGIN g8e operator-stream config"

    _stanza="$(cat <<'STANZA'
# BEGIN g8e operator-stream config
# Generated by: ./g8e operator ssh-config
# Purpose: High-concurrency operator streaming (ControlMaster multiplexing + keep-alives)
# Docs: docs/components/g8ep.md
Host *
    ControlMaster auto
    ControlPath ~/.ssh/sockets/%r@%h:%p
    ControlPersist 1h
    ServerAliveInterval 30
    ServerAliveCountMax 3
    StrictHostKeyChecking accept-new
    Compression yes
    ForwardAgent no
# END g8e operator-stream config
STANZA
)"

    if [[ "$_print_only" == "true" ]]; then
        echo "--- Recommended ~/.ssh/config stanza for g8e operator streaming ---"
        echo
        echo "$_stanza"
        echo
        echo "--- Socket directory setup ---"
        echo "mkdir -p ${_sockets_dir}"
        echo "chmod 700 ${_sockets_dir}"
        exit 0
    fi

    if [[ ! -d "$_ssh_dir" ]]; then
        mkdir -p "$_ssh_dir"
        chmod 700 "$_ssh_dir"
        echo "Created ${_ssh_dir}"
    fi

    if [[ ! -d "$_sockets_dir" ]]; then
        mkdir -p "$_sockets_dir"
        chmod 700 "$_sockets_dir"
        echo "Created ${_sockets_dir}"
    else
        echo "${_sockets_dir}: already exists"
        chmod 700 "$_sockets_dir"
    fi

    if [[ "$_force" != "true" ]] && grep -qF "$_marker" "$_config_file" 2>/dev/null; then
        echo "g8e stanza already present in ${_config_file} — skipping (use --force to override)"
        echo
        echo "Current stanza:"
        sed -n "/^# BEGIN g8e operator-stream config/,/^# END g8e operator-stream config/p" "$_config_file"
        exit 0
    fi

    if [[ "$_force" == "true" ]] && grep -qF "$_marker" "$_config_file" 2>/dev/null; then
        _tmp="$(mktemp)"
        sed '/^# BEGIN g8e operator-stream config/,/^# END g8e operator-stream config/d' "$_config_file" > "$_tmp"
        mv "$_tmp" "$_config_file"
        chmod 600 "$_config_file"
        echo "Removed existing g8e stanza from ${_config_file}"
    fi

    if [[ -f "$_config_file" ]] && [[ -s "$_config_file" ]]; then
        _last_char="$(tail -c1 "$_config_file" | wc -l)"
        if [[ "$_last_char" -eq 0 ]]; then
            echo >> "$_config_file"
        fi
        echo >> "$_config_file"
    fi

    printf '%s\n' "$_stanza" >> "$_config_file"
    chmod 600 "$_config_file"
    echo "Appended g8e stanza to ${_config_file}"
    echo
    echo "Configuration summary:"
    echo "  Multiplexing socket dir : ${_sockets_dir}"
    echo "  ControlMaster           : auto (reuse connections to the same host)"
    echo "  ControlPersist          : 1h (master stays open 1 hour after last session)"
    echo "  ServerAliveInterval     : 30s (keep-alive ping every 30 seconds)"
    echo "  StrictHostKeyChecking   : accept-new (auto-accept new host keys, no prompts)"
    echo "  Compression             : yes (reduces binary transfer size)"
    echo "  ForwardAgent            : no (never forward SSH agent to remote hosts)"
    echo
    echo "Run './g8e operator stream <host>' to start streaming."
    exit 0
fi

echo "Error: Unknown subcommand. Use 'ssh-config' or --help for usage." >&2
exit 1
