#!/bin/bash
# g8e SSH management.
#
# Subcommands:
#   ssh-config   Configure ~/.ssh/config for high-concurrency operator streaming.
#   (default)    Mount an SSH directory into g8ep for operator streaming.
#                Run once; re-run to change the key path.
#
# Non-interactive setup usage:
#   --ssh-dir  path to SSH directory (default: ~/.ssh)

set -euo pipefail

_footer() {
    local rc=$?
    [[ $rc -eq 0 ]] || return
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  setup-ssh.sh done"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
}
trap _footer EXIT

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  setup-ssh.sh $*"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# =============================================================================
# ssh-config subcommand
# =============================================================================

if [[ "${1:-}" == "ssh-config" ]]; then
    shift
    _print_only=false
    _force=false
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --print) _print_only=true; shift ;;
            --force) _force=true; shift ;;
            --help|-h)
                echo "Usage: setup-ssh.sh ssh-config [--print] [--force]"
                echo ""
                echo "Options:"
                echo "  --print  Print the stanza without writing anything"
                echo "  --force  Replace stanza even if g8e block already present"
                exit 0 ;;
            *) echo "Unknown option: $1" >&2; exit 1 ;;
        esac
    done

    _ssh_dir="$HOME/.ssh"
    _sockets_dir="${_ssh_dir}/sockets"
    _config_file="${_ssh_dir}/config"
    _marker="# BEGIN g8e operator-stream config"

    _stanza="$(cat <<'STANZA'
# BEGIN g8e operator-stream config
# Generated by: ./g8e operator ssh-config
# Purpose: High-concurrency operator streaming (ControlMaster multiplexing + keep-alives)
# Docs: docs/components/g8ep.md
Host *
    ControlMaster auto
    ControlPath ~/.ssh/sockets/%r@%h:%p
    ControlPersist 1h
    ServerAliveInterval 30
    ServerAliveCountMax 3
    StrictHostKeyChecking accept-new
    Compression yes
    ForwardAgent no
# END g8e operator-stream config
STANZA
)"

    if [[ "$_print_only" == "true" ]]; then
        echo "--- Recommended ~/.ssh/config stanza for g8e operator streaming ---"
        echo
        echo "$_stanza"
        echo
        echo "--- Socket directory setup ---"
        echo "mkdir -p ${_sockets_dir}"
        echo "chmod 700 ${_sockets_dir}"
        exit 0
    fi

    if [[ ! -d "$_ssh_dir" ]]; then
        mkdir -p "$_ssh_dir"
        chmod 700 "$_ssh_dir"
        echo "Created ${_ssh_dir}"
    fi

    if [[ ! -d "$_sockets_dir" ]]; then
        mkdir -p "$_sockets_dir"
        chmod 700 "$_sockets_dir"
        echo "Created ${_sockets_dir}"
    else
        echo "${_sockets_dir}: already exists"
        chmod 700 "$_sockets_dir"
    fi

    if [[ "$_force" != "true" ]] && grep -qF "$_marker" "$_config_file" 2>/dev/null; then
        echo "g8e stanza already present in ${_config_file} — skipping (use --force to override)"
        echo
        echo "Current stanza:"
        sed -n "/^# BEGIN g8e operator-stream config/,/^# END g8e operator-stream config/p" "$_config_file"
        exit 0
    fi

    if [[ "$_force" == "true" ]] && grep -qF "$_marker" "$_config_file" 2>/dev/null; then
        _tmp="$(mktemp)"
        sed '/^# BEGIN g8e operator-stream config/,/^# END g8e operator-stream config/d' "$_config_file" > "$_tmp"
        mv "$_tmp" "$_config_file"
        chmod 600 "$_config_file"
        echo "Removed existing g8e stanza from ${_config_file}"
    fi

    if [[ -f "$_config_file" ]] && [[ -s "$_config_file" ]]; then
        _last_char="$(tail -c1 "$_config_file" | wc -l)"
        if [[ "$_last_char" -eq 0 ]]; then
            echo >> "$_config_file"
        fi
        echo >> "$_config_file"
    fi

    printf '%s\n' "$_stanza" >> "$_config_file"
    chmod 600 "$_config_file"
    echo "Appended g8e stanza to ${_config_file}"
    echo
    echo "Configuration summary:"
    echo "  Multiplexing socket dir : ${_sockets_dir}"
    echo "  ControlMaster           : auto (reuse connections to the same host)"
    echo "  ControlPersist          : 1h (master stays open 1 hour after last session)"
    echo "  ServerAliveInterval     : 30s (keep-alive ping every 30 seconds)"
    echo "  StrictHostKeyChecking   : accept-new (auto-accept new host keys, no prompts)"
    echo "  Compression             : yes (reduces binary transfer size)"
    echo "  ForwardAgent            : no (never forward SSH agent to remote hosts)"
    echo
    echo "Run './g8e operator stream <host>' to start streaming."
    exit 0
fi

# =============================================================================
# setup subcommand (default)
# =============================================================================

ARG_SSH_DIR=""
NON_INTERACTIVE=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --ssh-dir) ARG_SSH_DIR="$2"; shift 2 ;;
        --help|-h)
            echo "Usage: setup-ssh.sh [options]"
            echo ""
            echo "Options:"
            echo "  --ssh-dir  path to SSH directory to mount (default: ~/.ssh)"
            exit 0 ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

if [[ -n "$ARG_SSH_DIR" ]]; then
    NON_INTERACTIVE=true
fi

RED=$'\033[0;31m'
GREEN=$'\033[0;32m'
BLUE=$'\033[0;34m'
YELLOW=$'\033[1;33m'
CYAN=$'\033[0;36m'
BOLD=$'\033[1m'
NC=$'\033[0m'

_header() { echo -e "\n${BLUE}${BOLD}$1${NC}"; }
_ok()     { echo -e "  ${GREEN}[OK]${NC} $1"; }
_warn()   { echo -e "  ${YELLOW}[WARN]${NC} $1"; }
_err()    { echo -e "  ${RED}[ERROR]${NC} $1" >&2; }
_info()   { echo -e "  ${CYAN}$1${NC}"; }

_header "SSH Configuration"
echo
_info "g8ep mounts your SSH keys for operator streaming."
_info "The mounted directory is configured in docker-compose.yml as \${HOME}/.ssh."
echo
_info "  Default: ~/.ssh  — uses your existing SSH keys and config"
_info "  To use a custom directory, update the volume mount in docker-compose.yml"
echo

_default_ssh_dir="${HOME}/.ssh"

if [[ "$NON_INTERACTIVE" == true ]]; then
    SSH_DIR="$ARG_SSH_DIR"
else
    printf "  SSH directory to verify [%s]: " "$_default_ssh_dir"
    IFS= read -r _input
    SSH_DIR="${_input:-$_default_ssh_dir}"
fi

SSH_DIR="${SSH_DIR/#\~/$HOME}"

if [[ ! -d "$SSH_DIR" ]]; then
    _err "Directory not found: $SSH_DIR"
    exit 1
fi

_ok "SSH directory exists: $SSH_DIR"

echo
_info "g8ep mounts \${HOME}/.ssh from docker-compose.yml."
_info "If you need a custom path, update the ssh volume mount in docker-compose.yml"
_info "and run: ./g8e platform restart"
echo
