# Copyright (c) 2026 Lateralus Labs, LLC.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by scripts/data/generate_constants.py. DO NOT EDIT.

# Source: protocol/constants/paths.json

class PathConstants:
    """Collection of canonical G8E paths."""
    PATH_DB_PATH = ".g8e/data/g8e.db"
    PATH_PKI_DIR = ".g8e/pki"
    PATH_SECRETS_DIR = ".g8e/secrets"
    PATH_CA_CERT_PATH = ".g8e/pki/trust/hub-bundle.pem"
    PATH_APP_CERT_DIR = ".g8e/pki/issued/apps"
    PATH_DOCS_DIR = "/docs"
    PATH_PROTOCOL_DIR = "/app/protocol"
    PATH_PROTOCOL_CONSTANTS_DIR = "/app/protocol/constants"
    PATH_PROTOCOL_MODELS_DIR = "/app/protocol/models"
    PATH_SSH_CONFIG_PATH = "/etc/g8e/ssh_config"


class PortConstants:
    """Collection of canonical G8E ports."""
    PORT_OPERATOR_HTTP = 8440
    PORT_OPERATOR_BOOTSTRAP = 8441
    PORT_OPERATOR_PUBLIC = 8442
    PORT_G8EE_HTTP = 8443
    PORT_OPENCLAW_GATEWAY = 18789
