# Code generated by services/g8eo/cmd/exporter. DO NOT EDIT.

FIELD_CHANNEL = "channel"
FIELD_DATA = "data"
FIELD_MESSAGE = "message"
FIELD_PATTERN = "pattern"
FIELD_TYPE = "type"
FIELD_SENDER = "sender"
FIELD_ACTION = "action"
