// Copyright (c) 2026 Lateralus Labs, LLC.
// Use of this source code is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date listed in the LICENSE file, this software is
// released under the Apache License, Version 2.0.

package main

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRegistryKeyToJSEnum_SplitsPascalCaseIntoUpperSnakeCase(t *testing.T) {
	tests := []struct {
		name string
		key  string
		want string
	}{
		{name: "empty key", key: "", want: ""},
		{name: "single upper letter", key: "A", want: "A"},
		{name: "single word", key: "Heartbeat", want: "HEARTBEAT"},
		{name: "two words", key: "CaseCreated", want: "CASE_CREATED"},
		{name: "three words", key: "OperatorCommandRequested", want: "OPERATOR_COMMAND_REQUESTED"},
		{name: "acronym followed by word stays together until the last capital", key: "HTTPServerStarted", want: "HTTP_SERVER_STARTED"},
		{name: "trailing acronym is not split", key: "OperatorMCP", want: "OPERATOR_MCP"},
		{name: "digit followed by capital splits", key: "Tier1Result", want: "TIER1_RESULT"},
		{name: "lowercase followed by digit does not split", key: "Sha256Computed", want: "SHA256_COMPUTED"},
		{name: "already upper snake is unchanged apart from case", key: "ALREADY_UPPER", want: "ALREADY_UPPER"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, registryKeyToJSEnum(tt.key))
		})
	}
}

func TestShouldSplitPascal_BoundariesBetweenCharacterClasses(t *testing.T) {
	tests := []struct {
		name  string
		input string
		index int
		want  bool
	}{
		{name: "lower to upper", input: "aB", index: 1, want: true},
		{name: "digit to upper", input: "1B", index: 1, want: true},
		{name: "upper to lower", input: "Ab", index: 1, want: false},
		{name: "upper to upper before lower splits the acronym boundary", input: "ABc", index: 1, want: true},
		{name: "upper to upper at end of input", input: "AB", index: 1, want: false},
		{name: "upper to upper before upper", input: "ABC", index: 1, want: false},
		{name: "lower to lower", input: "ab", index: 1, want: false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, shouldSplitPascal([]rune(tt.input), tt.index))
		})
	}
}

func dashboardFixture() registryFile {
	return registryFile{Events: map[string]eventEntry{
		"OperatorCommandRequested": {
			GoConst:     "EventOperatorCommandRequested",
			Value:       "g8e.v1.operator.command.requested",
			Kind:        "request",
			Transport:   []string{"governed", "pubsub"},
			Producers:   []string{"gateway", "ensemble"},
			Persistence: "operator.audit_log",
			Governance:  &governanceBlock{ActionType: "EXECUTE_BASH", Payload: "g8e.operator.v1.CommandRequested"},
		},
		"AppCaseCreated": {
			GoConst:     "EventAppCaseCreated",
			Value:       "g8e.v1.app.case.created",
			Kind:        "outcome",
			Persistence: "ephemeral",
			Reserved:    true,
		},
	}}
}

func TestGenerateDashboardEventsJS_EmitsFrozenEventTypeMapSortedByKey(t *testing.T) {
	got, err := generateDashboardEventsJS(dashboardFixture())

	require.NoError(t, err)
	assert.Contains(t, got, "// Code generated by constgen; DO NOT EDIT.")
	assert.Contains(t, got, "export const EventType = Object.freeze({\n"+
		"    APP_CASE_CREATED: 'g8e.v1.app.case.created',\n"+
		"    OPERATOR_COMMAND_REQUESTED: 'g8e.v1.operator.command.requested',\n"+
		"});")
}

func TestGenerateDashboardEventsJS_EmitsGovernedRequestMetadata(t *testing.T) {
	got, err := generateDashboardEventsJS(dashboardFixture())

	require.NoError(t, err)
	assert.Contains(t, got, "    OPERATOR_COMMAND_REQUESTED: Object.freeze({\n"+
		"        kind: 'request',\n"+
		"        transport: ['governed', 'pubsub'],\n"+
		"        producers: ['gateway', 'ensemble'],\n"+
		"        persistence: 'operator.audit_log',\n"+
		"        actionType: 'EXECUTE_BASH',\n"+
		"        payload: 'g8e.operator.v1.CommandRequested',\n"+
		"    }),\n")
}

func TestGenerateDashboardEventsJS_OmitsAbsentOptionalFieldsAndMarksReservedEvents(t *testing.T) {
	got, err := generateDashboardEventsJS(dashboardFixture())

	require.NoError(t, err)
	registry := got[strings.Index(got, "export const EventRegistry"):]
	caseCreated := between(t, registry, "    APP_CASE_CREATED: Object.freeze({", "    }),")
	assert.NotContains(t, caseCreated, "transport:")
	assert.NotContains(t, caseCreated, "producers:")
	assert.NotContains(t, caseCreated, "actionType:")
	assert.NotContains(t, caseCreated, "payload:")
	assert.Contains(t, caseCreated, "reserved: true,")

	command := between(t, registry, "    OPERATOR_COMMAND_REQUESTED: Object.freeze({", "    }),")
	assert.NotContains(t, command, "reserved:")
}

func TestGenerateDashboardEventsJS_EmptyRegistryStillEmitsBothFrozenObjects(t *testing.T) {
	got, err := generateDashboardEventsJS(registryFile{})

	require.NoError(t, err)
	assert.Contains(t, got, "export const EventType = Object.freeze({\n});")
	assert.Contains(t, got, "export const EventRegistry = Object.freeze({\n});")
}

func TestGenerateDashboardEventsJS_IsDeterministicAcrossMapIterationOrder(t *testing.T) {
	first, err := generateDashboardEventsJS(dashboardFixture())
	require.NoError(t, err)
	for range 20 {
		again, err := generateDashboardEventsJS(dashboardFixture())
		require.NoError(t, err)
		require.Equal(t, first, again)
	}
}
