// Copyright (c) 2026 Lateralus Labs, LLC.
// Use of this source code is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date listed in the LICENSE file, this software is
// released under the Apache License, Version 2.0.

package main

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestTitleCase_UppercasesOnlyTheFirstByte(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{name: "empty", input: "", want: ""},
		{name: "lowercase word", input: "request", want: "Request"},
		{name: "already capitalised", input: "Outcome", want: "Outcome"},
		{name: "rest of the word is left alone", input: "sTREAM", want: "STREAM"},
		{name: "single letter", input: "f", want: "F"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, titleCase(tt.input))
		})
	}
}

func TestGoStringSlice_RendersNilForEmptyAndQuotedLiteralOtherwise(t *testing.T) {
	tests := []struct {
		name   string
		values []string
		want   string
	}{
		{name: "nil slice", values: nil, want: "nil"},
		{name: "empty slice", values: []string{}, want: "nil"},
		{name: "single value", values: []string{"gateway"}, want: `[]string{"gateway"}`},
		{name: "multiple values keep order", values: []string{"sse", "pubsub"}, want: `[]string{"sse", "pubsub"}`},
		{name: "quotes and backslashes are escaped", values: []string{`a"b`, `c\d`}, want: `[]string{"a\"b", "c\\d"}`},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, goStringSlice(tt.values))
		})
	}
}

func TestSortedMapKeys_ReturnsKeysInLexicalOrder(t *testing.T) {
	got := sortedMapKeys(map[string]int{"b": 1, "c": 2, "a": 3})

	assert.Equal(t, []string{"a", "b", "c"}, got)
	assert.Empty(t, sortedMapKeys(map[string]int{}))
}

func TestSortedEventKeys_ReturnsRegistryKeysInLexicalOrder(t *testing.T) {
	got := sortedEventKeys(map[string]eventEntry{"Zeta": {}, "Alpha": {}, "Mid": {}})

	assert.Equal(t, []string{"Alpha", "Mid", "Zeta"}, got)
}

func TestActionTypeGoConst_ResolvesByWireValueNotRegistryKey(t *testing.T) {
	actionTypes := map[string]actionTypeMeta{
		"KEY_A": {GoConst: "ActionA", Value: "A_WIRE"},
		"KEY_B": {GoConst: "ActionB", Value: "B_WIRE"},
	}

	got, err := actionTypeGoConst(actionTypes, "B_WIRE")
	require.NoError(t, err)
	assert.Equal(t, "ActionB", got)

	_, err = actionTypeGoConst(actionTypes, "KEY_B")
	require.Error(t, err, "registry key must not resolve; only the wire value does")
	assert.Contains(t, err.Error(), `unknown governance.action_type "KEY_B"`)
}

func eventsFixture() (registryFile, map[string]actionTypeMeta) {
	reg := registryFile{Events: map[string]eventEntry{
		"OperatorCommandRequested": {
			GoConst:     "EventOperatorCommandRequested",
			Value:       "g8e.v1.operator.command.requested",
			Kind:        "request",
			Transport:   []string{"governed"},
			Producers:   []string{"gateway", "ensemble"},
			Persistence: "operator.audit_log",
			Outcomes:    []string{"OperatorCommandCompleted"},
			Governance:  &governanceBlock{ActionType: "EXECUTE_BASH", Payload: "g8e.operator.v1.CommandRequested"},
		},
		"OperatorCommandCompleted": {
			GoConst:     "EventOperatorCommandCompleted",
			Value:       "g8e.v1.operator.command.completed",
			Kind:        "outcome",
			Producers:   []string{"operator"},
			Persistence: "operator.audit_log",
			Reserved:    true,
		},
	}}
	actionTypes := map[string]actionTypeMeta{
		"EXECUTE_BASH": {GoConst: "ActionExecuteBash", Value: "EXECUTE_BASH", Mutation: true},
	}
	return reg, actionTypes
}

func TestGenerateEventsGo_DeclaresOneTypedConstantPerEventSortedByRegistryKey(t *testing.T) {
	reg, actionTypes := eventsFixture()

	got, err := generateEventsGo(reg, map[string]string{}, actionTypes)

	require.NoError(t, err)
	requireParsesAsGo(t, got)
	assert.Contains(t, got, "// Code generated by constgen; DO NOT EDIT.")
	assert.Contains(t, got, "type EventType string")
	completed := strings.Index(got, `const EventOperatorCommandCompleted EventType = "g8e.v1.operator.command.completed"`)
	requested := strings.Index(got, `const EventOperatorCommandRequested EventType = "g8e.v1.operator.command.requested"`)
	require.GreaterOrEqual(t, completed, 0)
	require.GreaterOrEqual(t, requested, 0)
	assert.Less(t, completed, requested, "OperatorCommandCompleted sorts before OperatorCommandRequested")
}

func TestGenerateEventsGo_RegistryEntryCarriesGovernanceTransportAndOutcomes(t *testing.T) {
	reg, actionTypes := eventsFixture()

	got, err := generateEventsGo(reg, map[string]string{}, actionTypes)

	require.NoError(t, err)
	entry := between(t, got, "\tEventOperatorCommandRequested: {\n", "\t},\n")
	assert.Contains(t, entry, `Key: "OperatorCommandRequested",`)
	assert.Contains(t, entry, "Kind: EventKindRequest,")
	assert.Contains(t, entry, `Transport: []string{"governed"},`)
	assert.Contains(t, entry, `Producers: []string{"gateway", "ensemble"},`)
	assert.Contains(t, entry, `Persistence: "operator.audit_log",`)
	assert.Contains(t, entry, "GovernanceAction: ActionExecuteBash,")
	assert.Contains(t, entry, `GovernancePayload: "g8e.operator.v1.CommandRequested",`)
	assert.Contains(t, entry, `Outcomes: []string{"OperatorCommandCompleted"},`)
	assert.NotContains(t, entry, "Reserved")
}

func TestGenerateEventsGo_UngovernedReservedEntryOmitsGovernanceAndNilsTransport(t *testing.T) {
	reg, actionTypes := eventsFixture()

	got, err := generateEventsGo(reg, map[string]string{}, actionTypes)

	require.NoError(t, err)
	entry := between(t, got, "\tEventOperatorCommandCompleted: {\n", "\t},\n")
	assert.Contains(t, entry, "Kind: EventKindOutcome,")
	assert.Contains(t, entry, "Transport: nil,")
	assert.Contains(t, entry, "Reserved: true,")
	assert.NotContains(t, entry, "Governance")
	assert.NotContains(t, entry, "Outcomes")
}

func TestGenerateEventsGo_AppendsOperatorHierarchyAfterRegistry(t *testing.T) {
	reg, actionTypes := eventsFixture()
	hierarchy := map[string]string{"EventOperatorCommandRequested": "Command.Requested"}

	got, err := generateEventsGo(reg, hierarchy, actionTypes)

	require.NoError(t, err)
	requireParsesAsGo(t, got)
	registryEnd := strings.Index(got, "}}\n\n")
	hierarchyStart := strings.Index(got, "type _EventOperator struct {")
	require.GreaterOrEqual(t, registryEnd, 0)
	require.Greater(t, hierarchyStart, registryEnd)
	assert.Contains(t, got, "Requested: EventOperatorCommandRequested,")
}

func TestGenerateEventsGo_FailsNamingTheEventWhoseActionTypeIsUnknown(t *testing.T) {
	reg, _ := eventsFixture()

	_, err := generateEventsGo(reg, map[string]string{}, map[string]actionTypeMeta{})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "OperatorCommandRequested")
	assert.Contains(t, err.Error(), `unknown governance.action_type "EXECUTE_BASH"`)
}

func TestGenerateEventsGo_IsDeterministicAcrossMapIterationOrder(t *testing.T) {
	reg, actionTypes := eventsFixture()
	hierarchy := map[string]string{
		"EventOperatorCommandRequested": "Command.Requested",
		"EventOperatorCommandCompleted": "Command.Completed",
		"EventOperatorHeartbeat":        "Heartbeat",
	}
	first, err := generateEventsGo(reg, hierarchy, actionTypes)
	require.NoError(t, err)

	for range 20 {
		again, err := generateEventsGo(reg, hierarchy, actionTypes)
		require.NoError(t, err)
		require.Equal(t, first, again)
	}
}

func TestGenerateOperatorHierarchy_NestsStructsByPathAndKeepsLeavesAsEventTypes(t *testing.T) {
	hierarchy := map[string]string{
		"EventOperatorCommandRequested": "Command.Requested",
		"EventOperatorCommandCompleted": "Command.Completed",
		"EventOperatorHeartbeat":        "Heartbeat",
	}

	got := generateOperatorHierarchy(hierarchy)

	want := "type _EventOperator struct {\n" +
		"\tCommand _EventOperatorCommand\n" +
		"\tHeartbeat EventType\n" +
		"}\n\n" +
		"type _EventOperatorCommand struct {\n" +
		"\tCompleted EventType\n" +
		"\tRequested EventType\n" +
		"}\n\n" +
		"var Event = struct {\n" +
		"\tOperator _EventOperator\n" +
		"}{\n" +
		"\tOperator: _EventOperator{\n" +
		"\t\tCommand: _EventOperatorCommand{\n" +
		"\t\t\tCompleted: EventOperatorCommandCompleted,\n" +
		"\t\t\tRequested: EventOperatorCommandRequested,\n" +
		"\t\t},\n" +
		"\t\tHeartbeat: EventOperatorHeartbeat,\n" +
		"\t},\n" +
		"}\n"
	assert.Equal(t, want, got)
}

func TestGenerateOperatorHierarchy_SupportsMoreThanTwoLevelsOfNesting(t *testing.T) {
	hierarchy := map[string]string{
		"EventOperatorAuditUserRecordRequested": "Audit.User.Record.Requested",
		"EventOperatorAuditUserRecordCreated":   "Audit.User.Record.Created",
		"EventOperatorAuditSystemRecorded":      "Audit.System.Recorded",
	}

	got := generateOperatorHierarchy(hierarchy)

	requireParsesAsGo(t, "package constants\ntype EventType string\n"+got)
	for _, typeDecl := range []string{
		"type _EventOperator struct {\n\tAudit _EventOperatorAudit\n}\n",
		"type _EventOperatorAudit struct {\n\tSystem _EventOperatorAuditSystem\n\tUser _EventOperatorAuditUser\n}\n",
		"type _EventOperatorAuditSystem struct {\n\tRecorded EventType\n}\n",
		"type _EventOperatorAuditUser struct {\n\tRecord _EventOperatorAuditUserRecord\n}\n",
		"type _EventOperatorAuditUserRecord struct {\n\tCreated EventType\n\tRequested EventType\n}\n",
	} {
		assert.Contains(t, got, typeDecl)
	}
	assert.Contains(t, got, "\t\t\t\t\tCreated: EventOperatorAuditUserRecordCreated,\n")
}
