// Copyright (c) 2026 Lateralus Labs, LLC.
// Use of this source code is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date listed in the LICENSE file, this software is
// released under the Apache License, Version 2.0.

package main

import (
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const (
	eventsRel    = "protocol/constants/events.json"
	statusRel    = "protocol/constants/status.json"
	hierarchyRel = "internal/tools/constgen/operator_hierarchy.json"

	eventsGoRel      = "internal/constants/events_gen.go"
	actionTypesGoRel = "internal/constants/action_types_gen.go"
	consoleTSRel   = "console/src/generated/events.ts"
	pythonEventsRel  = "protocol/python/g8e/_data/events.json"
)

// governanceBlock is the anonymous governance struct embedded in eventEntry.
type governanceBlock = struct {
	ActionType string `json:"action_type"`
	Payload    string `json:"payload"`
}

// requireParsesAsGo fails the test unless src is syntactically valid Go.
func requireParsesAsGo(t *testing.T, src string) {
	t.Helper()
	_, err := parser.ParseFile(token.NewFileSet(), "generated.go", src, parser.AllErrors)
	require.NoError(t, err, "generated source must be valid Go:\n%s", src)
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
}

// newConstgenRoot returns a temp repo root holding copies of the real input
// registries and the directories the generator writes into.
func newConstgenRoot(t *testing.T) string {
	t.Helper()
	repo, err := findRepoRoot()
	require.NoError(t, err)
	root := t.TempDir()
	for _, rel := range []string{eventsRel, statusRel, hierarchyRel} {
		data, err := os.ReadFile(filepath.Join(repo, rel))
		require.NoError(t, err)
		writeFile(t, filepath.Join(root, rel), string(data))
	}
	for _, rel := range []string{eventsGoRel, consoleTSRel, pythonEventsRel} {
		require.NoError(t, os.MkdirAll(filepath.Dir(filepath.Join(root, rel)), 0o755))
	}
	return root
}

func sampleOutputs() generationOutputs {
	return generationOutputs{
		EventsGo:      "package constants // events\n",
		ActionTypesGo: "package constants // actions\n",
		ConsoleTS:   "export const EventType = {};\n",
	}
}

// seedGenerated writes out to every target under root and syncs the bundled
// Python registry from the canonical events.json already present there.
func seedGenerated(t *testing.T, root string, out generationOutputs) {
	t.Helper()
	writeFile(t, filepath.Join(root, eventsGoRel), out.EventsGo)
	writeFile(t, filepath.Join(root, actionTypesGoRel), out.ActionTypesGo)
	writeFile(t, filepath.Join(root, consoleTSRel), out.ConsoleTS)
	require.NoError(t, syncBundledPythonEvents(root))
}

func TestLoadOperatorHierarchy_ParsesPathMapping(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, hierarchyRel), `{"EventOperatorHeartbeat":"Heartbeat","EventOperatorCommandRequested":"Command.Requested"}`)

	got, err := loadOperatorHierarchy(root)

	require.NoError(t, err)
	assert.Equal(t, map[string]string{
		"EventOperatorHeartbeat":        "Heartbeat",
		"EventOperatorCommandRequested": "Command.Requested",
	}, got)
}

func TestLoadOperatorHierarchy_ReportsMissingAndMalformedFiles(t *testing.T) {
	t.Run("missing file", func(t *testing.T) {
		_, err := loadOperatorHierarchy(t.TempDir())

		require.Error(t, err)
		assert.ErrorIs(t, err, os.ErrNotExist)
		assert.Contains(t, err.Error(), "read operator_hierarchy.json")
	})
	t.Run("malformed json", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, hierarchyRel), `{"EventOperatorHeartbeat":`)

		_, err := loadOperatorHierarchy(root)

		require.Error(t, err)
		assert.Contains(t, err.Error(), "decode operator_hierarchy.json")
	})
	t.Run("values that are not strings", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, hierarchyRel), `{"EventOperatorHeartbeat":["Heartbeat"]}`)

		_, err := loadOperatorHierarchy(root)

		require.Error(t, err)
		assert.Contains(t, err.Error(), "decode operator_hierarchy.json")
	})
}

func TestFileHeader_NamesGeneratorAndMarksFileAsGenerated(t *testing.T) {
	got := fileHeader("constgen")

	assert.Contains(t, got, "// Code generated by constgen; DO NOT EDIT.")
	assert.Contains(t, got, "Business Source License")
	assert.Equal(t, "\n\n", got[len(got)-2:], "header ends with a blank line so the package clause stands apart")
}

func TestBundledPythonEventsPath_IsUnderPythonProtocolDataDir(t *testing.T) {
	assert.Equal(t, filepath.Join("root", pythonEventsRel), bundledPythonEventsPath("root"))
}

func TestGenerateAll_ProducesParseableGoAndEveryRegistryEvent(t *testing.T) {
	repo, err := findRepoRoot()
	require.NoError(t, err)
	events, err := loadRegistry(filepath.Join(repo, eventsRel))
	require.NoError(t, err)
	actionTypes, err := loadActionTypeMeta(filepath.Join(repo, statusRel))
	require.NoError(t, err)

	out, err := generateAll(repo, events, actionTypes)

	require.NoError(t, err)
	requireParsesAsGo(t, out.EventsGo)
	requireParsesAsGo(t, out.ActionTypesGo)
	for name, source := range map[string]string{"events": out.EventsGo, "actions": out.ActionTypesGo} {
		formatted, err := format.Source([]byte(source))
		require.NoError(t, err)
		assert.Equal(t, source, string(formatted), "%s constants must already be gofmt-clean", name)
	}
	for _, entry := range events.Events {
		assert.Contains(t, out.EventsGo, entry.GoConst)
		assert.Contains(t, out.ConsoleTS, entry.Value)
	}
	for _, meta := range actionTypes {
		assert.Contains(t, out.ActionTypesGo, meta.GoConst)
	}
}

func TestGenerateAll_FailsWhenOperatorHierarchyIsMissing(t *testing.T) {
	_, err := generateAll(t.TempDir(), registryFile{}, nil)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "operator_hierarchy.json")
}

func TestGenerateAll_FailsWhenGovernedEventNamesUnknownActionType(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, hierarchyRel), `{}`)
	reg := registryFile{Events: map[string]eventEntry{
		"Command": {
			GoConst:    "EventCommandRequested",
			Value:      "g8e.v1.app.command.requested",
			Kind:       "request",
			Governance: &governanceBlock{ActionType: "NO_SUCH_ACTION", Payload: "p"},
		},
	}}

	_, err := generateAll(root, reg, map[string]actionTypeMeta{})

	require.Error(t, err)
	assert.Contains(t, err.Error(), "Command")
	assert.Contains(t, err.Error(), `unknown governance.action_type "NO_SUCH_ACTION"`)
}

func TestWriteGenerated_WritesEveryTargetAndSyncsBundledPythonRegistry(t *testing.T) {
	root := newConstgenRoot(t)
	out := sampleOutputs()

	require.NoError(t, writeGenerated(root, out))

	for rel, want := range map[string]string{
		eventsGoRel:      out.EventsGo,
		actionTypesGoRel: out.ActionTypesGo,
		consoleTSRel:   out.ConsoleTS,
	} {
		got, err := os.ReadFile(filepath.Join(root, rel))
		require.NoError(t, err, rel)
		assert.Equal(t, want, string(got), rel)
	}
	canonical, err := os.ReadFile(filepath.Join(root, eventsRel))
	require.NoError(t, err)
	bundled, err := os.ReadFile(filepath.Join(root, pythonEventsRel))
	require.NoError(t, err)
	assert.Equal(t, canonical, bundled)
}

func TestWriteGenerated_FailsWhenTargetDirectoryIsMissing(t *testing.T) {
	root := newConstgenRoot(t)
	require.NoError(t, os.RemoveAll(filepath.Join(root, "console")))

	err := writeGenerated(root, sampleOutputs())

	require.Error(t, err)
	assert.ErrorIs(t, err, os.ErrNotExist)
	assert.Contains(t, err.Error(), "write ")
}

func TestWriteGenerated_FailsWhenCanonicalEventsRegistryIsMissing(t *testing.T) {
	root := newConstgenRoot(t)
	require.NoError(t, os.Remove(filepath.Join(root, eventsRel)))

	err := writeGenerated(root, sampleOutputs())

	require.Error(t, err)
	assert.ErrorIs(t, err, os.ErrNotExist)
	assert.Contains(t, err.Error(), "read canonical events.json")
}

func TestSyncBundledPythonEvents_FailsWhenBundleDirectoryIsMissing(t *testing.T) {
	root := newConstgenRoot(t)
	require.NoError(t, os.RemoveAll(filepath.Join(root, "protocol", "python")))

	err := syncBundledPythonEvents(root)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "write "+filepath.Join(root, pythonEventsRel))
}

func TestVerifyGenerated_AcceptsCommittedOutputMatchingGeneration(t *testing.T) {
	root := newConstgenRoot(t)
	out := sampleOutputs()
	seedGenerated(t, root, out)

	require.NoError(t, verifyGenerated(root, out))
}

func TestVerifyGenerated_ReportsEachStaleOrMissingTargetInSortedOrder(t *testing.T) {
	root := newConstgenRoot(t)
	out := sampleOutputs()
	seedGenerated(t, root, out)
	writeFile(t, filepath.Join(root, eventsGoRel), "package constants // hand edited\n")
	require.NoError(t, os.Remove(filepath.Join(root, consoleTSRel)))

	err := verifyGenerated(root, out)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "generated constants are stale:")
	assert.Contains(t, err.Error(), filepath.Join(root, eventsGoRel)+": generated output differs from committed file (run make constants)")
	assert.Contains(t, err.Error(), filepath.Join(root, consoleTSRel)+": ")
	assert.NotContains(t, err.Error(), filepath.Join(root, actionTypesGoRel), "an up-to-date file must not be reported")
	assert.Less(t, strings.Index(err.Error(), filepath.Join(root, consoleTSRel)), strings.Index(err.Error(), filepath.Join(root, eventsGoRel)), "diagnostics are sorted")
}

func TestVerifyGenerated_DetectsBundledPythonRegistryDrift(t *testing.T) {
	root := newConstgenRoot(t)
	out := sampleOutputs()
	seedGenerated(t, root, out)
	writeFile(t, filepath.Join(root, pythonEventsRel), `{"events":{}}`)

	err := verifyGenerated(root, out)

	require.Error(t, err)
	assert.Contains(t, err.Error(), "bundled Python events.json differs from protocol/constants/events.json (run make constants)")
}

func TestVerifyBundledPythonEvents_ReportsMissingCanonicalAndMissingBundle(t *testing.T) {
	t.Run("canonical registry missing", func(t *testing.T) {
		err := verifyBundledPythonEvents(t.TempDir())

		require.Error(t, err)
		assert.Contains(t, err.Error(), "read canonical events.json")
	})
	t.Run("bundle missing", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, eventsRel), `{"events":{}}`)

		err := verifyBundledPythonEvents(root)

		require.Error(t, err)
		assert.Contains(t, err.Error(), filepath.Join(root, pythonEventsRel))
	})
}
