// Copyright (c) 2026 Lateralus Labs, LLC.
// Use of this source code is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date listed in the LICENSE file, this software is
// released under the Apache License, Version 2.0.

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type generationOutputs struct {
	EventsGo      string
	ActionTypesGo string
	DashboardJS   string
}

func generateAll(root string, reg registryFile, actionTypes map[string]actionTypeMeta) (generationOutputs, error) {
	hierarchy, err := loadOperatorHierarchy(root)
	if err != nil {
		return generationOutputs{}, err
	}

	eventsGo, err := generateEventsGo(reg, hierarchy, actionTypes)
	if err != nil {
		return generationOutputs{}, err
	}
	actionTypesGo, err := generateActionTypesGo(actionTypes)
	if err != nil {
		return generationOutputs{}, err
	}
	dashboardJS, err := generateDashboardEventsJS(reg)
	if err != nil {
		return generationOutputs{}, err
	}

	return generationOutputs{
		EventsGo:      eventsGo,
		ActionTypesGo: actionTypesGo,
		DashboardJS:   dashboardJS,
	}, nil
}

func writeGenerated(root string, out generationOutputs) error {
	targets := map[string]string{
		filepath.Join(root, "internal/constants/events_gen.go"):        out.EventsGo,
		filepath.Join(root, "internal/constants/action_types_gen.go"):  out.ActionTypesGo,
		filepath.Join(root, "dashboard/public/js/constants/events.js"): out.DashboardJS,
	}
	for path, content := range targets {
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	if err := syncBundledPythonEvents(root); err != nil {
		return err
	}
	return nil
}

func verifyGenerated(root string, out generationOutputs) error {
	targets := map[string]string{
		filepath.Join(root, "internal/constants/events_gen.go"):        out.EventsGo,
		filepath.Join(root, "internal/constants/action_types_gen.go"):  out.ActionTypesGo,
		filepath.Join(root, "dashboard/public/js/constants/events.js"): out.DashboardJS,
	}
	var diffs []string
	for path, expected := range targets {
		actual, err := os.ReadFile(path)
		if err != nil {
			diffs = append(diffs, fmt.Sprintf("%s: %v", path, err))
			continue
		}
		if !bytes.Equal(actual, []byte(expected)) {
			diffs = append(diffs, fmt.Sprintf("%s: generated output differs from committed file (run make constants)", path))
		}
	}
	if err := verifyBundledPythonEvents(root); err != nil {
		diffs = append(diffs, err.Error())
	}
	if len(diffs) > 0 {
		sort.Strings(diffs)
		return fmt.Errorf("generated constants are stale:\n  %s", strings.Join(diffs, "\n  "))
	}
	return nil
}

func bundledPythonEventsPath(root string) string {
	return filepath.Join(root, "protocol/python/g8e/_data/events.json")
}

func syncBundledPythonEvents(root string) error {
	canonical, err := os.ReadFile(filepath.Join(root, "protocol/constants/events.json"))
	if err != nil {
		return fmt.Errorf("read canonical events.json: %w", err)
	}
	path := bundledPythonEventsPath(root)
	if err := os.WriteFile(path, canonical, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func verifyBundledPythonEvents(root string) error {
	canonical, err := os.ReadFile(filepath.Join(root, "protocol/constants/events.json"))
	if err != nil {
		return fmt.Errorf("read canonical events.json: %w", err)
	}
	path := bundledPythonEventsPath(root)
	actual, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("%s: %v", path, err)
	}
	if !bytes.Equal(actual, canonical) {
		return fmt.Errorf("%s: bundled Python events.json differs from protocol/constants/events.json (run make constants)", path)
	}
	return nil
}

func loadOperatorHierarchy(root string) (map[string]string, error) {
	path := filepath.Join(root, "internal/tools/constgen/operator_hierarchy.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read operator_hierarchy.json: %w", err)
	}
	var hierarchy map[string]string
	if err := json.Unmarshal(data, &hierarchy); err != nil {
		return nil, fmt.Errorf("decode operator_hierarchy.json: %w", err)
	}
	return hierarchy, nil
}

func fileHeader(tool string) string {
	return fmt.Sprintf(`// Code generated by %s; DO NOT EDIT.

`, tool)
}
