# Copyright (c) 2026 Lateralus Labs, LLC.
# Use of this source code is governed by the Business Source License
# included in the LICENSE file.
#
# As of the Change Date listed in the LICENSE file, this software is
# released under the Apache License, Version 2.0.

"""
g8ee Constants

Application constants, enums, and configuration values.

Constant modules:
- action_type_mappings.py: deleted — governed action classes resolve through g8e.registry
- agents.py: Agent-related constants
- api_paths.py: API path definitions and routing
- api_paths.json: JSON configuration for API paths
- channels.py: PubSub channel definitions and constants
- collections.py: Database collection names and definitions
- config.py: Application configuration constants (timeouts, models, templates)
- env_vars.py: Environment variable definitions
- errors.py: Error code definitions
- intents.py: Cloud intent definitions and verification logic
- kv_keys.py: Key-value cache key definitions
- message_sender.py: Message sender type definitions
- models.py: Model-related constants
- paths.py: File system path constants
- platform.py: Platform configuration (auth methods, log levels)
- prompts.py: Prompt-related constants
- proto_mappings.py: Protocol buffer mappings
- tool_registry_pending.py: Pending tool registry definitions
"""

from g8e.constants import (
    BOUND_OPERATORS_HEADER as BOUND_OPERATORS,
)
from g8e.constants import (
    CASE_ID_HEADER as CASE_ID,
)
from g8e.constants import (
    CLI_SESSION_ID_HEADER as CLI_SESSION_ID,
)
from g8e.constants import (
    COMPONENT_NAME_HEADER as SOURCE_COMPONENT,
)
from g8e.constants import (
    EXECUTION_ID_HEADER as EXECUTION_ID,
)
from g8e.constants import (
    HTTP_ACCEL_BUFFERING_HEADER as X_ACCEL_BUFFERING,
)
from g8e.constants import (
    HTTP_ACCEPT_HEADER as ACCEPT,
)
from g8e.constants import (
    HTTP_ACCEPT_LANGUAGE_HEADER as ACCEPT_LANGUAGE,
)
from g8e.constants import (
    HTTP_ACCESS_CONTROL_ALLOW_CREDENTIALS_HEADER as ACCESS_CONTROL_ALLOW_CREDENTIALS,
)
from g8e.constants import (
    HTTP_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER as ACCESS_CONTROL_ALLOW_ORIGIN,
)
from g8e.constants import (
    HTTP_ACCESS_CONTROL_REQUEST_HEADERS_HEADER as ACCESS_CONTROL_REQUEST_HEADERS,
)
from g8e.constants import (
    HTTP_ACCESS_CONTROL_REQUEST_METHOD_HEADER as ACCESS_CONTROL_REQUEST_METHOD,
)

# HTTP header constants — sourced from g8e.constants to stay in sync with protocol
from g8e.constants import (
    HTTP_AUTHORIZATION_HEADER as AUTHORIZATION,
)
from g8e.constants import (
    HTTP_CACHE_CONTROL_HEADER as CACHE_CONTROL,
)
from g8e.constants import (
    HTTP_CONTENT_LANGUAGE_HEADER as CONTENT_LANGUAGE,
)
from g8e.constants import (
    HTTP_CONTENT_TYPE_HEADER as CONTENT_TYPE,
)
from g8e.constants import (
    HTTP_COOKIE_HEADER as COOKIE,
)
from g8e.constants import (
    HTTP_G8E_SYSTEM_FINGERPRINT_HEADER as SYSTEM_FINGERPRINT,
)
from g8e.constants import (
    HTTP_LAST_EVENT_ID_HEADER as LAST_EVENT_ID,
)
from g8e.constants import (
    HTTP_PRAGMA_HEADER as PRAGMA,
)
from g8e.constants import (
    HTTP_REQUESTED_WITH_HEADER as REQUESTED_WITH,
)
from g8e.constants import (
    HTTP_SET_COOKIE_HEADER as SET_COOKIE,
)
from g8e.constants import (
    HTTP_USER_AGENT_HEADER as USER_AGENT,
)
from g8e.constants import (
    HTTP_X_FORWARDED_FOR_HEADER as X_FORWARDED_FOR,
)
from g8e.constants import (
    INVESTIGATION_ID_HEADER as INVESTIGATION_ID,
)
from g8e.constants import (
    OPERATOR_ID_HEADER as OPERATOR_ID,
)
from g8e.constants import (
    ORGANIZATION_ID_HEADER as ORGANIZATION_ID,
)
from g8e.constants import (
    PROXY_ISSUED_AT_HEADER as X_PROXY_ISSUED_AT,
)
from g8e.constants import (
    PROXY_KEY_ID_HEADER as X_PROXY_KEY_ID,
)
from g8e.constants import (
    PROXY_NONCE_HEADER as X_PROXY_NONCE,
)
from g8e.constants import (
    PROXY_ORGANIZATION_ID_HEADER as X_PROXY_ORGANIZATION_ID,
)
from g8e.constants import (
    PROXY_SIGNATURE_HEADER as X_PROXY_SIGNATURE,
)
from g8e.constants import (
    PROXY_USER_ID_HEADER as X_PROXY_USER_ID,
)
from g8e.constants import (
    TASK_ID_HEADER as TASK_ID,
)
from g8e.constants import (
    USER_ID_HEADER as USER_ID,
)
from g8e.constants import (
    WEB_SESSION_ID_HEADER as WEB_SESSION_ID,
)
from g8e.constants import ComponentName

from app.constants.agents import PersonaCapability
from app.constants.api_paths import API_PATHS, GatewayAPIPaths, InternalAPIPaths
from app.constants.channels import (
    CHANNEL_SEGMENT_COUNT,
    OperatorChannel,
    PubSubAction,
    PubSubChannel,
    PubSubField,
    PubSubMessageType,
    PubSubWireEventType,
)
from app.constants.collections import (
    DB_COLLECTION_AGENT_ACTIVITY_METADATA,
    DB_COLLECTION_API_KEYS,
    DB_COLLECTION_CASES,
    DB_COLLECTION_CLI_SESSIONS,
    DB_COLLECTION_INVESTIGATIONS,
    DB_COLLECTION_MEMORIES,
    DB_COLLECTION_OPERATOR_SESSIONS,
    DB_COLLECTION_OPERATORS,
    DB_COLLECTION_ORGANIZATIONS,
    DB_COLLECTION_REPUTATION_COMMITMENTS,
    DB_COLLECTION_REPUTATION_STATE,
    DB_COLLECTION_SETTINGS,
    DB_COLLECTION_STAKE_RESOLUTIONS,
    DB_COLLECTION_TASKS,
    DB_COLLECTION_USERS,
    DB_COLLECTION_WEB_SESSIONS,
)
from app.constants.config import (
    AGENT_CONTINUE_APPROVAL_TIMEOUT_SECONDS,
    AGENT_MAX_RETRIES,
    AGENT_MAX_TOOL_TURNS,
    AGENT_RETRY_BACKOFF_MULTIPLIER,
    AGENT_RETRY_DELAY_SECONDS,
    AGENT_RETRYABLE_ERROR_SUBSTRINGS,
    AGENT_RETRYABLE_STATUS_CODES,
    ANTHROPIC_CLAUDE_HAIKU_4_5,
    ANTHROPIC_CLAUDE_OPUS_4_6,
    ANTHROPIC_CLAUDE_SONNET_4_6,
    ANTHROPIC_DEFAULT_ENDPOINT,
    ANTHROPIC_DEFAULT_MODEL,
    APPROVAL_ERROR_TYPE,
    APPROVAL_ID_PREFIX,
    ATTACHED_DOCUMENT_FOOTER_TEMPLATE,
    ATTACHED_DOCUMENT_HEADER_TEMPLATE,
    ATTACHMENT_FILENAMES_PREFIX_TEMPLATE,
    BATCH_OUTPUT_SECTION_SEPARATOR,
    CACHE_TTL_DEFAULT,
    CACHE_TTL_LONG,
    CACHE_TTL_MEDIUM,
    CACHE_TTL_ORGS,
    CACHE_TTL_SHORT,
    COMMAND_RESULT_ERROR_TEMPLATE,
    COMMAND_RESULT_NO_OUTPUT_TEMPLATE,
    COMMAND_RESULT_OUTPUT_TEMPLATE,
    CORS_ALLOWED_ORIGIN_CLIENT_HTTP,
    CORS_ALLOWED_ORIGIN_CLIENT_HTTPS,
    CORS_ALLOWED_ORIGIN_G8EE,
    CORS_ALLOWED_ORIGIN_LOCALHOST,
    DB_TIMESTAMP,
    DEFAULT_FINISH_REASON,
    DEFAULT_HTTP_CLIENT_TIMEOUT,
    DEFAULT_HTTP_TIMEOUT,
    DEFAULT_MAX_RETRIES,
    DEFAULT_OPERATOR_CONFIG,
    DEFAULT_OS_NAME,
    DEFAULT_RETRY_BACKOFF_FACTOR,
    DEFAULT_RETRY_JITTER,
    DEFAULT_SHELL,
    DEFAULT_WORKING_DIRECTORY,
    DOCS_CACHE_TTL_SECONDS,
    DOCS_UNAVAILABLE_CACHE_TEMPLATE,
    DOCS_UNAVAILABLE_TEMPLATE,
    EVALUATION_BACKGROUND_BARRIER_TIMEOUT_SECONDS,
    EVENT_PUBLISH_SUCCESS,
    EXECUTION_ID_PREFIX,
    FETCH_FILE_DIFF_EXECUTION_ID_PREFIX,
    FETCH_FILE_HISTORY_EXECUTION_ID_PREFIX,
    FETCH_HISTORY_EXECUTION_ID_PREFIX,
    FETCH_LOGS_EXECUTION_ID_PREFIX,
    FILE_EDIT_EXECUTION_ID_PREFIX,
    FILE_EDIT_RESULT_TEMPLATE,
    FILE_EDIT_TIMEOUT_TEMPLATE,
    FILE_SECURITY_WARNING_PREFIX_TEMPLATE,
    FILE_TRUNCATION_SUFFIX,
    FORBIDDEN_COMMAND_PATTERNS,
    FS_LIST_EXECUTION_ID_PREFIX,
    FS_READ_EXECUTION_ID_PREFIX,
    FS_READ_MAX_SIZE_BYTES,
    G8EE_APP_CONTACT_EMAIL,
    G8EE_APP_CONTACT_NAME,
    G8EE_APP_CONTACT_URL,
    G8EE_APP_DESCRIPTION,
    G8EE_APP_LICENSE_NAME,
    G8EE_APP_LICENSE_URL,
    G8EE_APP_TITLE,
    G8EE_COMPONENT,
    GEMINI_3_1_FLASH_LITE,
    GEMINI_3_1_PRO,
    GEMINI_3_1_PRO_CUSTOM_TOOLS,
    GEMINI_3_FLASH,
    GEMINI_DEFAULT_ENDPOINT,
    GEMINI_DEFAULT_MODEL,
    HISTORY_OMITTED_MARKER,
    HTTP_METHOD_DELETE,
    HTTP_METHOD_GET,
    HTTP_METHOD_OPTIONS,
    HTTP_METHOD_POST,
    HTTP_METHOD_PUT,
    IAM_EXECUTION_ID_PREFIX,
    IAM_PENDING_EXECUTION_ID_PREFIX,
    IAM_REVOKE_EXECUTION_ID_PREFIX,
    IAM_REVOKE_INTENT_EXECUTION_ID_PREFIX,
    IAM_VERIFY_EXECUTION_ID_PREFIX,
    INFERENCE_DISPATCH_HTTP_TIMEOUT_SECONDS,
    INTENT_APPROVAL_ID_PREFIX,
    INTENT_EXECUTION_ID_PREFIX,
    INVESTIGATION_LOOKUP_MAX_RETRIES,
    INVESTIGATION_LOOKUP_RETRY_DELAYS_MS,
    JEV_DEFAULT_MODEL,
    LLAMACPP_DEFAULT_ENDPOINT,
    LLAMACPP_DEFAULT_MODEL,
    LLAMACPP_GEMMA4_E2B,
    LLM_ESTIMATED_CHARS_PER_TOKEN,
    LLM_OLLAMA_DEFAULT_NUM_CTX,
    LLM_OLLAMA_HISTORY_BUDGET_FRACTION,
    MAX_COMMAND_RESULTS_HISTORY,
    MAX_HEARTBEAT_HISTORY,
    MAX_OUTPUT_LENGTH,
    NONCE_TTL_SECONDS,
    OLLAMA_DEFAULT_ENDPOINT,
    OLLAMA_DEFAULT_MODEL,
    OLLAMA_DEFAULT_PROTOCOL,
    OLLAMA_GEMMA4_12B,
    OLLAMA_GEMMA4_E2B,
    OLLAMA_GEMMA4_E2B_G8EA,
    OLLAMA_GEMMA4_E4B,
    OLLAMA_GRANITE4_2_3B,
    OLLAMA_GRANITE4_2_8B,
    OLLAMA_LLAMA_3_2_3B,
    OLLAMA_QWEN3_1_7B,
    OLLAMA_QWEN3_5_0_8B,
    OLLAMA_QWEN3_5_2B,
    OLLAMA_SYSTEM_ONE_NIMBLE,
    OLLAMA_SYSTEM_ONE_PATH,
    OPENAI_DEFAULT_ENDPOINT,
    OPENAI_DEFAULT_MODEL,
    OPENAI_GPT_3_5_TURBO,
    OPENAI_GPT_4_TURBO,
    OPENAI_GPT_4O,
    OPENAI_GPT_4O_MINI,
    OPENAI_GPT_5_3_INSTANT,
    OPENAI_GPT_5_4,
    OPENAI_GPT_5_4_MINI,
    OPENAI_GPT_5_4_NANO,
    OPENAI_GPT_5_4_PRO,
    OPENAI_QWEN3_8_FLASH_NEXT,
    OPERATOR_AVAILABLE_MESSAGE_TEMPLATE,
    OPERATOR_COMMAND_SHORT_WAIT_TIMEOUT_SECONDS,
    OPERATOR_COMMAND_WAIT_TIMEOUT_SECONDS,
    OPERATOR_UNAVAILABLE_MESSAGE,
    OUTPUT_SECURITY_WARNING_PREFIX,
    OUTPUT_TRUNCATION_SUFFIX,
    PORT_CHECK_EXECUTION_ID_PREFIX,
    RESTORE_FILE_EXECUTION_ID_PREFIX,
    SYSTEM_ONE_MAX_REQUEST_BYTES,
    THINKING_LEVEL_PRIORITY_ASC,
    TIMESTAMP_WINDOW_SECONDS,
    TRIAGE_CONVERSATION_TAIL_LIMIT,
    TRIAGE_EMPTY_CONVERSATION,
    TRIAGE_LOG_TRUNCATION_LENGTH,
    TRIBUNAL_CORRELATION_ID_PREFIX,
    UNKNOWN_ERROR_MESSAGE,
    WEB_SEARCH_CLIENT_MAX_RETRIES,
    WEB_SEARCH_CLIENT_RETRY_BACKOFF,
    WEB_SEARCH_CLIENT_TIMEOUT,
    AnthropicRole,
    AnthropicStopReason,
    APIKeyStatus,
    ApprovalErrorType,
    ApprovalType,
    AttachmentType,
    BatchWriteOpType,
    ChatSessionStatus,
    CircuitBreakerState,
    CommandGenerationOutcome,
    ConversationStatus,
    EntityType,
    ErrorAnalysisCategory,
    EscalationRisk,
    ExecutionStatus,
    FileOperation,
    GeminiRole,
    GroundingSource,
    HealthStatus,
    InfrastructureStatus,
    LLMProvider,
    NetworkProtocol,
    NonceErrorCode,
    ResponseType,
    ScrubType,
    StreamChunkFromModelType,
    SuspiciousPatternType,
    ThinkingDialect,
    ThinkingLevel,
    TimestampErrorCode,
    ToolCallStatus,
    ToolDisplayCategory,
    TriageRole,
)
from app.constants.errors import ErrorCategory, ErrorCode, ErrorSeverity
from app.constants.generated_paths import PathConstants, PortConstants
from app.constants.generated_status import (
    ActionType,
    AISource,
    AITaskId,
    AuditEventSource,
    AuditEventType,
    AuditorReason,
    AuditSseEventType,
    AuthAuditEventType,
    AuthAuditResult,
    AuthProvider,
    CaseStatus,
    CitationLayout,
    CommandCategory,
    CommandErrorType,
    CommandStatus,
    ComponentStatus,
    ConnectionState,
    ConsensusAuditMode,
    ConsensusAuditStatus,
    ConsensusMember,
    DownloadAuditEventType,
    Environment,
    EventType,
    G8eAvailability,
    GatewayMode,
    HeartbeatType,
    HistoryActor,
    InvestigationStatus,
    LLMs,
    LoginAuditEventType,
    OperatorHistoryEventType,
    OperatorStatus,
    OperatorToolName,
    OperatorType,
    Platform,
    Priority,
    ReasoningAgent,
    RiskLevel,
    RiskThreshold,
    SentinelStatus,
    SessionEndReason,
    SessionEventType,
    SessionKeyPrefix,
    SessionSuspiciousReason,
    SessionType,
    Severity,
    SlashTier,
    StreamStatus,
    SystemHealth,
    TaskStatus,
    ThinkingPhase,
    TieBreakReason,
    ToolCallDefaults,
    ToolScope,
    TriageComplexityClassification,
    TriageConfidence,
    TriageIntentClassification,
    TriageRequestPosture,
    UserRole,
    UserStatus,
    VaultMode,
    VersionStability,
    WorkflowType,
)
from app.constants.intents import (
    CLOUD_INTENT_DEPENDENCIES,
    CLOUD_INTENT_QUESTIONS,
    CLOUD_INTENT_VERIFICATION_ACTIONS,
    CloudIntent,
)
from app.constants.kv_keys import (
    CACHE_PREFIX,
    KVKey,
    KVKeyPrefix,
)
from app.constants.message_sender import MessageSender
from app.constants.platform import AuthMethod, LogLevel
from app.constants.prompts import (
    AGENT_MODE_PROMPT_FILES,
    AgentMode,
    InvestigationContextLabel,
    PromptFile,
    PromptSection,
)

# X_PROXY_USER_EMAIL, X_PROXY_CLI_SESSION_ID, and X_PROXY_WEB_SESSION_ID are ensemble-local;
# the g8e protocol package does not define these proxy header constants.
# The ensemble's AuthService reads them from reverse-proxy headers when present.
X_PROXY_USER_EMAIL = "X-Proxy-User-Email"
X_PROXY_CLI_SESSION_ID = "X-Proxy-CLI-Session-Id"
X_PROXY_WEB_SESSION_ID = "X-Proxy-Web-Session-Id"
# Domain tag and clock window of the Gateway's browser-proxy identity stamp. They
# must match internal/constants/browser_proxy.go; the shared vector file in
# protocol/conformance/browser_proxy_stamp_vectors.json fails if they drift.
BROWSER_PROXY_STAMP_DOMAIN = "g8e.browser-proxy-stamp.v1"
BROWSER_PROXY_STAMP_MAX_SKEW_SECONDS = 30

__all__ = [
    "ACCEPT",
    "ACCEPT_LANGUAGE",
    "ACCESS_CONTROL_ALLOW_CREDENTIALS",
    "ACCESS_CONTROL_ALLOW_ORIGIN",
    "ACCESS_CONTROL_REQUEST_HEADERS",
    "ACCESS_CONTROL_REQUEST_METHOD",
    "AGENT_CONTINUE_APPROVAL_TIMEOUT_SECONDS",
    "AGENT_MAX_RETRIES",
    "AGENT_MAX_TOOL_TURNS",
    "AGENT_MODE_PROMPT_FILES",
    "AGENT_RETRYABLE_ERROR_SUBSTRINGS",
    "AGENT_RETRYABLE_STATUS_CODES",
    "AGENT_RETRY_BACKOFF_MULTIPLIER",
    "AGENT_RETRY_DELAY_SECONDS",
    "ANTHROPIC_CLAUDE_HAIKU_4_5",
    "ANTHROPIC_CLAUDE_OPUS_4_6",
    "ANTHROPIC_CLAUDE_SONNET_4_6",
    "ANTHROPIC_DEFAULT_ENDPOINT",
    "ANTHROPIC_DEFAULT_MODEL",
    "API_PATHS",
    "APPROVAL_ERROR_TYPE",
    "APPROVAL_ID_PREFIX",
    "ATTACHED_DOCUMENT_FOOTER_TEMPLATE",
    "ATTACHED_DOCUMENT_HEADER_TEMPLATE",
    "ATTACHMENT_FILENAMES_PREFIX_TEMPLATE",
    "AUTHORIZATION",
    "BATCH_OUTPUT_SECTION_SEPARATOR",
    "BOUND_OPERATORS",
    "BROWSER_PROXY_STAMP_DOMAIN",
    "BROWSER_PROXY_STAMP_MAX_SKEW_SECONDS",
    "CACHE_CONTROL",
    "CACHE_PREFIX",
    "CACHE_TTL_DEFAULT",
    "CACHE_TTL_LONG",
    "CACHE_TTL_MEDIUM",
    "CACHE_TTL_ORGS",
    "CACHE_TTL_SHORT",
    "CASE_ID",
    "CHANNEL_SEGMENT_COUNT",
    "CLI_SESSION_ID",
    "CLOUD_INTENT_DEPENDENCIES",
    "CLOUD_INTENT_QUESTIONS",
    "CLOUD_INTENT_VERIFICATION_ACTIONS",
    "COMMAND_RESULT_ERROR_TEMPLATE",
    "COMMAND_RESULT_NO_OUTPUT_TEMPLATE",
    "COMMAND_RESULT_OUTPUT_TEMPLATE",
    "CONTENT_LANGUAGE",
    "CONTENT_TYPE",
    "COOKIE",
    "CORS_ALLOWED_ORIGIN_CLIENT_HTTP",
    "CORS_ALLOWED_ORIGIN_CLIENT_HTTPS",
    "CORS_ALLOWED_ORIGIN_G8EE",
    "CORS_ALLOWED_ORIGIN_LOCALHOST",
    "DB_COLLECTION_AGENT_ACTIVITY_METADATA",
    "DB_COLLECTION_API_KEYS",
    "DB_COLLECTION_CASES",
    "DB_COLLECTION_INVESTIGATIONS",
    "DB_COLLECTION_MEMORIES",
    "DB_COLLECTION_OPERATORS",
    "DB_COLLECTION_OPERATOR_SESSIONS",
    "DB_COLLECTION_ORGANIZATIONS",
    "DB_COLLECTION_REPUTATION_COMMITMENTS",
    "DB_COLLECTION_REPUTATION_STATE",
    "DB_COLLECTION_SETTINGS",
    "DB_COLLECTION_STAKE_RESOLUTIONS",
    "DB_COLLECTION_TASKS",
    "DB_COLLECTION_USERS",
    "DB_COLLECTION_WEB_SESSIONS",
    "DB_TIMESTAMP",
    "DEFAULT_FINISH_REASON",
    "DEFAULT_HTTP_CLIENT_TIMEOUT",
    "DEFAULT_HTTP_TIMEOUT",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_OPERATOR_CONFIG",
    "DEFAULT_OS_NAME",
    "DEFAULT_RETRY_BACKOFF_FACTOR",
    "DEFAULT_RETRY_JITTER",
    "DEFAULT_SHELL",
    "DEFAULT_WORKING_DIRECTORY",
    "DOCS_CACHE_TTL_SECONDS",
    "DOCS_UNAVAILABLE_CACHE_TEMPLATE",
    "DOCS_UNAVAILABLE_TEMPLATE",
    "EVALUATION_BACKGROUND_BARRIER_TIMEOUT_SECONDS",
    "EVENT_PUBLISH_SUCCESS",
    "EXECUTION_ID",
    "EXECUTION_ID_PREFIX",
    "FETCH_FILE_DIFF_EXECUTION_ID_PREFIX",
    "FETCH_FILE_HISTORY_EXECUTION_ID_PREFIX",
    "FETCH_HISTORY_EXECUTION_ID_PREFIX",
    "FETCH_LOGS_EXECUTION_ID_PREFIX",
    "FILE_EDIT_EXECUTION_ID_PREFIX",
    "FILE_EDIT_RESULT_TEMPLATE",
    "FILE_EDIT_TIMEOUT_TEMPLATE",
    "FILE_SECURITY_WARNING_PREFIX_TEMPLATE",
    "FILE_TRUNCATION_SUFFIX",
    "FORBIDDEN_COMMAND_PATTERNS",
    "FS_LIST_EXECUTION_ID_PREFIX",
    "FS_READ_EXECUTION_ID_PREFIX",
    "FS_READ_MAX_SIZE_BYTES",
    "G8EE_APP_CONTACT_EMAIL",
    "G8EE_APP_CONTACT_NAME",
    "G8EE_APP_CONTACT_URL",
    "G8EE_APP_DESCRIPTION",
    "G8EE_APP_LICENSE_NAME",
    "G8EE_APP_LICENSE_URL",
    "G8EE_APP_TITLE",
    "G8EE_COMPONENT",
    "GEMINI_3_1_FLASH_LITE",
    "GEMINI_3_1_PRO",
    "GEMINI_3_1_PRO_CUSTOM_TOOLS",
    "GEMINI_3_FLASH",
    "GEMINI_DEFAULT_ENDPOINT",
    "GEMINI_DEFAULT_MODEL",
    "HISTORY_OMITTED_MARKER",
    "IAM_EXECUTION_ID_PREFIX",
    "IAM_PENDING_EXECUTION_ID_PREFIX",
    "IAM_REVOKE_EXECUTION_ID_PREFIX",
    "IAM_REVOKE_INTENT_EXECUTION_ID_PREFIX",
    "IAM_VERIFY_EXECUTION_ID_PREFIX",
    "INFERENCE_DISPATCH_HTTP_TIMEOUT_SECONDS",
    "INTENT_APPROVAL_ID_PREFIX",
    "INTENT_EXECUTION_ID_PREFIX",
    "INVESTIGATION_ID",
    "INVESTIGATION_LOOKUP_MAX_RETRIES",
    "INVESTIGATION_LOOKUP_RETRY_DELAYS_MS",
    "JEV_DEFAULT_MODEL",
    "LAST_EVENT_ID",
    "LLAMACPP_DEFAULT_ENDPOINT",
    "LLAMACPP_DEFAULT_MODEL",
    "LLAMACPP_GEMMA4_E2B",
    "LLM_ESTIMATED_CHARS_PER_TOKEN",
    "LLM_OLLAMA_DEFAULT_NUM_CTX",
    "LLM_OLLAMA_HISTORY_BUDGET_FRACTION",
    "MAX_COMMAND_RESULTS_HISTORY",
    "MAX_HEARTBEAT_HISTORY",
    "MAX_OUTPUT_LENGTH",
    "NONCE_TTL_SECONDS",
    "OLLAMA_DEFAULT_ENDPOINT",
    "OLLAMA_DEFAULT_MODEL",
    "OLLAMA_DEFAULT_PROTOCOL",
    "OLLAMA_GEMMA4_12B",
    "OLLAMA_GEMMA4_E2B",
    "OLLAMA_GEMMA4_E2B_G8EA",
    "OLLAMA_GEMMA4_E4B",
    "OLLAMA_GRANITE4_2_3B",
    "OLLAMA_GRANITE4_2_8B",
    "OLLAMA_LLAMA_3_2_3B",
    "OLLAMA_QWEN3_1_7B",
    "OLLAMA_QWEN3_5_0_8B",
    "OLLAMA_QWEN3_5_2B",
    "OLLAMA_SYSTEM_ONE_NIMBLE",
    "OLLAMA_SYSTEM_ONE_PATH",
    "OPENAI_DEFAULT_ENDPOINT",
    "OPENAI_DEFAULT_MODEL",
    "OPENAI_GPT_3_5_TURBO",
    "OPENAI_GPT_4O",
    "OPENAI_GPT_4O_MINI",
    "OPENAI_GPT_4_TURBO",
    "OPENAI_GPT_5_3_INSTANT",
    "OPENAI_GPT_5_4",
    "OPENAI_GPT_5_4_MINI",
    "OPENAI_GPT_5_4_NANO",
    "OPENAI_GPT_5_4_PRO",
    "OPENAI_QWEN3_8_FLASH_NEXT",
    "OPERATOR_AVAILABLE_MESSAGE_TEMPLATE",
    "OPERATOR_COMMAND_SHORT_WAIT_TIMEOUT_SECONDS",
    "OPERATOR_COMMAND_WAIT_TIMEOUT_SECONDS",
    "OPERATOR_ID",
    "OPERATOR_UNAVAILABLE_MESSAGE",
    "ORGANIZATION_ID",
    "OUTPUT_SECURITY_WARNING_PREFIX",
    "OUTPUT_TRUNCATION_SUFFIX",
    "PORT_CHECK_EXECUTION_ID_PREFIX",
    "PRAGMA",
    "REQUESTED_WITH",
    "RESTORE_FILE_EXECUTION_ID_PREFIX",
    "SET_COOKIE",
    "SOURCE_COMPONENT",
    "SYSTEM_FINGERPRINT",
    "SYSTEM_ONE_MAX_REQUEST_BYTES",
    "TASK_ID",
    "THINKING_LEVEL_PRIORITY_ASC",
    "TIMESTAMP_WINDOW_SECONDS",
    "TRIAGE_CONVERSATION_TAIL_LIMIT",
    "TRIAGE_EMPTY_CONVERSATION",
    "TRIAGE_LOG_TRUNCATION_LENGTH",
    "TRIBUNAL_CORRELATION_ID_PREFIX",
    "TRUNCATED_LINES_MARKER_TEMPLATE",
    "UNKNOWN_ERROR_MESSAGE",
    "USER_AGENT",
    "USER_ID",
    "WEB_SEARCH_CLIENT_MAX_RETRIES",
    "WEB_SEARCH_CLIENT_RETRY_BACKOFF",
    "WEB_SEARCH_CLIENT_TIMEOUT",
    "WEB_SESSION_ID",
    "X_ACCEL_BUFFERING",
    "X_FORWARDED_FOR",
    "X_PROXY_CLI_SESSION_ID",
    "X_PROXY_ISSUED_AT",
    "X_PROXY_KEY_ID",
    "X_PROXY_NONCE",
    "X_PROXY_ORGANIZATION_ID",
    "X_PROXY_SIGNATURE",
    "X_PROXY_USER_EMAIL",
    "X_PROXY_USER_ID",
    "X_PROXY_WEB_SESSION_ID",
    "AISource",
    "AITaskId",
    "APIKeyStatus",
    "ActionType",
    "AgentMode",
    "AnthropicRole",
    "AnthropicStopReason",
    "ApprovalErrorType",
    "ApprovalType",
    "AttachmentType",
    "AuditEventSource",
    "AuditEventType",
    "AuditSseEventType",
    "AuditorReason",
    "AuthAuditEventType",
    "AuthAuditResult",
    "AuthMethod",
    "AuthProvider",
    "BatchWriteOpType",
    "CaseStatus",
    "ChatSessionStatus",
    "CircuitBreakerState",
    "CitationLayout",
    "CloudIntent",
    "CommandCategory",
    "CommandErrorType",
    "CommandGenerationOutcome",
    "CommandStatus",
    "ComponentName",
    "ComponentStatus",
    "ConnectionState",
    "ConsensusMember",
    "ConversationStatus",
    "DownloadAuditEventType",
    "EntityType",
    "Environment",
    "ErrorAnalysisCategory",
    "ErrorCategory",
    "ErrorCode",
    "ErrorSeverity",
    "EscalationRisk",
    "EventType",
    "ExecutionStatus",
    "FileOperation",
    "G8eAvailability",
    "GatewayAPIPaths",
    "GatewayMode",
    "GeminiRole",
    "GroundingSource",
    "HealthStatus",
    "HeartbeatType",
    "HistoryActor",
    "InfrastructureStatus",
    "InternalAPIPaths",
    "InvestigationContextLabel",
    "InvestigationStatus",
    "KVKey",
    "KVKeyPrefix",
    "LLMProvider",
    "LLMs",
    "LogLevel",
    "LoginAuditEventType",
    "MessageSender",
    "NetworkProtocol",
    "NonceErrorCode",
    "OperatorChannel",
    "OperatorHistoryEventType",
    "OperatorStatus",
    "OperatorToolName",
    "OperatorType",
    "PathConstants",
    "PersonaCapability",
    "Platform",
    "PortConstants",
    "Priority",
    "PromptFile",
    "PromptSection",
    "PubSubAction",
    "PubSubChannel",
    "PubSubField",
    "PubSubMessageType",
    "PubSubWireEventType",
    "ReasoningAgent",
    "ResponseType",
    "RiskLevel",
    "RiskThreshold",
    "ScrubType",
    "SentinelStatus",
    "SessionEndReason",
    "SessionEventType",
    "SessionKeyPrefix",
    "SessionSuspiciousReason",
    "SessionType",
    "Severity",
    "SlashTier",
    "StreamChunkFromModelType",
    "StreamStatus",
    "SuspiciousPatternType",
    "SystemHealth",
    "TaskStatus",
    "ThinkingDialect",
    "ThinkingLevel",
    "ThinkingPhase",
    "TieBreakReason",
    "TimestampErrorCode",
    "ToolCallDefaults",
    "ToolCallStatus",
    "ToolDisplayCategory",
    "ToolScope",
    "TriageComplexityClassification",
    "TriageConfidence",
    "TriageIntentClassification",
    "TriageRequestPosture",
    "TriageRole",
    "UserRole",
    "UserStatus",
    "VaultMode",
    "VersionStability",
    "WorkflowType",
]
