# Copyright (c) 2026 Lateralus Labs, LLC.
# Use of this source code is governed by the Business Source License
# included in the LICENSE file.
#
# As of the Change Date listed in the LICENSE file, this software is
# released under the Apache License, Version 2.0.

"""
g8ee Models

Pydantic models and data structures for the application.

Model categories:
- agent.py: Agent execution and streaming models
- agents/: Agent-specific models (triage, primary, auditor, case title)
- attachments.py: File attachment models
- base.py: Base model classes (auditable, identifiable, timestamped)
- cache.py: Cache operation models
- cases.py: Case management models
- command_request_payloads.py: Command request payloads
- conversation.py: Conversation models
- db_queries.py: Database query models
- errors.py: Error models
- events.py: Event models
- grounding.py: Grounding and citation models
- health.py: Health check models
- http_context.py: HTTP context models
- infra.py: Infrastructure models
- internal_api.py: Internal API request/response models
- investigations.py: Investigation models
- memory.py: Memory analysis models
- model_configs.py: LLM model configuration
- operators.py: Operator-related models
- operators_bind.py: Operator binding models
- personas/: Persona models
- pubsub_messages.py: PubSub message models
- reputation.py: Reputation models
- sessions.py: Session models
- settings.py: Settings models
- ssh_inventory.py: SSH inventory models
- state.py: State models
- tool_args.py: Tool argument models
- tool_results.py: Tool result models
- triage_api.py: Triage API models
- tribunal_commands.py: Tribunal command models
- uap.py: (removed) envelope construction now uses g8e.models.governance directly
- version.py: Version information
- whitelist.py: Whitelist models
"""

from app.constants import (
    AGENT_MODE_PROMPT_FILES,
    AgentMode,
    ApprovalType,
    AttachmentType,
    AuthMethod,
    BatchWriteOpType,
    CloudIntent,
    ConversationStatus,
    EscalationRisk,
    ExecutionStatus,
    FileOperation,
    GroundingSource,
    HealthStatus,
    HeartbeatType,
    InfrastructureStatus,
    NetworkProtocol,
    OperatorStatus,
    OperatorToolName,
    OperatorType,
    Platform,
    Priority,
    PromptFile,
    PromptSection,
    ResponseType,
    RiskLevel,
    RiskThreshold,
    TaskStatus,
    ThinkingLevel,
    ToolCallStatus,
    ToolDisplayCategory,
    VersionStability,
)
from app.models.version import VersionInfo

from .agent import (
    AgentInputs,
    AgentStreamState,
    ExecutorCommandArgs,
    OperatorContext,
    SageOperatorRequest,
    StreamChunkData,
    StreamChunkFromModel,
)
from .agents import (
    AuditorRequest,
    AuditorResult,
    CandidateCommand,
    CaseTitleRequest,
    CaseTitleResult,
    CommandGenerationResult,
    PrimaryRequest,
    PrimaryResult,
    TriageResult,
)
from .attachments import (
    AttachmentData,
    AttachmentMetadata,
    ProcessedAttachment,
)
from .base import G8eAuditableModel, G8eBaseModel, G8eIdentifiableModel, G8eTimestampedModel
from .cache import (
    BatchOperationResult,
    BatchWriteOperation,
    CacheContextWarmResult,
    CacheOperationResult,
    CacheWarmResult,
    DocumentResult,
    FieldFilter,
    QueryOrderBy,
    QueryResult,
)
from .cases import CaseCreateRequest, CaseEventPayload, CaseModel, CaseUpdateRequest, HistoryEntry
from .command_request_payloads import (
    CommandCancelRequestPayload,
    CommandRequestPayload,
    FetchFileDiffRequestPayload,
    FetchFileHistoryRequestPayload,
    FetchHistoryRequestPayload,
    FetchLogsRequestPayload,
    FileEditRequestPayload,
    FsListRequestPayload,
    FsReadRequestPayload,
    RestoreFileRequestPayload,
)
from .conversation import (
    Conversation,
)
from .grounding import (
    GroundingChunk,
    GroundingMetadata,
    GroundingSegment,
    GroundingSourceInfo,
    GroundingSupport,
    SearchEntryPoint,
)
from .health import (
    DependencyStatus,
    HealthCheckResult,
    ServiceHealthResult,
    WorkflowHealthResult,
)
from .http_context import (
    BoundOperator,
    G8eHttpContext,
    RequestContext,
)
from .internal_api import (
    APIKeyGenerationRequest,
    APIKeyGenerationResponse,
    ApprovalRespondedResponse,
    CaseResponse,
    ChatMessageRequest,
    ChatStartedResponse,
    DirectCommandRequest,
    DirectCommandSentResponse,
    GrantIntentResponse,
    IntentOperationResult,
    IntentRequestPayload,
    InternalOperatorAuthCall,
    OperatorApprovalResponse,
    OperatorAuthenticateResponse,
    OperatorBindRequest,
    OperatorBindResponse,
    OperatorCertificateRevokeRequest,
    OperatorCertificateRevokeResponse,
    OperatorDeviceLinkRegisterRequest,
    OperatorDeviceLinkRegisterResponse,
    OperatorLinkRequestPayload,
    OperatorLinkResponse,
    OperatorListenSessionAuthRequest,
    OperatorSessionRefreshRequest,
    OperatorSessionRefreshResponse,
    OperatorSessionValidateRequest,
    OperatorSessionValidateResponse,
    OperatorSlotClaimRequest,
    OperatorSlotClaimResponse,
    OperatorSlotCreationRequest,
    OperatorSlotCreationResponse,
    OperatorStoppedResponse,
    OperatorTerminateRequest,
    OperatorTerminateResponse,
    OperatorUnbindRequest,
    OperatorUnbindResponse,
    OperatorUpdateAPIKeyRequest,
    OperatorUpdateAPIKeyResponse,
    PendingApprovalsResponse,
    ResourceCreationRequest,
    RevokeIntentResponse,
    SettingsGetRequest,
    SSEPushResponse,
    StopAIRequest,
    StopAIResponse,
    StopOperatorRequest,
)
from .investigations import (
    AIResponseMetadata,
    ApprovalMetadata,
    Attachment,
    ConversationHistoryMessage,
    ConversationMessageMetadata,
    ConversationUpdateOperation,
    EnrichedInvestigationContext,
    FileEditMetadata,
    InvestigationCreateRequest,
    InvestigationCurrentState,
    InvestigationCustomerContext,
    InvestigationExecutionConstraints,
    InvestigationHistoryEntry,
    InvestigationModel,
    InvestigationQueryRequest,
    InvestigationTechnicalContext,
    InvestigationUpdateRequest,
    OperatorCommandMetadata,
    ThinkingMessage,
    UserChatMetadata,
)
from .memory import InvestigationMemory, MemoryAnalysis
from .model_configs import (
    GEMINI_3_1_PRO,
    GEMINI_3_FLASH,
    MODEL_REGISTRY,
    LLModelConfig,
    LLModelRegistry,
    get_available_models,
    get_model_config,
)
from .operators import (
    AgentContinueApprovalRequest,
    ApprovalContext,
    ApprovalRequestBase,
    ApprovalResult,
    AttachmentRecord,
    BatchCommandBroadcastEvent,
    BatchOperatorExecutionResult,
    BindingValidationResult,
    CancelCommandResult,
    CommandApprovalRequest,
    DirectCommandResult,
    FileEditApprovalRequest,
    HeartbeatDiskDetails,
    HeartbeatEnvironment,
    HeartbeatFingerprintDetails,
    HeartbeatMemoryDetails,
    HeartbeatOSDetails,
    HeartbeatSnapshot,
    HeartbeatUserDetails,
    IntentApprovalEvent,
    IntentApprovalRequest,
    OperatorDocument,
    PendingApproval,
    TargetSystem,
)
from .operators_bind import (
    BindOperatorsRequest,
    BindOperatorsResponse,
    UnbindOperatorsRequest,
    UnbindOperatorsResponse,
)
from .pubsub_messages import (
    CancellationResultPayload,
    ExecutionResultsPayload,
    ExecutionStatusPayload,
    FetchFileDiffByIdSuccessPayload,
    FetchFileDiffBySessionSuccessPayload,
    FetchFileDiffErrorPayload,
    FetchFileHistoryErrorPayload,
    FetchFileHistorySuccessPayload,
    FetchHistoryErrorPayload,
    FetchHistorySuccessPayload,
    FetchLogsErrorPayload,
    FetchLogsResultPayload,
    FileEditResultPayload,
    FsListResultPayload,
    FsReadResultPayload,
    G8eMessage,
    G8eoResultEnvelope,
    G8eoResultPayload,
    PortCheckResultPayload,
    RestoreFileErrorPayload,
    RestoreFileSuccessPayload,
)
from .tool_results import (
    AuditEvent,
    AuditFileMutation,
    AuditSessionMetadata,
    CommandExecutionResult,
    CommandRiskAnalysis,
    CommandRiskContext,
    ErrorAnalysisContext,
    ErrorAnalysisResult,
    FailedIntentResult,
    FetchFileDiffToolResult,
    FetchFileHistoryToolResult,
    FetchHistoryToolResult,
    FetchLogsToolResult,
    FileDiffEntry,
    FileEditResult,
    FileHistoryEntry,
    FileOperationRiskAnalysis,
    FileOperationRiskContext,
    FsListEntry,
    FsListToolResult,
    FsReadToolResult,
    IamIntentResult,
    IntentPermissionResult,
    PortCheckToolResult,
    RestoreFileToolResult,
    SearchWebResult,
    TokenUsage,
    ToolResult,
)
from .tribunal_commands import TribunalGenerationRequest

__all__ = [
    "AGENT_MODE_PROMPT_FILES",
    "GEMINI_3_1_PRO",
    "GEMINI_3_FLASH",
    "MODEL_REGISTRY",
    "APIKeyGenerationRequest",
    "APIKeyGenerationResponse",
    "AgentContinueApprovalRequest",
    "AgentInputs",
    "AgentMode",
    "AgentStreamState",
    "ApprovalContext",
    "ApprovalMetadata",
    "ApprovalRequestBase",
    "ApprovalRespondedResponse",
    "ApprovalResult",
    "ApprovalType",
    "Attachment",
    "AttachmentData",
    "AttachmentMetadata",
    "AttachmentRecord",
    "AttachmentType",
    "AuditEvent",
    "AuditFileMutation",
    "AuditSessionMetadata",
    "AuditorRequest",
    "AuditorResult",
    "AuthMethod",
    "AuthenticatedUser",
    "BatchCommandBroadcastEvent",
    "BatchOperationResult",
    "BatchOperatorExecutionResult",
    "BatchWriteOpType",
    "BatchWriteOperation",
    "BindOperatorsRequest",
    "BindOperatorsResponse",
    "BindingValidationResult",
    "BoundOperator",
    "CacheContextWarmResult",
    "CacheOperationResult",
    "CacheWarmResult",
    "CancelCommandResult",
    "CancellationResultPayload",
    "CandidateCommand",
    "CaseCreateRequest",
    "CaseEventPayload",
    "CaseModel",
    "CaseResponse",
    "CaseTitleRequest",
    "CaseTitleResult",
    "CaseUpdateRequest",
    "ChatMessageRequest",
    "ChatStartedResponse",
    "CloudIntent",
    "CommandApprovalRequest",
    "CommandCancelRequestPayload",
    "CommandExecutionResult",
    "CommandGenerationResult",
    "CommandRequestPayload",
    "CommandRiskAnalysis",
    "CommandRiskContext",
    "Conversation",
    "ConversationHistoryMessage",
    "ConversationMessageMetadata",
    "ConversationStatus",
    "ConversationUpdateOperation",
    "DependencyStatus",
    "DirectCommandRequest",
    "DirectCommandResult",
    "DirectCommandSentResponse",
    "DocumentResult",
    "EnrichedInvestigationContext",
    "ErrorAnalysisContext",
    "ErrorAnalysisResult",
    "EscalationRisk",
    "ExecutionResultsPayload",
    "ExecutionStatus",
    "ExecutionStatusPayload",
    "ExecutorCommandArgs",
    "FailedIntentResult",
    "FetchFileDiffByIdSuccessPayload",
    "FetchFileDiffBySessionSuccessPayload",
    "FetchFileDiffErrorPayload",
    "FetchFileDiffRequestPayload",
    "FetchFileDiffToolResult",
    "FetchFileHistoryErrorPayload",
    "FetchFileHistoryRequestPayload",
    "FetchFileHistorySuccessPayload",
    "FetchFileHistoryToolResult",
    "FetchHistoryErrorPayload",
    "FetchHistoryRequestPayload",
    "FetchHistorySuccessPayload",
    "FetchHistoryToolResult",
    "FetchLogsErrorPayload",
    "FetchLogsRequestPayload",
    "FetchLogsResultPayload",
    "FetchLogsToolResult",
    "FieldFilter",
    "FileDiffEntry",
    "FileEditApprovalRequest",
    "FileEditMetadata",
    "FileEditRequestPayload",
    "FileEditResult",
    "FileEditResultPayload",
    "FileHistoryEntry",
    "FileOperation",
    "FileOperationRiskAnalysis",
    "FileOperationRiskContext",
    "FsListEntry",
    "FsListRequestPayload",
    "FsListResultPayload",
    "FsListToolResult",
    "FsReadRequestPayload",
    "FsReadResultPayload",
    "FsReadToolResult",
    "G8eAuditableModel",
    "G8eBaseModel",
    "G8eHttpContext",
    "G8eIdentifiableModel",
    "G8eMessage",
    "G8eTimestampedModel",
    "G8eoResultEnvelope",
    "G8eoResultPayload",
    "GrantIntentResponse",
    "GroundingChunk",
    "GroundingMetadata",
    "GroundingSegment",
    "GroundingSource",
    "GroundingSourceInfo",
    "GroundingSupport",
    "HealthCheckResult",
    "HealthStatus",
    "HeartbeatType",
    "HistoryEntry",
    "IamIntentResult",
    "InfrastructureStatus",
    "IntentApprovalEvent",
    "IntentApprovalRequest",
    "IntentOperationResult",
    "IntentPermissionResult",
    "IntentRequestPayload",
    "InternalOperatorAuthCall",
    "InvestigationCreateRequest",
    "InvestigationCurrentState",
    "InvestigationCustomerContext",
    "InvestigationExecutionConstraints",
    "InvestigationHistoryEntry",
    "InvestigationMemory",
    "InvestigationModel",
    "InvestigationQueryRequest",
    "InvestigationTechnicalContext",
    "InvestigationUpdateRequest",
    "LLModelConfig",
    "LLModelRegistry",
    "MemoryAnalysis",
    "NetworkProtocol",
    "OperatorApprovalResponse",
    "OperatorAuthenticateResponse",
    "OperatorBindRequest",
    "OperatorBindResponse",
    "OperatorCertificateRevokeRequest",
    "OperatorCertificateRevokeResponse",
    "OperatorCommandMetadata",
    "OperatorContext",
    "OperatorDeviceLinkRegisterRequest",
    "OperatorDeviceLinkRegisterResponse",
    "OperatorDocument",
    "OperatorLinkRequestPayload",
    "OperatorLinkResponse",
    "OperatorListenSessionAuthRequest",
    "OperatorSessionRefreshRequest",
    "OperatorSessionRefreshResponse",
    "OperatorSessionValidateRequest",
    "OperatorSessionValidateResponse",
    "OperatorSlotClaimRequest",
    "OperatorSlotClaimResponse",
    "OperatorSlotCreationRequest",
    "OperatorSlotCreationResponse",
    "OperatorStatus",
    "OperatorStoppedResponse",
    "OperatorTerminateRequest",
    "OperatorTerminateResponse",
    "OperatorToolName",
    "OperatorType",
    "OperatorUnbindRequest",
    "OperatorUnbindResponse",
    "OperatorUpdateAPIKeyRequest",
    "OperatorUpdateAPIKeyResponse",
    "PendingApproval",
    "PendingApprovalsResponse",
    "Platform",
    "PortCheckResultPayload",
    "PortCheckToolResult",
    "PrimaryRequest",
    "PrimaryResult",
    "Priority",
    "ProcessedAttachment",
    "PromptFile",
    "PromptSection",
    "QueryOrderBy",
    "QueryResult",
    "RequestContext",
    "ResourceCreationRequest",
    "ResponseType",
    "RestoreFileErrorPayload",
    "RestoreFileRequestPayload",
    "RestoreFileSuccessPayload",
    "RestoreFileToolResult",
    "RevokeIntentResponse",
    "RiskLevel",
    "RiskThreshold",
    "SSEPushResponse",
    "SageOperatorRequest",
    "SearchEntryPoint",
    "SearchWebResult",
    "ServiceHealthResult",
    "SettingsGetRequest",
    "StopAIRequest",
    "StopAIResponse",
    "StopOperatorRequest",
    "StreamChunkData",
    "StreamChunkFromModel",
    "TargetSystem",
    "TaskStatus",
    "ThinkingLevel",
    "ThinkingMessage",
    "TokenUsage",
    "ToolCallStatus",
    "ToolDisplayCategory",
    "ToolResult",
    "TriageResult",
    "UnbindOperatorsRequest",
    "UnbindOperatorsResponse",
    "UserChatMetadata",
    "VersionInfo",
    "VersionStability",
    "WorkflowHealthResult",
    "get_available_models",
    "get_model_config",
]

ApprovalRequestBase.model_rebuild()
CommandApprovalRequest.model_rebuild()
FileEditApprovalRequest.model_rebuild()
IntentApprovalRequest.model_rebuild()
AgentContinueApprovalRequest.model_rebuild()
