// Copyright (c) 2026 Lateralus Labs, LLC.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: g8e/common/v1/common.proto

package commonv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Source component identifier
type Component int32

const (
	Component_COMPONENT_UNSPECIFIED Component = 0
	Component_COMPONENT_G8EE        Component = 1
	Component_COMPONENT_G8EO        Component = 2
	Component_COMPONENT_CLIENT      Component = 3
)

// Enum value maps for Component.
var (
	Component_name = map[int32]string{
		0: "COMPONENT_UNSPECIFIED",
		1: "COMPONENT_G8EE",
		2: "COMPONENT_G8EO",
		3: "COMPONENT_CLIENT",
	}
	Component_value = map[string]int32{
		"COMPONENT_UNSPECIFIED": 0,
		"COMPONENT_G8EE":        1,
		"COMPONENT_G8EO":        2,
		"COMPONENT_CLIENT":      3,
	}
)

func (x Component) Enum() *Component {
	p := new(Component)
	*p = x
	return p
}

func (x Component) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Component) Descriptor() protoreflect.EnumDescriptor {
	return file_g8e_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (Component) Type() protoreflect.EnumType {
	return &file_g8e_common_v1_common_proto_enumTypes[0]
}

func (x Component) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Component.Descriptor instead.
func (Component) EnumDescriptor() ([]byte, []int) {
	return file_g8e_common_v1_common_proto_rawDescGZIP(), []int{0}
}

// Doctrine (L1Doctrine) Governance: Technical Bedrock (Hard Gates)
type L1Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validated     bool                   `protobuf:"varint,1,opt,name=validated,proto3" json:"validated,omitempty"`
	Violations    []string               `protobuf:"bytes,2,rep,name=violations,proto3" json:"violations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L1Metadata) Reset() {
	*x = L1Metadata{}
	mi := &file_g8e_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L1Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L1Metadata) ProtoMessage() {}

func (x *L1Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_g8e_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L1Metadata.ProtoReflect.Descriptor instead.
func (*L1Metadata) Descriptor() ([]byte, []int) {
	return file_g8e_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *L1Metadata) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

func (x *L1Metadata) GetViolations() []string {
	if x != nil {
		return x.Violations
	}
	return nil
}

// Consensus (L2Consensus) Governance: Consensus (Tribunal)
type L2Metadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TribunalSignature string                 `protobuf:"bytes,1,opt,name=tribunal_signature,json=tribunalSignature,proto3" json:"tribunal_signature,omitempty"` // ED25519 signature over transaction_hash|decision
	AgentIds          []string               `protobuf:"bytes,2,rep,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"`                            // IDs of agents that voted
	KeyId             string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`                                     // ID of the key used for signature
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *L2Metadata) Reset() {
	*x = L2Metadata{}
	mi := &file_g8e_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2Metadata) ProtoMessage() {}

func (x *L2Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_g8e_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2Metadata.ProtoReflect.Descriptor instead.
func (*L2Metadata) Descriptor() ([]byte, []int) {
	return file_g8e_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *L2Metadata) GetTribunalSignature() string {
	if x != nil {
		return x.TribunalSignature
	}
	return ""
}

func (x *L2Metadata) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

func (x *L2Metadata) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// Notary (L3Notary) Governance: Authorization (Human-in-the-loop)
type L3Proof struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClientDataJson    string                 `protobuf:"bytes,1,opt,name=client_data_json,json=clientDataJSON,proto3" json:"client_data_json,omitempty"`
	AuthenticatorData string                 `protobuf:"bytes,2,opt,name=authenticator_data,json=authenticatorData,proto3" json:"authenticator_data,omitempty"`
	Signature         string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	CredentialId      string                 `protobuf:"bytes,4,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	// CLI mTLS proof: fingerprint of the CLI certificate used for authentication
	// Used when the L3Notary proof is based on mTLS certificate validation rather than WebAuthn
	MtlsCertFingerprint string `protobuf:"bytes,5,opt,name=mtls_cert_fingerprint,json=mtlsCertFingerprint,proto3" json:"mtls_cert_fingerprint,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *L3Proof) Reset() {
	*x = L3Proof{}
	mi := &file_g8e_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L3Proof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L3Proof) ProtoMessage() {}

func (x *L3Proof) ProtoReflect() protoreflect.Message {
	mi := &file_g8e_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L3Proof.ProtoReflect.Descriptor instead.
func (*L3Proof) Descriptor() ([]byte, []int) {
	return file_g8e_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *L3Proof) GetClientDataJson() string {
	if x != nil {
		return x.ClientDataJson
	}
	return ""
}

func (x *L3Proof) GetAuthenticatorData() string {
	if x != nil {
		return x.AuthenticatorData
	}
	return ""
}

func (x *L3Proof) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *L3Proof) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *L3Proof) GetMtlsCertFingerprint() string {
	if x != nil {
		return x.MtlsCertFingerprint
	}
	return ""
}

type L3Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proof         *L3Proof               `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`                                    // Real WebAuthn proof
	AutoApproved  bool                   `protobuf:"varint,2,opt,name=auto_approved,json=autoApproved,proto3" json:"auto_approved,omitempty"` // True if skipped via auto-approval policy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L3Metadata) Reset() {
	*x = L3Metadata{}
	mi := &file_g8e_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L3Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L3Metadata) ProtoMessage() {}

func (x *L3Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_g8e_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L3Metadata.ProtoReflect.Descriptor instead.
func (*L3Metadata) Descriptor() ([]byte, []int) {
	return file_g8e_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *L3Metadata) GetProof() *L3Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *L3Metadata) GetAutoApproved() bool {
	if x != nil {
		return x.AutoApproved
	}
	return false
}

// Unified Governance Metadata
type GovernanceMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	L1    *L1Metadata            `protobuf:"bytes,1,opt,name=l1,proto3" json:"l1,omitempty"`
	L2    *L2Metadata            `protobuf:"bytes,2,opt,name=l2,proto3" json:"l2,omitempty"`
	L3    *L3Metadata            `protobuf:"bytes,3,opt,name=l3,proto3" json:"l3,omitempty"`
	// Set to true if signed by the local gateway without full Tribunal consensus.
	// This is used for single-agent MCP clients that bypass the L2 consensus layer.
	GatewaySigned bool `protobuf:"varint,4,opt,name=gateway_signed,json=gatewaySigned,proto3" json:"gateway_signed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GovernanceMetadata) Reset() {
	*x = GovernanceMetadata{}
	mi := &file_g8e_common_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernanceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernanceMetadata) ProtoMessage() {}

func (x *GovernanceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_g8e_common_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernanceMetadata.ProtoReflect.Descriptor instead.
func (*GovernanceMetadata) Descriptor() ([]byte, []int) {
	return file_g8e_common_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *GovernanceMetadata) GetL1() *L1Metadata {
	if x != nil {
		return x.L1
	}
	return nil
}

func (x *GovernanceMetadata) GetL2() *L2Metadata {
	if x != nil {
		return x.L2
	}
	return nil
}

func (x *GovernanceMetadata) GetL3() *L3Metadata {
	if x != nil {
		return x.L3
	}
	return nil
}

func (x *GovernanceMetadata) GetGatewaySigned() bool {
	if x != nil {
		return x.GatewaySigned
	}
	return false
}

// GovernanceEnvelope is the single canonical container for all g8e mutations.
// It binds identity, intent, state, and governance proofs into one transaction.
type GovernanceEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity & Metadata
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExpiresAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SourceComponent   Component              `protobuf:"varint,4,opt,name=source_component,json=sourceComponent,proto3,enum=g8e.common.v1.Component" json:"source_component,omitempty"`
	OperatorId        string                 `protobuf:"bytes,5,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	OperatorSessionId string                 `protobuf:"bytes,6,opt,name=operator_session_id,json=operatorSessionId,proto3" json:"operator_session_id,omitempty"`
	WebSessionId      string                 `protobuf:"bytes,7,opt,name=web_session_id,json=webSessionId,proto3" json:"web_session_id,omitempty"`
	CliSessionId      string                 `protobuf:"bytes,22,opt,name=cli_session_id,json=cliSessionId,proto3" json:"cli_session_id,omitempty"`
	// Intent & Payload
	EventType      string           `protobuf:"bytes,8,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload        []byte           `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`                                      // Raw protobuf payload
	IntentData     *structpb.Struct `protobuf:"bytes,10,opt,name=intent_data,json=intentData,proto3" json:"intent_data,omitempty"`             // Structured JSON-first view
	ActionType     string           `protobuf:"bytes,19,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`             // UAP-compatible action type (e.g., EXECUTE_BASH)
	TargetResource string           `protobuf:"bytes,20,opt,name=target_resource,json=targetResource,proto3" json:"target_resource,omitempty"` // UAP-compatible target resource
	// State & Replay Protection
	StateMerkleRoot string `protobuf:"bytes,11,opt,name=state_merkle_root,json=stateMerkleRoot,proto3" json:"state_merkle_root,omitempty"`
	Nonce           string `protobuf:"bytes,12,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TransactionHash string `protobuf:"bytes,13,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	ProtocolVersion string `protobuf:"bytes,21,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // UAP-compatible protocol version (e.g., "1.0")
	// Governance Proofs
	Governance *GovernanceMetadata `protobuf:"bytes,14,opt,name=governance,proto3" json:"governance,omitempty"`
	// Application Context
	CaseId            string `protobuf:"bytes,15,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	InvestigationId   string `protobuf:"bytes,16,opt,name=investigation_id,json=investigationId,proto3" json:"investigation_id,omitempty"`
	TaskId            string `protobuf:"bytes,17,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SystemFingerprint string `protobuf:"bytes,18,opt,name=system_fingerprint,json=systemFingerprint,proto3" json:"system_fingerprint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GovernanceEnvelope) Reset() {
	*x = GovernanceEnvelope{}
	mi := &file_g8e_common_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovernanceEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovernanceEnvelope) ProtoMessage() {}

func (x *GovernanceEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_g8e_common_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovernanceEnvelope.ProtoReflect.Descriptor instead.
func (*GovernanceEnvelope) Descriptor() ([]byte, []int) {
	return file_g8e_common_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *GovernanceEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GovernanceEnvelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GovernanceEnvelope) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GovernanceEnvelope) GetSourceComponent() Component {
	if x != nil {
		return x.SourceComponent
	}
	return Component_COMPONENT_UNSPECIFIED
}

func (x *GovernanceEnvelope) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *GovernanceEnvelope) GetOperatorSessionId() string {
	if x != nil {
		return x.OperatorSessionId
	}
	return ""
}

func (x *GovernanceEnvelope) GetWebSessionId() string {
	if x != nil {
		return x.WebSessionId
	}
	return ""
}

func (x *GovernanceEnvelope) GetCliSessionId() string {
	if x != nil {
		return x.CliSessionId
	}
	return ""
}

func (x *GovernanceEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *GovernanceEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GovernanceEnvelope) GetIntentData() *structpb.Struct {
	if x != nil {
		return x.IntentData
	}
	return nil
}

func (x *GovernanceEnvelope) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *GovernanceEnvelope) GetTargetResource() string {
	if x != nil {
		return x.TargetResource
	}
	return ""
}

func (x *GovernanceEnvelope) GetStateMerkleRoot() string {
	if x != nil {
		return x.StateMerkleRoot
	}
	return ""
}

func (x *GovernanceEnvelope) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *GovernanceEnvelope) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *GovernanceEnvelope) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *GovernanceEnvelope) GetGovernance() *GovernanceMetadata {
	if x != nil {
		return x.Governance
	}
	return nil
}

func (x *GovernanceEnvelope) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *GovernanceEnvelope) GetInvestigationId() string {
	if x != nil {
		return x.InvestigationId
	}
	return ""
}

func (x *GovernanceEnvelope) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GovernanceEnvelope) GetSystemFingerprint() string {
	if x != nil {
		return x.SystemFingerprint
	}
	return ""
}

var file_g8e_common_v1_common_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "g8e.common.v1.forbidden_patterns",
		Tag:           "bytes,50001,opt,name=forbidden_patterns",
		Filename:      "g8e/common/v1/common.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Comma-separated list of forbidden regex patterns
	//
	// optional string forbidden_patterns = 50001;
	E_ForbiddenPatterns = &file_g8e_common_v1_common_proto_extTypes[0]
)

var File_g8e_common_v1_common_proto protoreflect.FileDescriptor

const file_g8e_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1ag8e/common/v1/common.proto\x12\rg8e.common.v1\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"J\n" +
	"\n" +
	"L1Metadata\x12\x1c\n" +
	"\tvalidated\x18\x01 \x01(\bR\tvalidated\x12\x1e\n" +
	"\n" +
	"violations\x18\x02 \x03(\tR\n" +
	"violations\"o\n" +
	"\n" +
	"L2Metadata\x12-\n" +
	"\x12tribunal_signature\x18\x01 \x01(\tR\x11tribunalSignature\x12\x1b\n" +
	"\tagent_ids\x18\x02 \x03(\tR\bagentIds\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\"\xd9\x01\n" +
	"\aL3Proof\x12(\n" +
	"\x10client_data_json\x18\x01 \x01(\tR\x0eclientDataJSON\x12-\n" +
	"\x12authenticator_data\x18\x02 \x01(\tR\x11authenticatorData\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12#\n" +
	"\rcredential_id\x18\x04 \x01(\tR\fcredentialId\x122\n" +
	"\x15mtls_cert_fingerprint\x18\x05 \x01(\tR\x13mtlsCertFingerprint\"_\n" +
	"\n" +
	"L3Metadata\x12,\n" +
	"\x05proof\x18\x01 \x01(\v2\x16.g8e.common.v1.L3ProofR\x05proof\x12#\n" +
	"\rauto_approved\x18\x02 \x01(\bR\fautoApproved\"\xbc\x01\n" +
	"\x12GovernanceMetadata\x12)\n" +
	"\x02l1\x18\x01 \x01(\v2\x19.g8e.common.v1.L1MetadataR\x02l1\x12)\n" +
	"\x02l2\x18\x02 \x01(\v2\x19.g8e.common.v1.L2MetadataR\x02l2\x12)\n" +
	"\x02l3\x18\x03 \x01(\v2\x19.g8e.common.v1.L3MetadataR\x02l3\x12%\n" +
	"\x0egateway_signed\x18\x04 \x01(\bR\rgatewaySigned\"\x9f\a\n" +
	"\x12GovernanceEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12C\n" +
	"\x10source_component\x18\x04 \x01(\x0e2\x18.g8e.common.v1.ComponentR\x0fsourceComponent\x12\x1f\n" +
	"\voperator_id\x18\x05 \x01(\tR\n" +
	"operatorId\x12.\n" +
	"\x13operator_session_id\x18\x06 \x01(\tR\x11operatorSessionId\x12$\n" +
	"\x0eweb_session_id\x18\a \x01(\tR\fwebSessionId\x12$\n" +
	"\x0ecli_session_id\x18\x16 \x01(\tR\fcliSessionId\x12\x1d\n" +
	"\n" +
	"event_type\x18\b \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\x128\n" +
	"\vintent_data\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\n" +
	"intentData\x12\x1f\n" +
	"\vaction_type\x18\x13 \x01(\tR\n" +
	"actionType\x12'\n" +
	"\x0ftarget_resource\x18\x14 \x01(\tR\x0etargetResource\x12*\n" +
	"\x11state_merkle_root\x18\v \x01(\tR\x0fstateMerkleRoot\x12\x14\n" +
	"\x05nonce\x18\f \x01(\tR\x05nonce\x12)\n" +
	"\x10transaction_hash\x18\r \x01(\tR\x0ftransactionHash\x12)\n" +
	"\x10protocol_version\x18\x15 \x01(\tR\x0fprotocolVersion\x12A\n" +
	"\n" +
	"governance\x18\x0e \x01(\v2!.g8e.common.v1.GovernanceMetadataR\n" +
	"governance\x12\x17\n" +
	"\acase_id\x18\x0f \x01(\tR\x06caseId\x12)\n" +
	"\x10investigation_id\x18\x10 \x01(\tR\x0finvestigationId\x12\x17\n" +
	"\atask_id\x18\x11 \x01(\tR\x06taskId\x12-\n" +
	"\x12system_fingerprint\x18\x12 \x01(\tR\x11systemFingerprint*d\n" +
	"\tComponent\x12\x19\n" +
	"\x15COMPONENT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eCOMPONENT_G8EE\x10\x01\x12\x12\n" +
	"\x0eCOMPONENT_G8EO\x10\x02\x12\x14\n" +
	"\x10COMPONENT_CLIENT\x10\x03:N\n" +
	"\x12forbidden_patterns\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\tR\x11forbiddenPatternsB=Z;github.com/g8e-ai/g8e/protocol/proto/g8e/common/v1;commonv1b\x06proto3"

var (
	file_g8e_common_v1_common_proto_rawDescOnce sync.Once
	file_g8e_common_v1_common_proto_rawDescData []byte
)

func file_g8e_common_v1_common_proto_rawDescGZIP() []byte {
	file_g8e_common_v1_common_proto_rawDescOnce.Do(func() {
		file_g8e_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_g8e_common_v1_common_proto_rawDesc), len(file_g8e_common_v1_common_proto_rawDesc)))
	})
	return file_g8e_common_v1_common_proto_rawDescData
}

var file_g8e_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_g8e_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_g8e_common_v1_common_proto_goTypes = []any{
	(Component)(0),                    // 0: g8e.common.v1.Component
	(*L1Metadata)(nil),                // 1: g8e.common.v1.L1Metadata
	(*L2Metadata)(nil),                // 2: g8e.common.v1.L2Metadata
	(*L3Proof)(nil),                   // 3: g8e.common.v1.L3Proof
	(*L3Metadata)(nil),                // 4: g8e.common.v1.L3Metadata
	(*GovernanceMetadata)(nil),        // 5: g8e.common.v1.GovernanceMetadata
	(*GovernanceEnvelope)(nil),        // 6: g8e.common.v1.GovernanceEnvelope
	(*timestamppb.Timestamp)(nil),     // 7: google.protobuf.Timestamp
	(*structpb.Struct)(nil),           // 8: google.protobuf.Struct
	(*descriptorpb.FieldOptions)(nil), // 9: google.protobuf.FieldOptions
}
var file_g8e_common_v1_common_proto_depIdxs = []int32{
	3,  // 0: g8e.common.v1.L3Metadata.proof:type_name -> g8e.common.v1.L3Proof
	1,  // 1: g8e.common.v1.GovernanceMetadata.l1:type_name -> g8e.common.v1.L1Metadata
	2,  // 2: g8e.common.v1.GovernanceMetadata.l2:type_name -> g8e.common.v1.L2Metadata
	4,  // 3: g8e.common.v1.GovernanceMetadata.l3:type_name -> g8e.common.v1.L3Metadata
	7,  // 4: g8e.common.v1.GovernanceEnvelope.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 5: g8e.common.v1.GovernanceEnvelope.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 6: g8e.common.v1.GovernanceEnvelope.source_component:type_name -> g8e.common.v1.Component
	8,  // 7: g8e.common.v1.GovernanceEnvelope.intent_data:type_name -> google.protobuf.Struct
	5,  // 8: g8e.common.v1.GovernanceEnvelope.governance:type_name -> g8e.common.v1.GovernanceMetadata
	9,  // 9: g8e.common.v1.forbidden_patterns:extendee -> google.protobuf.FieldOptions
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	9,  // [9:10] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_g8e_common_v1_common_proto_init() }
func file_g8e_common_v1_common_proto_init() {
	if File_g8e_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_g8e_common_v1_common_proto_rawDesc), len(file_g8e_common_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_g8e_common_v1_common_proto_goTypes,
		DependencyIndexes: file_g8e_common_v1_common_proto_depIdxs,
		EnumInfos:         file_g8e_common_v1_common_proto_enumTypes,
		MessageInfos:      file_g8e_common_v1_common_proto_msgTypes,
		ExtensionInfos:    file_g8e_common_v1_common_proto_extTypes,
	}.Build()
	File_g8e_common_v1_common_proto = out.File
	file_g8e_common_v1_common_proto_goTypes = nil
	file_g8e_common_v1_common_proto_depIdxs = nil
}
