// Copyright (c) 2026 Lateralus Labs, LLC.
// Use of this source code is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date listed in the LICENSE file, this software is
// released under the Apache License, Version 2.0.

// Code generated by constgen; DO NOT EDIT.

package constants

// ActionType is a typed string for governed action classes.
type ActionType string

const (
	ActionTypeA2aCall ActionType = "A2A_CALL"
	ActionTypeCancel ActionType = "CANCEL"
	ActionTypeDocumentDelete ActionType = "DOCUMENT_DELETE"
	ActionTypeDocumentUpdate ActionType = "DOCUMENT_UPDATE"
	ActionTypeEvalAnswer ActionType = "EVAL_ANSWER"
	ActionTypeExecuteBash ActionType = "EXECUTE_BASH"
	ActionTypeFetchFileDiff ActionType = "FETCH_FILE_DIFF"
	ActionTypeFetchFileHistory ActionType = "FETCH_FILE_HISTORY"
	ActionTypeFetchHistory ActionType = "FETCH_HISTORY"
	ActionTypeFetchLogs ActionType = "FETCH_LOGS"
	ActionTypeFileEdit ActionType = "FILE_EDIT"
	ActionTypeFsGrep ActionType = "FS_GREP"
	ActionTypeFsList ActionType = "FS_LIST"
	ActionTypeFsRead ActionType = "FS_READ"
	ActionTypeHeartbeat ActionType = "HEARTBEAT"
	ActionTypeInference ActionType = "INFERENCE"
	ActionTypeMcpCall ActionType = "MCP_CALL"
	ActionTypeMcpPromptGet ActionType = "MCP_PROMPT_GET"
	ActionTypeMcpPromptList ActionType = "MCP_PROMPT_LIST"
	ActionTypeMcpResourceList ActionType = "MCP_RESOURCE_LIST"
	ActionTypeMcpResourceRead ActionType = "MCP_RESOURCE_READ"
	ActionTypeModelProvenanceObservation ActionType = "MODEL_PROVENANCE_OBSERVATION"
	ActionTypeOllamaModelInventory ActionType = "OLLAMA_MODEL_INVENTORY"
	ActionTypeOllamaModelResidency ActionType = "OLLAMA_MODEL_RESIDENCY"
	ActionTypePlatformEnrollmentCreate ActionType = "PLATFORM_ENROLLMENT_CREATE"
	ActionTypePlatformEnrollmentCreateSession ActionType = "PLATFORM_ENROLLMENT_CREATE_SESSION"
	ActionTypePlatformEnrollmentDecide ActionType = "PLATFORM_ENROLLMENT_DECIDE"
	ActionTypePlatformEnrollmentIssue ActionType = "PLATFORM_ENROLLMENT_ISSUE"
	ActionTypePlatformEnrollmentPersistPolicy ActionType = "PLATFORM_ENROLLMENT_PERSIST_POLICY"
	ActionTypePlatformEnrollmentRevoke ActionType = "PLATFORM_ENROLLMENT_REVOKE"
	ActionTypePortCheck ActionType = "PORT_CHECK"
	ActionTypeProviderBoundaryObservation ActionType = "PROVIDER_BOUNDARY_OBSERVATION"
	ActionTypeRestoreFile ActionType = "RESTORE_FILE"
	ActionTypeShutdown ActionType = "SHUTDOWN"
)

// AllActionTypes is the canonical slice of all valid action types.
var AllActionTypes = []ActionType{
	ActionTypeA2aCall,
	ActionTypeCancel,
	ActionTypeDocumentDelete,
	ActionTypeDocumentUpdate,
	ActionTypeEvalAnswer,
	ActionTypeExecuteBash,
	ActionTypeFetchFileDiff,
	ActionTypeFetchFileHistory,
	ActionTypeFetchHistory,
	ActionTypeFetchLogs,
	ActionTypeFileEdit,
	ActionTypeFsGrep,
	ActionTypeFsList,
	ActionTypeFsRead,
	ActionTypeHeartbeat,
	ActionTypeInference,
	ActionTypeMcpCall,
	ActionTypeMcpPromptGet,
	ActionTypeMcpPromptList,
	ActionTypeMcpResourceList,
	ActionTypeMcpResourceRead,
	ActionTypeModelProvenanceObservation,
	ActionTypeOllamaModelInventory,
	ActionTypeOllamaModelResidency,
	ActionTypePlatformEnrollmentCreate,
	ActionTypePlatformEnrollmentCreateSession,
	ActionTypePlatformEnrollmentDecide,
	ActionTypePlatformEnrollmentIssue,
	ActionTypePlatformEnrollmentPersistPolicy,
	ActionTypePlatformEnrollmentRevoke,
	ActionTypePortCheck,
	ActionTypeProviderBoundaryObservation,
	ActionTypeRestoreFile,
	ActionTypeShutdown,
}

// IsMutation returns true if the action type modifies system state.
func (a ActionType) IsMutation() bool {
	switch a {
	case ActionTypeA2aCall,
		ActionTypeCancel,
		ActionTypeDocumentDelete,
		ActionTypeDocumentUpdate,
		ActionTypeExecuteBash,
		ActionTypeFileEdit,
		ActionTypeInference,
		ActionTypeMcpCall,
		ActionTypePlatformEnrollmentCreateSession,
		ActionTypePlatformEnrollmentDecide,
		ActionTypePlatformEnrollmentIssue,
		ActionTypePlatformEnrollmentPersistPolicy,
		ActionTypePlatformEnrollmentRevoke,
		ActionTypeRestoreFile,
		ActionTypeShutdown:
		return true
	default:
		return false
	}
}

// IsBootstrapAction returns true for platform enrollment bootstrap actions.
func (a ActionType) IsBootstrapAction() bool {
	switch a {
	case ActionTypePlatformEnrollmentCreate,
		ActionTypePlatformEnrollmentCreateSession,
		ActionTypePlatformEnrollmentDecide,
		ActionTypePlatformEnrollmentIssue,
		ActionTypePlatformEnrollmentPersistPolicy,
		ActionTypePlatformEnrollmentRevoke:
		return true
	default:
		return false
	}
}
