// Copyright (c) 2026 Lateralus Labs, LLC.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package constants

import "errors"

// Standard platform errors
var (
	ErrUserNotFound         = errors.New("user not found")
	ErrNoPasskeysRegistered = errors.New("no passkeys registered")
	ErrInvalidJSONBody      = errors.New("invalid JSON body")
	ErrUserIDRequired       = errors.New("user_id required")
	ErrMethodNotAllowed     = errors.New("method not allowed")
	ErrForbidden            = errors.New("forbidden")
	ErrInternal             = errors.New("internal error")
	ErrNotFound             = errors.New("not found")
	ErrAlreadyExists        = errors.New("already exists")
	ErrConstraintViolation  = errors.New("constraint violation")
	ErrDatabaseLocked       = errors.New("database is locked")
	ErrServiceUnavailable   = errors.New("service unavailable")
	ErrDatabaseReplay       = errors.New("database replay detected")
	ErrDuplicateColumn      = errors.New("duplicate column name")
	ErrProcessKilled        = errors.New("process killed")
	ErrTrustBundleStale     = errors.New("trust bundle stale")
	ErrKeyNotFound          = errors.New("key not found")
	ErrExpired              = errors.New("expired")
	ErrAgentNotFound        = errors.New("agent not found")
	ErrAgentNotInPath       = errors.New("agent binary not found in PATH")
	ErrAgentNotSupported    = errors.New("agent auto-launch not supported")
	ErrConfigFileExists     = errors.New("config file already exists")
	ErrEndpointRequired     = errors.New("endpoint required")
	ErrGatewayURLRequired   = errors.New("gateway URL is required")
	ErrConfigLoadFailed     = errors.New("config load failed")
	ErrCSRGenerationFailed  = errors.New("CSR generation failed")
	ErrEnrollmentFailed     = errors.New("enrollment failed")
	ErrMissingCertificate   = errors.New("missing certificate")
	ErrDirCreateFailed      = errors.New("directory creation failed")
	ErrPKIDirRequired       = errors.New("PKI directory required")
	ErrCertSaveFailed       = errors.New("certificate save failed")
	ErrChainSaveFailed      = errors.New("certificate chain save failed")
	ErrTrustSaveFailed      = errors.New("trust bundle save failed")
	ErrValidationFailed     = errors.New("security validation failed")
	ErrPEMDecodeFailed      = errors.New("failed to decode PEM block")
	ErrInvalidPEMType       = errors.New("invalid PEM block type")
	ErrPEMExtraData         = errors.New("extra data after PEM block")
	ErrHTTPStatusError      = errors.New("HTTP status error")
	ErrEmptyTrustBundle     = errors.New("trust bundle is empty")
	ErrCAParseFailed        = errors.New("failed to parse CA certificates")
	ErrMissingRequiredField = errors.New("missing required field")
	ErrInvalidLogLevel      = errors.New("invalid log level")

	// Keystore errors
	ErrKeyStoreKeyNotFound = errors.New("master key not found in OS key store")
	ErrKeyStoreLocked      = errors.New("OS key store is locked/unavailable")
	ErrInvalidCiphertext   = errors.New("invalid ciphertext or authentication failed")
	ErrOSNotSupported      = errors.New("OS not supported for OS-native key store")

	// Ledger errors
	ErrLedgerDisabled       = errors.New("ledger is disabled")
	ErrLedgerConfigRequired = errors.New("ledger config is required")
	ErrLedgerVaultRequired  = errors.New("ledger encryption vault is required")

	// Ledger status messages
	LedgerStatusFileDeleted = "file deleted"

	// CLI approval errors
	ErrKeyReadFailed            = errors.New("failed to read CLI private key")
	ErrKeyParseFailed           = errors.New("failed to parse private key")
	ErrInvalidKeyType           = errors.New("private key is not Ed25519")
	ErrCertReadFailed           = errors.New("failed to read CLI certificate")
	ErrCertParseFailed          = errors.New("failed to parse certificate")
	ErrRequestMarshalFailed     = errors.New("failed to marshal request")
	ErrTransactionApproveFailed = errors.New("failed to approve transaction")
	ErrResponseParseFailed      = errors.New("failed to parse response")

	// Notary errors
	ErrTransactionExpired = errors.New("transaction approval expired")

	// CLI authentication errors
	ErrNotAuthenticated              = errors.New("not authenticated")
	ErrFailedToLoadCredentials       = errors.New("failed to load credentials")
	ErrFailedToLoadClientCertificate = errors.New("failed to load client certificate")
	ErrFailedToReadTrustBundle       = errors.New("failed to read trust bundle")
	ErrFailedToParseTrustBundle      = errors.New("failed to parse trust bundle")
	ErrFailedToParsePaths            = errors.New("failed to parse paths.json")

	// HTTP client errors
	ErrHTTPRequestCreateFailed = errors.New("failed to create HTTP request")
	ErrHTTPRequestExecuteFailed = errors.New("failed to execute HTTP request")
	ErrHTTPResponseReadFailed = errors.New("failed to read HTTP response")
	ErrHTTPRequestMarshalFailed = errors.New("failed to marshal request body")
	ErrInvalidJSONResponse = errors.New("invalid JSON response")

	// Process manager errors
	ErrProcessStartFailed = errors.New("process start failed")
	ErrProcessStopFailed  = errors.New("process stop failed")
	ErrPortUnavailable    = errors.New("port unavailable")
	ErrInvalidPosture     = errors.New("invalid posture")
	ErrPIDReadFailed      = errors.New("failed to read PID file")
	ErrPIDWriteFailed     = errors.New("failed to write PID file")
	ErrPostureReadFailed  = errors.New("failed to read posture file")
	ErrPostureWriteFailed = errors.New("failed to write posture file")
	ErrProcessInterrupted = errors.New("process interrupted")

	// File system errors
	ErrPathNotFound      = errors.New("path not found")
	ErrStatFailed        = errors.New("failed to stat path")
	ErrNotADirectory     = errors.New("path is not a directory")
	ErrPathValidation    = errors.New("invalid path")
	ErrDirectoryList     = errors.New("failed to list directory")
	ErrDirectoryRead     = errors.New("failed to read directory")
	ErrFileOpenFailed    = errors.New("failed to open file")
	ErrInvalidRegex      = errors.New("invalid regex pattern")
	ErrGrepFailed        = errors.New("failed to perform grep")

	// Execution service errors
	ErrExecutionServiceStopping = errors.New("execution service is stopping")
	ErrExecutionNotFound        = errors.New("execution not found")
	ErrEmptyCommand             = errors.New("empty command")
	ErrCommandLookup            = errors.New("command lookup failed")
	ErrShellRequired            = errors.New("shell required but not found")
	ErrCloudCLIBlocked          = errors.New("cloud CLI command blocked")

	// MCP service errors
	ErrMCPUnmarshalArguments = errors.New("unmarshal arguments")
	ErrMCPGetDiskUsage       = errors.New("get disk usage")
	ErrMCPStatFS             = errors.New("statfs")
	ErrMCPParseMounts        = errors.New("parse mounts")
	ErrMCPReadMounts         = errors.New("read /proc/mounts")
	ErrMCPHostPortRequired   = errors.New("host and port required")
	ErrMCPGetAbsolutePath    = errors.New("get absolute path")
	ErrMCPGetDiskFreeSpaceEx = errors.New("GetDiskFreeSpaceExW failed")

	// MCP registry errors
	ErrMCPSchemaNil               = errors.New("schema cannot be nil")
	ErrMCPSchemaMissingType       = errors.New("schema missing required 'type' field")
	ErrMCPSchemaInvalidType       = errors.New("schema 'type' must be 'object'")
	ErrMCPSchemaInvalidProperties = errors.New("schema 'properties' must be an object")
	ErrMCPSchemaInvalidRequired   = errors.New("schema 'required' must be an array")
	ErrMCPToolNil                 = errors.New("cannot register nil tool")
	ErrMCPToolNameEmpty           = errors.New("tool name cannot be empty")
	ErrMCPToolNameInvalid         = errors.New("invalid tool name: must contain only lowercase letters, digits, and underscores")
	ErrMCPToolAlreadyRegistered   = errors.New("tool is already registered")
	ErrMCPRegistryNil             = errors.New("registry cannot be nil")

	// MCP validation errors
	ErrMCPValidateSQLQueryEmpty                 = errors.New("SQL query cannot be empty")
	ErrMCPValidateSQLQueryTrailingSemicolon     = errors.New("SQL query must not end with semicolon")
	ErrMCPValidateURLInvalidScheme              = errors.New("only http and https schemes are allowed")
	ErrMCPValidateURLMissingHost                = errors.New("URL must have a host")
	ErrMCPValidateURLLoopbackAddress            = errors.New("localhost and loopback addresses are not allowed")
	ErrMCPValidateURLPrivateAddress             = errors.New("private and loopback IP addresses are not allowed")
	ErrMCPValidateProcNetInvalidProtocol        = errors.New("invalid protocol")
	ErrMCPValidatePathEmpty                     = errors.New("path cannot be empty")
	ErrMCPValidatePathWhitespace                = errors.New("path must not contain leading/trailing whitespace")
	ErrMCPValidatePathParentDirRef              = errors.New("path must not contain parent directory references (..)")
	ErrMCPValidatePathNullBytes                 = errors.New("path must not contain null bytes")
	ErrMCPValidateRefEmpty                      = errors.New("git reference cannot be empty")
	ErrMCPValidateRefWhitespace                 = errors.New("git reference must not contain leading/trailing whitespace")
	ErrMCPValidateRefNullBytes                  = errors.New("git reference must not contain null bytes")
	ErrMCPValidateRefDangerousChar              = errors.New("git reference contains dangerous character")
	ErrMCPValidateRefAbsolutePath               = errors.New("git reference must not be an absolute path")
	ErrMCPValidateRefInvalidChars               = errors.New("git reference contains invalid characters")
	ErrMCPValidateK8sNameEmpty                  = errors.New("resource name cannot be empty")
	ErrMCPValidateK8sNameWhitespace             = errors.New("resource name must not contain leading/trailing whitespace")
	ErrMCPValidateK8sNameTooLong                = errors.New("resource name must not exceed 253 characters")
	ErrMCPValidateK8sNameInvalidPattern         = errors.New("resource name must consist of lowercase alphanumeric characters, hyphens, or dots, and must start and end with an alphanumeric character")
	ErrMCPValidateK8sNameNullBytes              = errors.New("resource name must not contain null bytes")
	ErrMCPValidateK8sNamespaceEmpty             = errors.New("namespace cannot be empty")
	ErrMCPValidateK8sNamespaceWhitespace        = errors.New("namespace must not contain leading/trailing whitespace")
	ErrMCPValidateK8sNamespaceTooLong           = errors.New("namespace must not exceed 63 characters")
	ErrMCPValidateK8sNamespaceInvalidPattern    = errors.New("namespace must consist of lowercase alphanumeric characters or hyphens, and must start and end with an alphanumeric character")
	ErrMCPValidateK8sNamespaceNullBytes         = errors.New("namespace must not contain null bytes")
	ErrMCPValidateCloudMetadataInvalidOperation = errors.New("invalid operation")
	ErrMCPValidateHostnameEmpty                 = errors.New("hostname cannot be empty")
	ErrMCPValidateHostnameWhitespace            = errors.New("hostname must not contain leading/trailing whitespace")
	ErrMCPValidateHostnameNullBytes             = errors.New("hostname must not contain null bytes")
	ErrMCPValidateHostnameDangerousChar         = errors.New("hostname contains dangerous character")
	ErrMCPValidateHostnamesEmpty                = errors.New("hostnames list cannot be empty")
	ErrMCPValidateOperatorArgsNullBytes         = errors.New("argument must not contain null bytes")
	ErrMCPValidateOperatorArgsDangerousChar     = errors.New("argument contains dangerous character")

	// MCP OOM detection errors
	ErrMCPGetWorkingDirectory = errors.New("get working directory")
	ErrMCPOpenLogFile         = errors.New("open log file")
	ErrMCPReadLogFile         = errors.New("read log file")
	ErrMCPMarshalOOMResult    = errors.New("marshal OOM result")

	// MCP SSH known hosts errors
	ErrMCPGetHomeDirectory = errors.New("get home directory")
	ErrMCPMarshalResult    = errors.New("marshal result")

	// MCP proc signal safe errors
	ErrMCPProcSignalRequired = errors.New("pid and signal required")

	// MCP git ops errors
	ErrMCPGitOpsUnsupportedOperation = errors.New("unsupported operation")

	// MCP TLS cert inspect errors
	ErrMCPTLSCertInspectRequired = errors.New("either cert_path or host must be specified")

	// Run shell command errors
	ErrMCPRunShellCommandRequired              = errors.New("command is required")
	ErrMCPRunShellCommandSafetyRejected        = errors.New("command rejected by safety policy")
	ErrMCPRunShellCommandTimeoutExceeded       = errors.New("timeout cannot exceed 300 seconds")
	ErrMCPRunShellCommandMarshalResult         = errors.New("marshal result")
	ErrMCPRunShellCommandBlocked               = errors.New("command is blocked by safety policy")
	ErrMCPRunShellCommandDangerousPattern      = errors.New("command contains dangerous pattern")
	ErrMCPRunShellCommandShellInjection        = errors.New("command contains shell injection pattern")
	ErrMCPRunShellCommandPathTraversal         = errors.New("working directory contains path traversal")
	ErrMCPRunShellCommandAbsolutePathRequired  = errors.New("working directory must be an absolute path")
	ErrMCPRunShellCommandDirNotAccessible      = errors.New("working directory does not exist or is not accessible")
	ErrMCPRunShellCommandNotDirectory          = errors.New("working directory is not a directory")
	ErrMCPRunShellCommandShellMetacharacter    = errors.New("command contains shell metacharacter which is not allowed for SSH execution")
	ErrMCPRunShellCommandArgMetacharacter      = errors.New("argument contains shell metacharacter which is not allowed for SSH execution")
	ErrMCPRunShellCommandDirMetacharacter      = errors.New("working directory contains shell metacharacter which is not allowed for SSH execution")
	ErrMCPRunShellCommandResolveHost           = errors.New("resolve host")
	ErrMCPRunShellCommandHostnameResolveFailed = errors.New("failed to resolve hostname")
	ErrMCPRunShellCommandBuildAuth             = errors.New("build auth methods")
	ErrMCPRunShellCommandNoAuth                = errors.New("no SSH auth methods available")
	ErrMCPRunShellCommandHostKeyVerification   = errors.New("host key verification failed")
	ErrMCPRunShellCommandSSHDial               = errors.New("SSH dial failed")
	ErrMCPRunShellCommandSSHSession            = errors.New("SSH session creation failed")
	ErrMCPRunShellCommandTimedOut              = errors.New("command timed out")

	// Network identity detection errors
	ErrNetworkDetectInterfaces    = errors.New("failed to get network interfaces")
	ErrNetworkOpenHostsFile       = errors.New("failed to open hosts file")
	ErrNetworkScanHostsFile       = errors.New("error scanning hosts file")
	ErrNetworkDetectMDNS          = errors.New("detect mDNS names")
	ErrNetworkDetectHostnames     = errors.New("detect hostnames")
	ErrNetworkDetectIPs           = errors.New("detect IPs")
	ErrNetworkDetectHostsAliases  = errors.New("detect hosts file aliases")
	ErrNetworkDetectDNSPTR        = errors.New("detect DNS PTR records")
	ErrNetworkDetectSSHKnownHosts = errors.New("detect SSH known hosts")
	ErrNetworkDetectWindows       = errors.New("detect Windows identity")
	ErrNetworkGetHostname         = errors.New("get hostname")
	ErrNetworkGetSysteminfo       = errors.New("get systeminfo")

	// Audit service errors
	ErrAuditUnmarshalUserMsg      = errors.New("failed to unmarshal user message payload")
	ErrAuditUnmarshalAIMsg        = errors.New("failed to unmarshal AI message payload")
	ErrAuditUnmarshalDirectCmd    = errors.New("failed to unmarshal direct command payload")
	ErrAuditUnmarshalDirectResult = errors.New("failed to unmarshal direct command result payload")
	ErrAuditRecordUserMsg         = errors.New("failed to record user message")
	ErrAuditRecordAIMsg           = errors.New("failed to record AI message")
	ErrAuditRecordDirectCmd       = errors.New("failed to record direct command")
	ErrAuditRecordDirectResult    = errors.New("failed to record direct command result")

	// PubSub service errors
	ErrPubSubEmptyPayload         = errors.New("empty payload")
	ErrPubSubTransactionVerifier  = errors.New("transaction verifier not configured")
	ErrPubSubActuator             = errors.New("actuator not configured")
	ErrPubSubL4Warden             = errors.New("L4Warden not configured")
	ErrPubSubMCPGateway           = errors.New("MCP gateway not configured")
	ErrPubSubMCPMissingToolName   = errors.New("MCP call missing tool_name")
	ErrPubSubA2AGateway           = errors.New("A2A gateway not configured")
	ErrPubSubA2AMissingSkillName  = errors.New("A2A call missing skill_name")
	ErrPubSubActuatorOrAuditStore = errors.New("actuator or ConsoleAuditStore not configured")

	// Scrubbing service errors
	ErrScrubbingInvalidPattern = errors.New("invalid custom scrub pattern")
	ErrScrubbingRegexTimeout   = errors.New("regex compilation timeout")
	ErrScrubbingTokenPersist   = errors.New("failed to persist token to local store")
	ErrScrubbingTokenLoad      = errors.New("failed to load persisted tokens from TokenStore")
	ErrScrubbingTokenKeyFormat = errors.New("invalid token key format")
	ErrScrubbingTokenSequence  = errors.New("failed to parse token sequence")

	// Gateway service errors
	ErrGatewayToolNameRequired             = errors.New("tool name required")
	ErrGatewayInvalidToolArguments         = errors.New("invalid tool arguments: must be a valid JSON object")
	ErrGatewayFieldPathRegistryNotInit     = errors.New("field path registry not initialized")
	ErrGatewayDatabaseServiceNotConfigured = errors.New("database service not configured")
	ErrGatewayCollectionRequired           = errors.New("collection required")
	ErrGatewayDocumentIDRequired           = errors.New("document_id required")
	ErrGatewayFieldPathRequired            = errors.New("field_path required")
	ErrGatewayOperatorSessionIDRequired    = errors.New("operator_session_id required")
	ErrGatewayOperatorSessionInvalid       = errors.New("operator session is invalid or expired")
	ErrGatewayURIRequired                  = errors.New("uri required")
	ErrGatewayNameRequired                 = errors.New("name required")
	ErrGatewaySkillNameRequired            = errors.New("skill_name required")
	ErrGatewayNoDownstreamConfigured       = errors.New("no downstream MCP server configured")
	ErrGatewayDownstreamUnavailable        = errors.New("downstream MCP server is temporarily unavailable (circuit open)")
	ErrGatewayNoA2ADownstreamConfigured    = errors.New("no downstream A2A server configured")
	ErrGatewayNotReady                     = errors.New("g8e Gateway not ready")
	ErrGatewayL3ProofRequired              = errors.New("L3 proof required")
	ErrGatewayUserIDRequired               = errors.New("user_id required")
	ErrGatewayInvalidPosture               = errors.New("invalid posture")
	ErrGatewayForbiddenPattern             = errors.New("forbidden pattern detected")
	ErrGatewayDownstreamHTTPError          = errors.New("downstream server returned HTTP error")
	ErrGatewayMCPError                     = errors.New("MCP error")
	ErrGatewayA2AError                     = errors.New("A2A error")
	ErrGatewayAlreadyRunning               = errors.New("gateway service already running")
	ErrGatewayShutdownTimeout              = errors.New("shutdown timeout exceeded")

	// MCP native handler errors
	ErrMCPNativeToolRegistration = errors.New("native tool registration failed")
	ErrMCPNativeToolUnknown      = errors.New("unknown native tool")
	ErrMCPParseSocketPort        = errors.New("parse socket port")
	ErrMCPParseSocketIPOctet     = errors.New("parse socket IP octet")

	// SQLite validation errors
	ErrSQLiteValidateEmptyIdentifier = errors.New("empty identifier")
	ErrSQLiteValidateInvalidPattern  = errors.New("invalid identifier pattern")

	// SQLite utility errors
	ErrSQLitePruneFailed = errors.New("prune function failed")

	// SQLite compression errors
	ErrSQLiteCompressGzipWrite  = errors.New("gzip write failed")
	ErrSQLiteCompressGzipClose  = errors.New("gzip close failed")
	ErrSQLiteDecompressGzipInit = errors.New("gzip reader init failed")
	ErrSQLiteDecompressGzipRead = errors.New("gzip read failed")

	// Timestamp errors
	ErrTimestampParseEmpty         = errors.New("timestamp: parse: empty string")
	ErrTimestampParseInvalidFormat = errors.New("timestamp: parse: unrecognized format")

	// Passkey bootstrap errors
	ErrPasskeyRegistrationTimedOut = errors.New("passkey registration timed out")
	ErrPasskeyRegistrationFailed   = errors.New("passkey registration failed")
	ErrPasskeyRequiresBrowser      = errors.New("direct passkey registration requires browser interaction; use RegisterPasskeyViaLocalhost instead")
	ErrGetCurrentUser              = errors.New("failed to get current user")
	ErrPasskeyBootstrapServerStart = errors.New("failed to start passkey bootstrap server")

	// Windows-specific errors
	ErrWindowsSpecificEnrollment = errors.New("windows-specific enrollment is only available on Windows")
	ErrWindowsCertStoreImport    = errors.New("windows cert store import is only available on Windows")
	ErrWindowsHelloSigning       = errors.New("windows Hello signing is only available on Windows")
	ErrWindowsHelloAuthentication = errors.New("windows Hello authentication is only available on Windows")
	ErrWindowsHelloRegistration  = errors.New("windows Hello registration is only available on Windows")
	ErrWindowsCertStoreTrust     = errors.New("windows cert store trust is only available on Windows")
	ErrWindowsWebAuthnDLLNotFound = errors.New("webauthn.dll not found")
	ErrWindowsWebAuthnAPIVersion  = errors.New("Windows Hello API version too old")
	ErrWindowsTempDirCreate      = errors.New("failed to create Windows temp directory")
	ErrWindowsCertWriteFailed    = errors.New("failed to write certificate to temp file")
	ErrWindowsPowerShellImport   = errors.New("failed to import certificate via PowerShell")
	ErrWindowsPowerShellTrust    = errors.New("failed to trust Root CA via PowerShell")

	// Data command errors
	ErrCollectionRequired        = errors.New("collection required")
	ErrOperatorSessionIDRequired = errors.New("operator session id required")
	ErrAuditVaultDatabaseNotFound = errors.New("audit vault database not found")
	ErrAuditQueryFailed         = errors.New("failed to query audit events")
	ErrAuditScanFailed          = errors.New("failed to scan audit row")

	// Test command errors
	ErrGatewayNotRunning        = errors.New("gateway not running")
	ErrChaosTestDatabaseNotFound = errors.New("chaos test database not found")
	ErrUnitTestsFailed          = errors.New("unit tests failed")
	ErrIntegrationTestsFailed   = errors.New("integration tests failed")
	ErrE2ETestsFailed           = errors.New("e2e tests failed")
	ErrCoverageTestsFailed      = errors.New("coverage tests failed")
	ErrLintingFailed            = errors.New("linting failed")

	// Vault command errors
	ErrVaultAlreadyInitialized = errors.New("vault already initialized")
	ErrVaultNotInitialized     = errors.New("vault not initialized")
	ErrVaultKeyReadFailed      = errors.New("failed to read vault key file")
	ErrVaultKeyDecodeFailed    = errors.New("failed to decode vault key")
	ErrVaultKeyInvalidSize     = errors.New("invalid vault key size")
	ErrVaultKeyGenerateFailed  = errors.New("failed to generate vault key")
	ErrVaultHeaderCreateFailed = errors.New("failed to create vault header")
	ErrVaultHeaderSaveFailed   = errors.New("failed to save vault header")
	ErrVaultCreateFailed       = errors.New("failed to create vault")
	ErrVaultUnlockFailed       = errors.New("failed to unlock vault")
	ErrVaultRekeyFailed        = errors.New("failed to rekey vault")
	ErrVaultResetFailed        = errors.New("failed to reset vault")
	ErrVaultKeyWriteFailed     = errors.New("failed to write vault key")

	// Config errors
	ErrConfigHTTPPortZero        = errors.New("httpPort cannot be 0 in production")
	ErrConfigHTTPSPortZero       = errors.New("httpsPort cannot be 0 in production")
	ErrConfigPortsMustDiffer     = errors.New("httpPort and httpsPort must be different")
	ErrConfigInvalidWorkingDir   = errors.New("invalid working directory")

	// SSH config errors
	ErrSSHOpenConfigFile         = errors.New("failed to open SSH config file")
	ErrSSHExpandTilde            = errors.New("failed to expand tilde in path")
	ErrSSHScanConfigFile         = errors.New("failed to scan SSH config file")
	ErrSSHResolveHomeDir         = errors.New("failed to resolve home directory")
	ErrSSHParseConfig            = errors.New("failed to parse SSH config")
	ErrSSHDialAgentSocket        = errors.New("failed to dial SSH agent socket")
	ErrSSHGetAgentSigners        = errors.New("failed to get SSH agent signers")
	ErrSSHReadKeyFile            = errors.New("failed to read SSH key file")
	ErrSSHParsePrivateKey        = errors.New("failed to parse SSH private key")
	ErrSSHKnownHostsNotFound     = errors.New("SSH known_hosts file not found")
	ErrSSHParseKnownHosts        = errors.New("failed to parse SSH known_hosts file")

	// Bootstrap service errors
	ErrBootstrapTLSConfig        = errors.New("bootstrap: failed to configure TLS")
	ErrBootstrapFingerprint      = errors.New("bootstrap: failed to generate system fingerprint")
	ErrBootstrapAuth             = errors.New("bootstrap: failed to authenticate")
	ErrBootstrapRequestMarshal   = errors.New("bootstrap: failed to marshal auth request")
	ErrBootstrapRequestBuild     = errors.New("bootstrap: failed to build auth request")
	ErrBootstrapRequestExecute   = errors.New("bootstrap: authentication request failed")
	ErrBootstrapResponseRead     = errors.New("bootstrap: failed to read auth response")
	ErrBootstrapResponseClose    = errors.New("bootstrap: failed to close response body")
	ErrBootstrapResponseStatus   = errors.New("bootstrap: authentication failed with status")
	ErrBootstrapResponseDecode   = errors.New("bootstrap: failed to decode auth response")
	ErrBootstrapAuthFailed       = errors.New("bootstrap: authentication failed")
	ErrBootstrapNoConfig         = errors.New("bootstrap: no configuration returned from Auth Services")
	ErrBootstrapNoSessionID      = errors.New("bootstrap: no operator_session_id returned from Auth Services")
	ErrBootstrapCertParse        = errors.New("bootstrap: failed to parse per-operator cert+key")
	ErrBootstrapTLSConfigDI      = errors.New("bootstrap: failed to get base TLS config from DI")
	ErrBootstrapTLSConfigLegacy  = errors.New("bootstrap: failed to get base TLS config")
	ErrBootstrapCertTrust        = errors.New("bootstrap: cert trust failure: per-operator mTLS cert invalid")

	// CLI L3 notary errors
	ErrCLIL3TransactionHashRequired = errors.New("transaction_hash required for CLI L3 verification")
	ErrCLIL3CertFingerprintRequired = errors.New("mtls_cert_fingerprint required for CLI L3 verification")
	ErrCLIL3InvalidFingerprintFormat = errors.New("invalid mtls_cert_fingerprint format")
	ErrCLIL3UserInactive           = errors.New("user is not active")
	ErrCLIL3SessionIDRequired      = errors.New("cli_session_id required for CLI L3 verification")
	ErrCLIL3SessionLoadFailed      = errors.New("failed to load CLI session")
	ErrCLIL3SessionNotFound        = errors.New("CLI session not found")
	ErrCLIL3SessionMarshalFailed   = errors.New("failed to marshal CLI session")
	ErrCLIL3SessionUnmarshalFailed = errors.New("failed to unmarshal CLI session")
	ErrCLIL3SessionUserMismatch    = errors.New("CLI session user mismatch")
	ErrCLIL3FingerprintMismatch    = errors.New("certificate fingerprint mismatch")
	ErrCLIL3SessionInactive        = errors.New("CLI session is not active")
	ErrCLIL3SessionExpired         = errors.New("CLI session expired")
	ErrCLIL3CertRevocationCheckFailed = errors.New("failed to check certificate revocation status")
	ErrCLIL3CertNil                = errors.New("certificate is nil")
	ErrCLIL3CertExpired            = errors.New("certificate expired")
	ErrCLIL3CertNotYetValid        = errors.New("certificate not yet valid")
	ErrCLIL3CertVerificationFailed = errors.New("certificate verification failed")
	ErrCLIL3SPIFFESANMismatch      = errors.New("certificate SPIFFE URI SAN does not match CLI session")
	ErrCLIL3NoSessionIDInCert      = errors.New("no CLI session ID found in certificate SPIFFE URI SANs")
	ErrCLIL3NoUserIDInCert         = errors.New("no user ID found in certificate SPIFFE URI SANs")
	ErrCLIL3PKINotConfigured       = errors.New("PKI authority not configured")
	ErrCLIL3NoSPIFFEURI            = errors.New("no SPIFFE URI found in certificate")

	// File edit service errors
	ErrFileEditUnsupportedOperation = errors.New("unsupported file operation")
	ErrFileEditContentRequired      = errors.New("content is required for write operation")
	ErrFileEditOldContentRequired   = errors.New("old_content is required for replace operation")
	ErrFileEditNewContentRequired   = errors.New("new_content is required for replace operation")
	ErrFileEditInsertContentRequired = errors.New("insert_content is required for insert operation")
	ErrFileEditInsertPositionRequired = errors.New("insert_position is required for insert operation")
	ErrFileEditLineRangeRequired    = errors.New("start_line and end_line are required for delete operation")
	ErrFileEditPatchContentRequired = errors.New("patch_content is required for patch operation")
	ErrFileEditPatchNotImplemented  = errors.New("patch operation not yet implemented")
	ErrFileEditFileTooLarge         = errors.New("file too large for operation")
	ErrFileEditOldContentNotFound   = errors.New("old_content not found in file")
	ErrFileEditInsertPositionOutOfRange = errors.New("insert position out of range")
	ErrFileEditInvalidLineRange    = errors.New("invalid line range")
	ErrFileEditCreateBackupFailed  = errors.New("failed to create backup")
	ErrFileEditOpenFileFailed       = errors.New("failed to open file")
	ErrFileEditReadFileFailed       = errors.New("failed to read file")
	ErrFileEditWriteFileFailed     = errors.New("failed to write file")
	ErrFileEditReadLinesFailed     = errors.New("failed to read file lines")

	// DB controller errors
	ErrDBControllerKeyRequired      = errors.New("key required")
	ErrDBControllerNamespaceRequired = errors.New("namespace required")
	ErrDBControllerInvalidNamespace = errors.New("invalid namespace")
	ErrDBControllerInvalidBlobID     = errors.New("invalid blob id")
	ErrDBControllerInvalidPath      = errors.New("invalid path")
	ErrDBControllerContentTypeRequired = errors.New("Content-Type header required")
	ErrDBControllerBodyReadFailed    = errors.New("failed to read body")
	ErrDBControllerChannelRequired   = errors.New("channel required")
	ErrDBControllerPatternRequired   = errors.New("pattern required")
	ErrDBControllerTTLRequired       = errors.New("ttl required and must be > 0")
	ErrDBControllerInvalidSignerID   = errors.New("invalid signer id")
	ErrDBControllerInvalidTTL        = errors.New("X-Blob-TTL must be a non-negative integer")
	ErrDBControllerBlobTooLarge      = errors.New("blob exceeds maximum size")
	ErrDBControllerBodyEmpty         = errors.New("body must not be empty")

	// Authorization errors
	ErrUnauthorizedNoIdentity        = errors.New("unauthorized: no identity present")
	ErrUnauthorizedAppNamespace      = errors.New("unauthorized: app can only write to its own namespace")
	ErrUnauthorizedOperatorNoUserID  = errors.New("unauthorized: operator/CLI identity without user_id")
	ErrUnauthorizedUserNamespace     = errors.New("unauthorized: user can only write to their own namespace")
	ErrUnauthorizedUnknownIdentity   = errors.New("unauthorized: unknown identity type")

	// Document store service errors
	ErrDocumentStoreUnmarshalDocument = errors.New("failed to unmarshal document")
	ErrDocumentStoreMarshalDocument   = errors.New("failed to marshal document")
	ErrDocumentStoreUnmarshalFields   = errors.New("failed to unmarshal fields")
	ErrDocumentStoreExtractField      = errors.New("failed to extract field")
	ErrDocumentStoreDecodeField       = errors.New("failed to decode field")
	ErrDocumentStoreInvalidFilterField = errors.New("invalid filter field")
	ErrDocumentStoreInvalidFilterValue = errors.New("invalid filter value")
	ErrDocumentStoreInvalidOrderByField = errors.New("invalid orderBy field")
	ErrDocumentStoreParseCreatedAt    = errors.New("failed to parse created_at timestamp")
	ErrDocumentStoreParseUpdatedAt    = errors.New("failed to parse updated_at timestamp")
	ErrDocumentStoreUnmarshalData     = errors.New("failed to unmarshal document data")

	// App policy store service errors
	ErrAppPolicyStoreGetFailed    = errors.New("failed to get app policy")
	ErrAppPolicyStoreMarshalFailed = errors.New("failed to marshal app policy data")
	ErrAppPolicyStoreUnmarshalFailed = errors.New("failed to unmarshal app policy")

	// Fingerprint errors
	ErrFingerprintGetHostname      = errors.New("fingerprint: failed to get hostname")
	ErrFingerprintUnsupportedOS    = errors.New("fingerprint: unsupported operating system")
	ErrFingerprintMachineIDRead    = errors.New("fingerprint: could not read machine ID from any known path")

	// PKI errors
	ErrPKICreateDirectory             = errors.New("pki: failed to create directory")
	ErrPKILoadRootCA                 = errors.New("pki: failed to load root CA")
	ErrPKIGenerateRootCA             = errors.New("pki: failed to generate root CA")
	ErrPKILoadIntermediateCA         = errors.New("pki: failed to load intermediate CA")
	ErrPKIGenerateIntermediateCA     = errors.New("pki: failed to generate intermediate CA")
	ErrPKILoadServiceCert            = errors.New("pki: failed to load service certificate")
	ErrPKIGenerateServiceCert        = errors.New("pki: failed to generate service certificate")
	ErrPKIGenerateTrustBundles       = errors.New("pki: failed to generate trust bundles")
	ErrPKIRevokeCertificate          = errors.New("pki: failed to revoke certificate")
	ErrPKIGenerateCRL                = errors.New("pki: failed to generate CRL")
	ErrPKICheckRevocation            = errors.New("pki: failed to check revocation status")
	ErrPKICertificateRevoked         = errors.New("pki: certificate is revoked")
	ErrPKINoCertificate              = errors.New("pki: no certificate provided")
	ErrPKISignCSR                    = errors.New("pki: failed to sign CSR")
	ErrPKIInvalidCSR                 = errors.New("pki: invalid CSR PEM")
	ErrPKIParseCSR                   = errors.New("pki: failed to parse CSR")
	ErrPKICSRSignatureCheck          = errors.New("pki: CSR signature check failed")
	ErrPKIInvalidCurve               = errors.New("pki: CSR public key must use P-256 curve")
	ErrPKIGenerateSerial             = errors.New("pki: failed to generate serial")

	// State root service errors
	ErrStateRootCalculate            = errors.New("state root calculation failed")
	ErrStateRootPersist              = errors.New("state root persistence failed")
	ErrStateRootScanDocuments        = errors.New("failed to scan documents row")
	ErrStateRootHashDocuments        = errors.New("failed to hash documents table")
	ErrStateRootScanKVStore          = errors.New("failed to scan kv_store row")
	ErrStateRootHashKVStore          = errors.New("failed to hash kv_store table")
	ErrStateRootScanBlobs            = errors.New("failed to scan blobs row")
	ErrStateRootHashBlobs            = errors.New("failed to hash blobs table")
	ErrStateRootQueryTable           = errors.New("failed to query table")
	ErrStateRootIterateRows          = errors.New("failed to iterate rows")
	ErrStateRootUnsupportedType      = errors.New("unsupported type for state root hashing")
	ErrPKIGenerateSPIFFEURL          = errors.New("pki: failed to generate SPIFFE URL")
	ErrPKICreateCertificate          = errors.New("pki: failed to create certificate")
	ErrPKIParseCertificate           = errors.New("pki: failed to parse certificate")
	ErrPKIReadCACertificate           = errors.New("pki: failed to read CA certificate")
	ErrPKIInvalidCertPEM             = errors.New("pki: invalid cert PEM")
	ErrPKILoadCAPrivateKey           = errors.New("pki: failed to load CA private key")
	ErrPKIPrivateKeyRequired         = errors.New("pki: secret manager required for private key operations")
	ErrPKIPrivateKeyNotFound         = errors.New("pki: CA private key not found in keystore")
	ErrPKIPrivateKeyParse            = errors.New("pki: failed to parse private key")
	ErrPKIMarshalPrivateKey          = errors.New("pki: failed to marshal private key")
	ErrPKIStorePrivateKey            = errors.New("pki: failed to store private key in keystore")
	ErrPKIWritePEMFile               = errors.New("pki: failed to write PEM file")
	ErrPKIReadRootCA                 = errors.New("pki: failed to read root CA")
	ErrPKIReadHubCA                  = errors.New("pki: failed to read hub CA")
	ErrPKIReadOperatorCA             = errors.New("pki: failed to read operator CA")
	ErrPKIReadGatewayPeerCA          = errors.New("pki: failed to read gateway peer CA")
	ErrPKIWriteGatewayBundle         = errors.New("pki: failed to write gateway bundle")
	ErrPKIWriteOperatorBundle        = errors.New("pki: failed to write operator bundle")
	ErrPKIWriteRootBundle            = errors.New("pki: failed to write root bundle")
	ErrPKIMarshalTrustDomain         = errors.New("pki: failed to marshal trust domain data")
	ErrPKIWriteTrustDomain           = errors.New("pki: failed to write trust-domain.json")
	ErrPKIDatabaseNotAvailable       = errors.New("pki: database not available")
	ErrPKIOperatorCANotLoaded        = errors.New("pki: operator CA not loaded - call InitializePKI first")
	ErrPKIGatewayPeerCANotLoaded     = errors.New("pki: gateway peer CA not loaded - call InitializePKI first")
	ErrPKIHubCANotLoaded             = errors.New("pki: hub CA not loaded - call InitializePKI first")
	ErrPKIUnknownCACommonName        = errors.New("pki: unknown CA common name")
	ErrPKILoadServiceKey             = errors.New("pki: failed to load service private key")
	ErrPKIStoreServiceKey            = errors.New("pki: failed to store service private key")
	ErrPKIRenewServiceCert           = errors.New("pki: failed to renew service certificate")

	// Registration service errors
	ErrRegistrationUserIDRequired           = errors.New("user_id is required")
	ErrRegistrationOperatorIDRequired       = errors.New("operator_id is required")
	ErrRegistrationOperatorNotFound          = errors.New("operator not found")
	ErrRegistrationOperatorNotBelongToUser   = errors.New("operator does not belong to user")
	ErrRegistrationSystemFingerprintRequired = errors.New("system_fingerprint is required")
	ErrRegistrationOperatorCSRRequired       = errors.New("operator CSR is required")
	ErrRegistrationInvalidSystemFingerprint  = errors.New("invalid system_fingerprint")
	ErrRegistrationFailedToCreateSlot        = errors.New("failed to create Operator slot")
	ErrRegistrationFailedToResolveSlot       = errors.New("failed to resolve Operator slot")
	ErrRegistrationBootstrapRetirementFailed = errors.New("registration failed: bootstrap retirement failed")
	ErrRegistrationInvalidCSRPEMFormat       = errors.New("invalid CSR PEM format")
	ErrRegistrationCSRParsingFailed          = errors.New("CSR parsing failed")
	ErrRegistrationCSRSignFailed             = errors.New("failed to sign CSR")
	ErrRegistrationCSRRequired               = errors.New("CSR required for device registration")
	ErrRegistrationWebSessionIDRequired     = errors.New("web_session_id is required")
	ErrRegistrationOperatorIDsRequired       = errors.New("operator_ids required")
	ErrRegistrationOperatorNoActiveSession   = errors.New("operator has no active session")
	ErrRegistrationFailedToMarshalSessionIDs = errors.New("failed to marshal session IDs")
	ErrRegistrationFailedToSetKVBinding      = errors.New("failed to set KV binding")
	ErrRegistrationFailedToGetBoundSessions  = errors.New("failed to get bound sessions document")
	ErrRegistrationFailedToMarshalBoundSessions = errors.New("failed to marshal bound sessions document")
	ErrRegistrationFailedToSetBoundSessions = errors.New("failed to set bound sessions document")
	ErrRegistrationFailedToMarshalExistingDocument = errors.New("failed to marshal existing document")
	ErrRegistrationFailedToUnmarshalBoundSessions = errors.New("failed to unmarshal bound sessions document")
	ErrRegistrationFailedToUpdateBoundSessions = errors.New("failed to update bound sessions document")
	ErrRegistrationFailedToBindOperator     = errors.New("failed to bind Operator for target context")

	// Federation/Peer connection errors
	ErrFederationInvalidSeedURL      = errors.New("federation: invalid seed URL")
	ErrFederationSeedURLScheme       = errors.New("federation: seed URL must use HTTPS scheme")
	ErrFederationLoadGatewayID      = errors.New("federation: failed to load gateway ID")
	ErrFederationWriteGatewayID      = errors.New("federation: failed to write gateway ID")
	ErrFederationGatewayIDEmpty      = errors.New("federation: gateway ID file is empty")
	ErrFederationReadPeerCert       = errors.New("federation: failed to read peer certificate")
	ErrFederationReadPeerKey        = errors.New("federation: failed to read peer key")
	ErrFederationReadPeerChain       = errors.New("federation: failed to read peer chain")
	ErrFederationParsePeerCert      = errors.New("federation: failed to parse peer certificate/key pair")
	ErrFederationCertExpiringSoon   = errors.New("federation: peer certificate is expiring soon")
	ErrFederationGeneratePeerKey    = errors.New("federation: failed to generate peer keypair")
	ErrFederationCreateCSR          = errors.New("federation: failed to create CSR")
	ErrFederationSubmitCSR          = errors.New("federation: failed to submit CSR to seed")
	ErrFederationCreatePeerDir      = errors.New("federation: failed to create peer directory")
	ErrFederationMarshalPrivateKey  = errors.New("federation: failed to marshal private key")
	ErrFederationWritePeerCert     = errors.New("federation: failed to write peer certificate")
	ErrFederationWritePeerKey       = errors.New("federation: failed to write peer key")
	ErrFederationWritePeerChain     = errors.New("federation: failed to write peer chain")
	ErrFederationLoadCertKeyPair    = errors.New("federation: failed to load certificate/key pair")
	ErrFederationHealthCheckClient  = errors.New("federation: health check: client not initialized")
	ErrFederationHealthCheckRequest = errors.New("federation: health check: failed to create request")
	ErrFederationHealthCheckFailed  = errors.New("federation: health check: request failed")
	ErrFederationHealthCheckStatus  = errors.New("federation: health check: unexpected status code")
	ErrFederationGenerateGatewayID  = errors.New("federation: failed to generate gateway ID")
)
