// Copyright (c) 2026 Lateralus Labs, LLC.
// Use of this source code is governed by the Business Source License
// included in the LICENSE file.
//
// As of the Change Date listed in the LICENSE file, this software is
// released under the Apache License, Version 2.0.

package constants

import "errors"

// Standard platform errors
var (
	ErrUserNotFound                 = errors.New("user not found")
	ErrNoPasskeysRegistered         = errors.New("no passkeys registered")
	ErrInvalidJSONBody              = errors.New("invalid JSON body")
	ErrUserIDRequired               = errors.New("user_id required")
	ErrMethodNotAllowed             = errors.New("method not allowed")
	ErrForbidden                    = errors.New("forbidden")
	ErrInternal                     = errors.New("internal error")
	ErrNotFound                     = errors.New("not found")
	ErrAlreadyExists                = errors.New("already exists")
	ErrConstraintViolation          = errors.New("constraint violation")
	ErrDatabaseLocked               = errors.New("database is locked")
	ErrServiceUnavailable           = errors.New("service unavailable")
	ErrDatabaseReplay               = errors.New("database replay detected")
	ErrDuplicateColumn              = errors.New("duplicate column name")
	ErrProcessKilled                = errors.New("process killed")
	ErrTrustBundleStale             = errors.New("trust bundle stale")
	ErrKeyNotFound                  = errors.New("key not found")
	ErrExpired                      = errors.New("expired")
	ErrAgentNotFound                = errors.New("agent not found")
	ErrAgentNotInPath               = errors.New("agent binary not found in PATH")
	ErrAgentNotSupported            = errors.New("agent auto-launch not supported")
	ErrToolInterceptionVerification = errors.New("tool interception verification failed")
	ErrEndpointRequired             = errors.New("endpoint required")
	ErrGatewayURLRequired           = errors.New("gateway URL is required")
	ErrConfigLoadFailed             = errors.New("config load failed")
	ErrFileServiceInit              = errors.New("file service initialization failed")
	ErrCSRGenerationFailed          = errors.New("CSR generation failed")
	ErrEnrollmentFailed             = errors.New("enrollment failed")
	ErrMissingCertificate           = errors.New("missing certificate")
	ErrDirCreateFailed              = errors.New("directory creation failed")
	ErrPKIDirRequired               = errors.New("PKI directory required")
	ErrCertSaveFailed               = errors.New("certificate save failed")
	ErrChainSaveFailed              = errors.New("certificate chain save failed")
	ErrTrustSaveFailed              = errors.New("trust bundle save failed")
	ErrValidationFailed             = errors.New("security validation failed")
	ErrPEMDecodeFailed              = errors.New("failed to decode PEM block")
	ErrInvalidPEMType               = errors.New("invalid PEM block type")
	ErrPEMExtraData                 = errors.New("extra data after PEM block")
	ErrHTTPStatusError              = errors.New("HTTP status error")
	ErrEmptyTrustBundle             = errors.New("trust bundle is empty")
	ErrCAParseFailed                = errors.New("failed to parse CA certificates")
	ErrMissingRequiredField         = errors.New("missing required field")
	ErrInvalidLogLevel              = errors.New("invalid log level")

	// Keystore errors
	ErrKeyStoreKeyNotFound        = errors.New("master key not found in OS key store")
	ErrKeyStoreLocked             = errors.New("OS key store is locked/unavailable")
	ErrInvalidCiphertext          = errors.New("invalid ciphertext or authentication failed")
	ErrOSNotSupported             = errors.New("OS not supported for OS-native key store")
	ErrKeyStoreSecurityNotFound   = errors.New("keychain: security command not found")
	ErrKeyStoreRetrieveFailed     = errors.New("keychain: retrieve master key failed")
	ErrKeyStoreDecodeFailed       = errors.New("keychain: decode base64 key failed")
	ErrKeyStoreStoreFailed        = errors.New("keychain: store master key failed")
	ErrKeyStoreDeleteFailed       = errors.New("keychain: delete master key failed")
	ErrKeyStoreInvalidKeyLength   = errors.New("master key has invalid length")
	ErrKeyStoreGenerateFailed     = errors.New("failed to generate master key")
	ErrKeyStoreCipherCreate       = errors.New("failed to create AES cipher")
	ErrKeyStoreGCMCreate          = errors.New("failed to create GCM mode")
	ErrKeyStoreNonceGenerate      = errors.New("failed to generate nonce")
	ErrKeyStoreUnsupportedVersion = errors.New("unsupported secret version")
	ErrKeyStoreMarshalFailed      = errors.New("failed to marshal encrypted secret")
	ErrKeyStoreWriteFailed        = errors.New("failed to write encrypted secret")
	ErrKeyStoreRenameFailed       = errors.New("failed to atomic rename")
	ErrKeyStoreReadFailed         = errors.New("failed to read encrypted secret")
	ErrKeyStoreUnmarshalFailed    = errors.New("failed to unmarshal encrypted secret")
	ErrKeyStoreDecodeBase64       = errors.New("failed to decode base64 ciphertext")
	ErrKeyStoreDeleteSecret       = errors.New("failed to delete secret")
	ErrKeyStoreReadDir            = errors.New("failed to read secrets directory")
	ErrKeyStoreDeleteFile         = errors.New("failed to delete secret file")
	ErrKeyStoreChmodDir           = errors.New("failed to chmod secrets directory")
	ErrKeyStoreChmodFile          = errors.New("failed to chmod secret file")
	ErrKeyStorePurgeFailed        = errors.New("purge failed with one or more errors")

	// Ledger errors
	ErrLedgerDisabled       = errors.New("ledger is disabled")
	ErrLedgerConfigRequired = errors.New("ledger config is required")
	ErrLedgerVaultRequired  = errors.New("ledger encryption vault is required")

	// Ledger status messages
	LedgerStatusFileDeleted = "file deleted"

	// CLI approval errors
	ErrKeyReadFailed            = errors.New("failed to read CLI private key")
	ErrKeyWriteFailed           = errors.New("failed to write CLI private key")
	ErrKeyParseFailed           = errors.New("failed to parse private key")
	ErrInvalidKeyType           = errors.New("private key is not Ed25519")
	ErrCertReadFailed           = errors.New("failed to read CLI certificate")
	ErrCertParseFailed          = errors.New("failed to parse certificate")
	ErrRequestMarshalFailed     = errors.New("failed to marshal request")
	ErrTransactionApproveFailed = errors.New("failed to approve transaction")
	ErrResponseParseFailed      = errors.New("failed to parse response")
	ErrJSONMarshalFailed        = errors.New("failed to marshal JSON")

	// Notary errors
	ErrTransactionExpired = errors.New("transaction approval expired")

	// CLI authentication errors
	ErrNotAuthenticated              = errors.New("not authenticated")
	ErrNotEnrolled                   = errors.New("not enrolled")
	ErrGatewayNotReachable           = errors.New("gateway not reachable")
	ErrFailedToLoadCredentials       = errors.New("failed to load credentials")
	ErrFailedToLoadClientCertificate = errors.New("failed to load client certificate")
	ErrIncompleteCredentialPair      = errors.New("certificate and key must be supplied together")
	ErrFailedToReadTrustBundle       = errors.New("failed to read trust bundle")
	ErrFailedToParseTrustBundle      = errors.New("failed to parse trust bundle")
	ErrFailedToParsePaths            = errors.New("failed to parse paths.json")

	// HTTP client errors
	ErrHTTPRequestCreateFailed  = errors.New("failed to create HTTP request")
	ErrHTTPRequestExecuteFailed = errors.New("failed to execute HTTP request")
	ErrHTTPResponseReadFailed   = errors.New("failed to read HTTP response")
	ErrHTTPRequestMarshalFailed = errors.New("failed to marshal request body")
	ErrInvalidJSONResponse      = errors.New("invalid JSON response")

	// Process manager errors
	ErrProcessStartFailed      = errors.New("process start failed")
	ErrProcessStopFailed       = errors.New("process stop failed")
	ErrProcessFindFailed       = errors.New("failed to find process")
	ErrPortUnavailable         = errors.New("port unavailable")
	ErrInvalidPosture          = errors.New("invalid posture")
	ErrPostureRequired         = errors.New("posture required: operator has no posture of its own and received none from the gateway")
	ErrPIDReadFailed           = errors.New("failed to read PID file")
	ErrPIDWriteFailed          = errors.New("failed to write PID file")
	ErrPostureReadFailed       = errors.New("failed to read posture file")
	ErrPostureWriteFailed      = errors.New("failed to write posture file")
	ErrProcessInterrupted      = errors.New("process interrupted")
	ErrProcessSigKillTimeout   = errors.New("process did not exit after SIGKILL")
	ErrProcessForceKillTimeout = errors.New("process did not exit after force kill")
	ErrBinaryResolveFailed     = errors.New("failed to resolve operator binary")
	ErrBinaryCopyFailed        = errors.New("failed to copy operator binary")

	// File system errors
	ErrPathNotFound         = errors.New("path not found")
	ErrStatFailed           = errors.New("failed to stat path")
	ErrNotADirectory        = errors.New("path is not a directory")
	ErrPathValidation       = errors.New("invalid path")
	ErrDirectoryList        = errors.New("failed to list directory")
	ErrDirectoryRead        = errors.New("failed to read directory")
	ErrFileOpenFailed       = errors.New("failed to open file")
	ErrFileWriteFailed      = errors.New("file write failed")
	ErrFileReadFailed       = errors.New("file read failed")
	ErrFileRenameFailed     = errors.New("file rename failed")
	ErrFileRemoveFailed     = errors.New("file remove failed")
	ErrDirRemoveFailed      = errors.New("directory remove failed")
	ErrEnforcePermissions   = errors.New("failed to enforce permissions")
	ErrInvalidRegex         = errors.New("invalid regex pattern")
	ErrGrepFailed           = errors.New("failed to perform grep")
	ErrFileOwnershipExtract = errors.New("failed to extract syscall.Stat_t from FileInfo")

	// FsGrep error type constants
	ErrFsGrepValidation     = errors.New("fs_grep validation error")
	ErrFsGrepInvalidPattern = errors.New("fs_grep invalid pattern")
	ErrFsGrepExecution      = errors.New("fs_grep execution error")

	// PubSub client errors
	ErrClientClosed = errors.New("client is closed")

	// Execution service errors
	ErrExecutionServiceStopping = errors.New("execution service is stopping")
	ErrExecutionNotFound        = errors.New("execution not found")
	ErrEmptyCommand             = errors.New("empty command")
	ErrCommandLookup            = errors.New("command lookup failed")
	ErrShellRequired            = errors.New("shell required but not found")
	ErrCloudCLIBlocked          = errors.New("cloud CLI command blocked")

	// Execution error message constants
	ErrMessageExecutionTimeout  = "Command execution timed out"
	ErrMessagePermissionDenied  = "Permission denied: command is not executable"
	ErrMessageCommandNotFound   = "Command not found"
	ErrMessageCommandTerminated = "Command was terminated"

	// MCP service errors
	ErrMCPUnmarshalArguments = errors.New("unmarshal arguments")
	ErrMCPGetDiskUsage       = errors.New("get disk usage")
	ErrMCPStatFS             = errors.New("statfs")
	ErrMCPParseMounts        = errors.New("parse mounts")
	ErrMCPReadMounts         = errors.New("read /proc/mounts")
	ErrMCPHostPortRequired   = errors.New("host and port required")
	ErrMCPGetAbsolutePath    = errors.New("get absolute path")
	ErrMCPGetDiskFreeSpaceEx = errors.New("GetDiskFreeSpaceExW failed")

	// MCP registry errors
	ErrMCPSchemaNil               = errors.New("schema cannot be nil")
	ErrMCPSchemaMissingType       = errors.New("schema missing required 'type' field")
	ErrMCPSchemaInvalidType       = errors.New("schema 'type' must be 'object'")
	ErrMCPSchemaInvalidProperties = errors.New("schema 'properties' must be an object")
	ErrMCPSchemaInvalidRequired   = errors.New("schema 'required' must be an array")
	ErrMCPToolNil                 = errors.New("cannot register nil tool")
	ErrMCPToolNameEmpty           = errors.New("tool name cannot be empty")
	ErrMCPToolNameInvalid         = errors.New("invalid tool name: must contain only lowercase letters, digits, and underscores")
	ErrMCPToolAlreadyRegistered   = errors.New("tool is already registered")
	ErrMCPRegistryNil             = errors.New("registry cannot be nil")

	// MCP validation errors
	ErrMCPValidateSQLQueryEmpty                    = errors.New("SQL query cannot be empty")
	ErrMCPValidateSQLQueryTrailingSemicolon        = errors.New("SQL query must not end with semicolon")
	ErrMCPValidateURLInvalidScheme                 = errors.New("only http and https schemes are allowed")
	ErrMCPValidateURLMissingHost                   = errors.New("URL must have a host")
	ErrMCPValidateURLLoopbackAddress               = errors.New("localhost and loopback addresses are not allowed")
	ErrMCPValidateURLPrivateAddress                = errors.New("private and loopback IP addresses are not allowed")
	ErrMCPValidateProcNetInvalidProtocol           = errors.New("invalid protocol")
	ErrMCPValidatePathEmpty                        = errors.New("path cannot be empty")
	ErrMCPValidatePathWhitespace                   = errors.New("path must not contain leading/trailing whitespace")
	ErrMCPValidatePathParentDirRef                 = errors.New("path must not contain parent directory references (..)")
	ErrMCPValidatePathNullBytes                    = errors.New("path must not contain null bytes")
	ErrMCPValidateRefEmpty                         = errors.New("git reference cannot be empty")
	ErrMCPValidateRefWhitespace                    = errors.New("git reference must not contain leading/trailing whitespace")
	ErrMCPValidateRefNullBytes                     = errors.New("git reference must not contain null bytes")
	ErrMCPValidateRefDangerousChar                 = errors.New("git reference contains dangerous character")
	ErrMCPValidateRefAbsolutePath                  = errors.New("git reference must not be an absolute path")
	ErrMCPValidateRefInvalidChars                  = errors.New("git reference contains invalid characters")
	ErrMCPValidateK8sNameEmpty                     = errors.New("resource name cannot be empty")
	ErrMCPValidateK8sNameWhitespace                = errors.New("resource name must not contain leading/trailing whitespace")
	ErrMCPValidateK8sNameTooLong                   = errors.New("resource name must not exceed 253 characters")
	ErrMCPValidateK8sNameInvalidPattern            = errors.New("resource name must consist of lowercase alphanumeric characters, hyphens, or dots, and must start and end with an alphanumeric character")
	ErrMCPValidateK8sNameNullBytes                 = errors.New("resource name must not contain null bytes")
	ErrMCPValidateK8sNamespaceEmpty                = errors.New("namespace cannot be empty")
	ErrMCPValidateK8sNamespaceWhitespace           = errors.New("namespace must not contain leading/trailing whitespace")
	ErrMCPValidateK8sNamespaceTooLong              = errors.New("namespace must not exceed 63 characters")
	ErrMCPValidateK8sNamespaceInvalidPattern       = errors.New("namespace must consist of lowercase alphanumeric characters or hyphens, and must start and end with an alphanumeric character")
	ErrMCPValidateK8sNamespaceNullBytes            = errors.New("namespace must not contain null bytes")
	ErrMCPValidateCloudMetadataInvalidOperation    = errors.New("invalid operation")
	ErrMCPValidateCloudMetadataUnsupportedProvider = errors.New("unsupported provider")
	ErrMCPValidateHostnameEmpty                    = errors.New("hostname cannot be empty")
	ErrMCPValidateHostnameWhitespace               = errors.New("hostname must not contain leading/trailing whitespace")
	ErrMCPValidateHostnameNullBytes                = errors.New("hostname must not contain null bytes")
	ErrMCPValidateHostnameDangerousChar            = errors.New("hostname contains dangerous character")
	ErrMCPValidateHostnamesEmpty                   = errors.New("hostnames list cannot be empty")
	ErrMCPValidateOperatorArgsNullBytes            = errors.New("argument must not contain null bytes")
	ErrMCPValidateOperatorArgsDangerousChar        = errors.New("argument contains dangerous character")

	// MCP OOM detection errors
	ErrMCPGetWorkingDirectory = errors.New("get working directory")
	ErrMCPOpenLogFile         = errors.New("open log file")
	ErrMCPReadLogFile         = errors.New("read log file")
	ErrMCPMarshalOOMResult    = errors.New("marshal OOM result")

	// MCP SSH known hosts errors
	ErrMCPGetHomeDirectory = errors.New("get home directory")
	ErrMCPMarshalResult    = errors.New("marshal result")

	// MCP proc signal safe errors
	ErrMCPProcSignalRequired = errors.New("pid and signal required")

	// MCP git ops errors
	ErrMCPGitOpsUnsupportedOperation = errors.New("unsupported operation")
	ErrMCPGitOpsBinaryPathRequired   = errors.New("git binary path required")

	// MCP TLS cert inspect errors
	ErrMCPTLSCertInspectRequired = errors.New("either cert_path or host must be specified")

	// Run shell command errors
	ErrMCPRunShellCommandRequired              = errors.New("command is required")
	ErrMCPRunShellCommandSafetyRejected        = errors.New("command rejected by safety policy")
	ErrMCPRunShellCommandTimeoutExceeded       = errors.New("timeout cannot exceed 300 seconds")
	ErrMCPRunShellCommandMarshalResult         = errors.New("marshal result")
	ErrMCPRunShellCommandBlocked               = errors.New("command is blocked by safety policy")
	ErrMCPRunShellCommandDangerousPattern      = errors.New("command contains dangerous pattern")
	ErrMCPRunShellCommandShellInjection        = errors.New("command contains shell injection pattern")
	ErrMCPRunShellCommandPathTraversal         = errors.New("working directory contains path traversal")
	ErrMCPRunShellCommandAbsolutePathRequired  = errors.New("working directory must be an absolute path")
	ErrMCPRunShellCommandDirNotAccessible      = errors.New("working directory does not exist or is not accessible")
	ErrMCPRunShellCommandNotDirectory          = errors.New("working directory is not a directory")
	ErrMCPRunShellCommandShellMetacharacter    = errors.New("command contains shell metacharacter which is not allowed for SSH execution")
	ErrMCPRunShellCommandArgMetacharacter      = errors.New("argument contains shell metacharacter which is not allowed for SSH execution")
	ErrMCPRunShellCommandDirMetacharacter      = errors.New("working directory contains shell metacharacter which is not allowed for SSH execution")
	ErrMCPRunShellCommandResolveHost           = errors.New("resolve host")
	ErrMCPRunShellCommandHostnameResolveFailed = errors.New("failed to resolve hostname")
	ErrMCPRunShellCommandBuildAuth             = errors.New("build auth methods")
	ErrMCPRunShellCommandNoAuth                = errors.New("no SSH auth methods available")
	ErrMCPRunShellCommandHostKeyVerification   = errors.New("host key verification failed")
	ErrMCPRunShellCommandSSHDial               = errors.New("SSH dial failed")
	ErrMCPRunShellCommandSSHSession            = errors.New("SSH session creation failed")
	ErrMCPRunShellCommandTimedOut              = errors.New("command timed out")

	// Network identity detection errors
	ErrNetworkDetectInterfaces    = errors.New("failed to get network interfaces")
	ErrNetworkOpenHostsFile       = errors.New("failed to open hosts file")
	ErrNetworkScanHostsFile       = errors.New("error scanning hosts file")
	ErrNetworkDetectMDNS          = errors.New("detect mDNS names")
	ErrNetworkDetectHostnames     = errors.New("detect hostnames")
	ErrNetworkDetectIPs           = errors.New("detect IPs")
	ErrNetworkDetectHostsAliases  = errors.New("detect hosts file aliases")
	ErrNetworkDetectDNSPTR        = errors.New("detect DNS PTR records")
	ErrNetworkDetectSSHKnownHosts = errors.New("detect SSH known hosts")
	ErrNetworkDetectWindows       = errors.New("detect Windows identity")
	ErrNetworkGetHostname         = errors.New("get hostname")
	ErrNetworkGetSysteminfo       = errors.New("get systeminfo")

	// System utils errors
	ErrSystemUtilsInvalidProcStatFormat = errors.New("invalid /proc/stat format")
	ErrSystemUtilsInvalidCPULineFormat  = errors.New("invalid CPU line format")

	// Audit service errors
	ErrAuditUnmarshalUserMsg      = errors.New("failed to unmarshal user message payload")
	ErrAuditUnmarshalAIMsg        = errors.New("failed to unmarshal AI message payload")
	ErrAuditUnmarshalDirectCmd    = errors.New("failed to unmarshal direct command payload")
	ErrAuditUnmarshalDirectResult = errors.New("failed to unmarshal direct command result payload")
	ErrAuditRecordUserMsg         = errors.New("failed to record user message")
	ErrAuditRecordAIMsg           = errors.New("failed to record AI message")
	ErrAuditRecordDirectCmd       = errors.New("failed to record direct command")
	ErrAuditRecordDirectResult    = errors.New("failed to record direct command result")

	// Audit store errors
	ErrAuditEventNil                      = errors.New("AUDIT_EVENT_INVALID: event required")
	ErrAuditSessionMissing                = errors.New("AUDIT_SESSION_MISSING: operator_session_id required")
	ErrAuditSessionUnknown                = errors.New("AUDIT_SESSION_UNKNOWN: operator_session_id must reference a pre-created session")
	ErrAuditStoreEncryptionVaultRequired  = errors.New("EncryptionVault is required for audit store")
	ErrAuditStoreBootstrapFailed          = errors.New("audit store bootstrap failed")
	ErrAuditStoreCreateDirFailed          = errors.New("failed to create directory structure")
	ErrAuditStoreNotWritable              = errors.New("FATAL: storage not writable (zero tolerance for data loss risk)")
	ErrAuditStoreInitDBFailed             = errors.New("failed to initialize database")
	ErrAuditStoreCreateDirPathFailed      = errors.New("failed to create directory")
	ErrAuditStoreCannotWrite              = errors.New("cannot write to data directory")
	ErrAuditStoreOpenDBFailed             = errors.New("failed to open database")
	ErrAuditStoreInitSchemaFailed         = errors.New("failed to initialize schema")
	ErrAuditStoreCreateSessionFailed      = errors.New("failed to create Operator session")
	ErrAuditStoreDisabled                 = errors.New("audit store is disabled")
	ErrAuditStoreGetSessionFailed         = errors.New("failed to get session")
	ErrAuditStoreVerifySessionFailed      = errors.New("failed to verify audit session")
	ErrAuditStoreDBNotInitialized         = errors.New("audit store: database not initialized")
	ErrAuditStorePrepareBatchFailed       = errors.New("failed to prepare batch statement")
	ErrAuditStoreEncryptContentFailed     = errors.New("failed to encrypt content_text")
	ErrAuditStoreEncryptStdoutFailed      = errors.New("failed to encrypt stdout")
	ErrAuditStoreEncryptStderrFailed      = errors.New("failed to encrypt stderr")
	ErrAuditStoreExecuteBatchFailed       = errors.New("failed to execute batch statement")
	ErrAuditStoreRecordEventFailed        = errors.New("failed to record event")
	ErrAuditStoreRecordReceiptFailed      = errors.New("failed to record action receipt")
	ErrAuditStoreGetReceiptFailed         = errors.New("failed to get action receipt")
	ErrAuditStoreQueryReceiptsFailed      = errors.New("failed to query action receipts")
	ErrAuditStoreQueryReceiptsSinceFailed = errors.New("failed to query action receipts since timestamp")
	ErrAuditStoreQueryEventsFailed        = errors.New("failed to query events")
	ErrAuditStoreRecordFileMutationFailed = errors.New("failed to record file mutation")
	ErrAuditStoreQueryFileMutationsFailed = errors.New("failed to query file mutations")
	ErrAuditStoreEncryptFailed            = errors.New("failed to encrypt content")
	ErrAuditStoreVaultLocked              = errors.New("vault is locked, cannot decrypt content")
	ErrAuditStoreDecryptFailed            = errors.New("failed to decrypt content")
	ErrAuditStoreRequired                 = errors.New("audit store is required: AuditStore must be wired at construction, not defaulted to a no-op")

	// Execution vault errors
	ErrExecutionVaultVaultLocked   = errors.New("execution vault: vault is locked, cannot encrypt/decrypt content")
	ErrExecutionVaultEncryptFailed = errors.New("execution vault: failed to encrypt content")
	ErrExecutionVaultDecryptFailed = errors.New("execution vault: failed to decrypt content")

	// PubSub service errors
	ErrPubSubEmptyPayload                 = errors.New("empty payload")
	ErrPayloadExceedsLimit                = errors.New("payload exceeds maximum size limit")
	ErrPubSubTransactionVerifier          = errors.New("transaction verifier not configured")
	ErrPubSubActuator                     = errors.New("actuator not configured")
	ErrPubSubL4Warden                     = errors.New("L4Warden not configured")
	ErrPubSubMCPGateway                   = errors.New("MCP gateway not configured")
	ErrPubSubMCPMissingToolName           = errors.New("MCP call missing tool_name")
	ErrPubSubA2AGateway                   = errors.New("A2A gateway not configured")
	ErrPubSubA2AMissingSkillName          = errors.New("A2A call missing skill_name")
	ErrPubSubActuatorOrAuditStore         = errors.New("actuator or ConsoleAuditStore not configured")
	ErrPubSubResultsPublisher             = errors.New("results publisher not configured")
	ErrPubSubPublishExecutionResult       = errors.New("failed to publish execution result")
	ErrPubSubPublishCancellationResult    = errors.New("failed to publish cancellation result")
	ErrPubSubPublishFileEditResult        = errors.New("failed to publish file edit result")
	ErrPubSubPublishFsListResult          = errors.New("failed to publish fs list result")
	ErrPubSubPublishFsGrepResult          = errors.New("failed to publish fs grep result")
	ErrPubSubBuildStatusEnvelope          = errors.New("failed to build Universal status envelope")
	ErrPubSubPublishStatusUpdate          = errors.New("failed to publish Universal status update")
	ErrPubSubBuildHeartbeatEnvelope       = errors.New("failed to build heartbeat envelope")
	ErrPubSubMarshalHeartbeatEnvelope     = errors.New("failed to marshal heartbeat envelope")
	ErrPubSubPublishHeartbeat             = errors.New("failed to send heartbeat")
	ErrPubSubMarshalEnvelope              = errors.New("failed to marshal Governance Envelope")
	ErrPubSubBuildResultEnvelope          = errors.New("failed to build Governance Envelope")
	ErrPubSubCertificateMissingOperatorID = errors.New("certificate missing Operator identity")
	ErrPubSubInvalidChannelFormat         = errors.New("invalid channel format")

	// Scrubbing service errors
	ErrScrubbingInvalidPattern        = errors.New("invalid custom scrub pattern")
	ErrScrubbingRegexTimeout          = errors.New("regex compilation timeout")
	ErrScrubbingTokenPersist          = errors.New("failed to persist token to local store")
	ErrScrubbingTokenLoad             = errors.New("failed to load persisted tokens from TokenStore")
	ErrScrubbingTokenKeyFormat        = errors.New("invalid token key format")
	ErrScrubbingTokenSequence         = errors.New("failed to parse token sequence")
	ErrScrubbingTokenStoreUnavailable = errors.New("token persistence required but TokenStore unavailable")

	// Gateway service errors
	ErrGatewayToolNameRequired                 = errors.New("tool name required")
	ErrGatewayInvalidToolArguments             = errors.New("invalid tool arguments: must be a valid JSON object")
	ErrGatewayFieldPathRegistryNotInit         = errors.New("field path registry not initialized")
	ErrGatewayDatabaseServiceNotConfigured     = errors.New("database service not configured")
	ErrGatewayCollectionRequired               = errors.New("collection required")
	ErrGatewayDocumentIDRequired               = errors.New("document_id required")
	ErrGatewayFieldPathRequired                = errors.New("field_path required")
	ErrGatewayOperatorSessionIDRequired        = errors.New("operator_session_id required")
	ErrGatewayOperatorSessionInvalid           = errors.New("operator session is invalid or expired")
	ErrGatewayURIRequired                      = errors.New("uri required")
	ErrGatewayNameRequired                     = errors.New("name required")
	ErrGatewaySkillNameRequired                = errors.New("skill_name required")
	ErrGatewayNoDownstreamConfigured           = errors.New("no downstream MCP server configured")
	ErrGatewayDownstreamUnavailable            = errors.New("downstream MCP server is temporarily unavailable (circuit open)")
	ErrGatewayNoA2ADownstreamConfigured        = errors.New("no downstream A2A server configured")
	ErrGatewayNotReady                         = errors.New("g8e Gateway not ready")
	ErrGatewayL3ProofRequired                  = errors.New("L3 proof required")
	ErrGatewayUserIDRequired                   = errors.New("user_id required")
	ErrGatewayInvalidPosture                   = errors.New("invalid posture")
	ErrGatewayForbiddenPattern                 = errors.New("forbidden pattern detected")
	ErrGatewayDownstreamHTTPError              = errors.New("downstream server returned HTTP error")
	ErrGatewayMCPError                         = errors.New("MCP error")
	ErrGatewayA2AError                         = errors.New("A2A error")
	ErrGatewayAlreadyRunning                   = errors.New("gateway service already running")
	ErrGatewayShutdownTimeout                  = errors.New("shutdown timeout exceeded")
	ErrGatewaySSERouteUserIDRequired           = errors.New("sse route requires user_id")
	ErrGatewaySSERouteSessionRequired          = errors.New("sse route requires exactly one of web_session_id or cli_session_id")
	ErrGatewaySSERouteSessionMutuallyExclusive = errors.New("sse route session is mutually-exclusive: set exactly one of web_session_id or cli_session_id")

	// Gateway approval errors
	ErrGatewayUnauthorized                = errors.New("unauthorized")
	ErrGatewayTransactionNotFound         = errors.New("transaction not found")
	ErrGatewayTransactionBelongsToAnother = errors.New("transaction belongs to another user")
	ErrGatewayTransactionHashRequired     = errors.New("transaction hash required")

	// MCP native handler errors
	ErrMCPNativeToolRegistration = errors.New("native tool registration failed")
	ErrMCPNativeToolUnknown      = errors.New("unknown native tool")
	ErrMCPParseSocketPort        = errors.New("parse socket port")
	ErrMCPParseSocketIPOctet     = errors.New("parse socket IP octet")

	// SQLite validation errors
	ErrSQLiteValidateEmptyIdentifier = errors.New("empty identifier")
	ErrSQLiteValidateInvalidPattern  = errors.New("invalid identifier pattern")

	// SQLite utility errors
	ErrSQLitePruneFailed = errors.New("prune function failed")

	// SQLite compression errors
	ErrSQLiteCompressGzipWrite  = errors.New("gzip write failed")
	ErrSQLiteCompressGzipClose  = errors.New("gzip close failed")
	ErrSQLiteDecompressGzipInit = errors.New("gzip reader init failed")
	ErrSQLiteDecompressGzipRead = errors.New("gzip read failed")

	// Passkey bootstrap errors
	ErrPasskeyRegistrationTimedOut    = errors.New("passkey registration timed out")
	ErrPasskeyRegistrationFailed      = errors.New("passkey registration failed")
	ErrPasskeyStatusUnauthorized      = errors.New("passkey status endpoint returned unauthorized")
	ErrPasskeySSEStreamClosed         = errors.New("SSE stream closed unexpectedly")
	ErrPasskeySSEDependenciesRequired = errors.New("passkey orchestrator: SSEStore and PubSub are required at construction, not nil")

	// Enrollment token errors
	ErrEnrollmentTokenGenerationFailed  = errors.New("enrollment token generation failed")
	ErrEnrollmentTokenPersistenceFailed = errors.New("enrollment token persistence failed")
	ErrEnrollmentTokenInvalid           = errors.New("enrollment token is invalid")
	ErrEnrollmentTokenExpired           = errors.New("enrollment token has expired")
	ErrEnrollmentTokenConsumed          = errors.New("enrollment token has already been consumed")

	// CLI recovery errors
	ErrCLIRecoveryRequestFailed   = errors.New("CLI recovery request failed")
	ErrCLIRecoveryRequestNotFound = errors.New("CLI recovery request not found")
	ErrCLIRecoveryRequestExpired  = errors.New("CLI recovery request has expired")
	ErrCLIRecoveryRequestConsumed = errors.New("CLI recovery request has already been consumed")
	ErrCLIRecoveryRequestDenied   = errors.New("CLI recovery request was denied")
	ErrCLIRecoveryProofInvalid    = errors.New("CLI recovery proof-of-possession signature is invalid")
	ErrCLIRecoveryCSRMismatch     = errors.New("CLI recovery CSR does not match the original request")
	ErrCLIRecoveryNotApproved     = errors.New("CLI recovery request has not been approved")

	ErrPlatformEnrollmentRequiresActivation   = errors.New("platform enrollment requires an activated gateway")
	ErrPlatformEnrollmentInvalidComponent     = errors.New("invalid platform component kind")
	ErrPlatformEnrollmentInstanceIDRequired   = errors.New("platform enrollment instance_id is required")
	ErrPlatformEnrollmentInvalidInstanceID    = errors.New("invalid platform enrollment instance_id")
	ErrPlatformEnrollmentHostnameRequired     = errors.New("platform enrollment hostname is required")
	ErrPlatformEnrollmentInvalidHostname      = errors.New("invalid platform enrollment hostname")
	ErrPlatformEnrollmentFingerprintRequired  = errors.New("platform enrollment system_fingerprint is required")
	ErrPlatformEnrollmentInvalidPayload       = errors.New("platform enrollment payload does not match component kind")
	ErrPlatformEnrollmentInvalidCSR           = errors.New("invalid platform enrollment CSR")
	ErrPlatformEnrollmentUnsupportedKey       = errors.New("platform enrollment CSR must use a P-256 key")
	ErrPlatformEnrollmentDuplicateKey         = errors.New("platform enrollment CSRs must use distinct keys")
	ErrPlatformEnrollmentRequestIDRequired    = errors.New("platform enrollment request_id is required")
	ErrPlatformEnrollmentTokenRequired        = errors.New("platform enrollment token is required")
	ErrPlatformEnrollmentInvalidToken         = errors.New("invalid platform enrollment token")
	ErrPlatformEnrollmentRequestNotFound      = errors.New("platform enrollment request not found")
	ErrPlatformEnrollmentRequestExpired       = errors.New("platform enrollment request has expired")
	ErrPlatformEnrollmentRequestDenied        = errors.New("platform enrollment request was denied")
	ErrPlatformEnrollmentNotApproved          = errors.New("platform enrollment request has not been approved")
	ErrPlatformEnrollmentAlreadyDecided       = errors.New("platform enrollment request has already been decided")
	ErrPlatformEnrollmentIssuanceInProgress   = errors.New("platform enrollment issuance is in progress")
	ErrPlatformEnrollmentInvalidState         = errors.New("invalid platform enrollment state transition")
	ErrPlatformEnrollmentInvalidDecision      = errors.New("invalid platform enrollment decision")
	ErrPlatformEnrollmentReasonTooLong        = errors.New("platform enrollment decision reason is too long")
	ErrPlatformEnrollmentProofRequired        = errors.New("platform enrollment proof of possession is required")
	ErrPlatformEnrollmentProofInvalid         = errors.New("platform enrollment proof of possession is invalid")
	ErrPlatformEnrollmentCSRMismatch          = errors.New("platform enrollment CSR fingerprint mismatch")
	ErrPlatformEnrollmentStoredRequestInvalid = errors.New("stored platform enrollment request is invalid")
	ErrPlatformEnrollmentQuotaExceeded        = errors.New("platform enrollment request quota exceeded")
	ErrPlatformEnrollmentRateLimited          = errors.New("platform enrollment request rate limited")
	ErrPlatformEnrollmentGovernanceRejected   = errors.New("platform enrollment governance verification rejected")
	ErrPlatformEnrollmentPersistenceFailed    = errors.New("platform enrollment persistence failed")
	ErrPlatformEnrollmentIssuanceFailed       = errors.New("platform enrollment issuance failed")
	ErrPlatformEnrollmentReservedIdentity     = errors.New("platform identity requires owner-approved enrollment")

	ErrCLIRotationFailed            = errors.New("CLI rotation failed")
	ErrCLIRotationCSRRequired       = errors.New("cli_csr_pem is required for rotation")
	ErrCLISessionNotFound           = errors.New("CLI session not found")
	ErrCLISessionAlreadyDeactivated = errors.New("CLI session already deactivated")

	// Passkey credential validation errors
	ErrPasskeyCredentialInvalidID          = errors.New("passkey credential ID is empty")
	ErrPasskeyCredentialIDTooLong          = errors.New("passkey credential ID exceeds 1024 bytes")
	ErrPasskeyCredentialInvalidPublicKey   = errors.New("passkey credential public key is not a valid CBOR-encoded COSE key")
	ErrPasskeyCredentialInvalidAttestation = errors.New("passkey credential attestation type is not recognized")
	ErrPasskeyCredentialInvalidTimestamp   = errors.New("passkey credential created_at_unix_ms is zero")

	// Windows-specific errors
	ErrWindowsSpecificEnrollment = errors.New("windows-specific enrollment is only available on Windows")
	ErrWindowsCertStoreImport    = errors.New("windows cert store import is only available on Windows")
	ErrWindowsCertStoreTrust     = errors.New("windows cert store trust is only available on Windows")
	ErrWindowsTempDirCreate      = errors.New("failed to create Windows temp directory")
	ErrWindowsCertWriteFailed    = errors.New("failed to write certificate to temp file")
	ErrWindowsPowerShellImport   = errors.New("failed to import certificate via PowerShell")
	ErrWindowsPowerShellTrust    = errors.New("failed to trust Root CA via PowerShell")
	ErrWindowsRegistryOpenKey    = errors.New("failed to open registry key")
	ErrWindowsRegistryReadValue  = errors.New("failed to read registry value")

	// System trust installation errors
	ErrSystemTrustInvalidAnchor      = errors.New("invalid or missing trust anchor")
	ErrSystemTrustInstallFailed      = errors.New("system trust installation failed")
	ErrSystemTrustElevationRequired  = errors.New("elevated privileges required for system trust installation")
	ErrSystemTrustUnsupported        = errors.New("system trust installation unsupported on this platform")
	ErrSystemTrustDelegated          = errors.New("browser trust explicitly delegated to the administrator")
	ErrSystemTrustNoChainToAnchor    = errors.New("no certificate in the bundle chains to the identified root anchor")
	ErrSystemTrustStaleRemovalDenied = errors.New("user declined removal of stale trust anchors")
	ErrBrowserRestartDeclined        = errors.New("user declined to restart browser before passkey ceremony")

	// Data command errors
	ErrCollectionRequired         = errors.New("collection required")
	ErrOperatorSessionIDRequired  = errors.New("operator session id required")
	ErrAuditVaultDatabaseNotFound = errors.New("audit vault database not found")
	ErrAuditQueryFailed           = errors.New("failed to query audit events")
	ErrAuditScanFailed            = errors.New("failed to scan audit row")
	ErrSQLDatabaseOpenFailed      = errors.New("failed to open SQL database")
	ErrSQLQueryFailed             = errors.New("failed to execute SQL query")

	// Test command errors
	ErrGatewayNotRunning         = errors.New("gateway not running")
	ErrChaosTestDatabaseNotFound = errors.New("chaos test database not found")
	ErrUnitTestsFailed           = errors.New("unit tests failed")
	ErrIntegrationTestsFailed    = errors.New("integration tests failed")
	ErrE2ETestsFailed            = errors.New("e2e tests failed")
	ErrCoverageTestsFailed       = errors.New("coverage tests failed")
	ErrLintingFailed             = errors.New("linting failed")

	// Vault command errors
	ErrVaultAlreadyInitialized = errors.New("vault already initialized")
	ErrVaultNotInitialized     = errors.New("vault not initialized")
	ErrVaultKeyReadFailed      = errors.New("failed to read vault key file")
	ErrVaultKeyDecodeFailed    = errors.New("failed to decode vault key")
	ErrVaultKeyInvalidSize     = errors.New("invalid vault key size")
	ErrVaultKeyGenerateFailed  = errors.New("failed to generate vault key")
	ErrVaultHeaderCreateFailed = errors.New("failed to create vault header")
	ErrVaultHeaderSaveFailed   = errors.New("failed to save vault header")
	ErrVaultCreateFailed       = errors.New("failed to create vault")
	ErrVaultUnlockFailed       = errors.New("failed to unlock vault")
	ErrVaultRekeyFailed        = errors.New("failed to rekey vault")
	ErrVaultResetFailed        = errors.New("failed to reset vault")
	ErrVaultKeyWriteFailed     = errors.New("failed to write vault key")
	ErrVaultStoreExecution     = errors.New("failed to store execution in vault")
	ErrVaultStoreFileDiff      = errors.New("failed to store file diff in vault")
	ErrVaultLocked             = errors.New("vault is locked")
	ErrVaultAlreadyOpen        = errors.New("vault is already unlocked")
	ErrVaultConfigRequired     = errors.New("vault config is required")
	ErrVaultDataDirRequired    = errors.New("vault data directory is required")
	ErrVaultResetConfirmation  = errors.New("vault reset requires explicit confirmation")
	ErrVaultInvalidPrivateKey  = errors.New("invalid private key for this vault")
	ErrVaultCiphertextTooShort = errors.New("ciphertext too short")
	ErrVaultStdinReadFailed    = errors.New("failed to read from stdin")

	// Vault crypto errors
	ErrVaultInvalidKeySize      = errors.New("invalid key size: must be 32 bytes")
	ErrVaultInvalidNonceSize    = errors.New("invalid nonce size: must be 12 bytes")
	ErrVaultDecryptionFailed    = errors.New("decryption failed: authentication error")
	ErrVaultKeyWrapFailed       = errors.New("key wrap failed")
	ErrVaultKeyUnwrapFailed     = errors.New("key unwrap failed: integrity check failed")
	ErrVaultInvalidWrappedKey   = errors.New("invalid wrapped key size")
	ErrVaultInvalidPlaintextKey = errors.New("plaintext key must be multiple of 8 bytes")
	ErrVaultPrivateKeyEmpty     = errors.New("private key cannot be empty")

	// Vault header errors
	ErrVaultHeaderNotFound      = errors.New("vault header not found")
	ErrVaultHeaderCorrupted     = errors.New("vault header is corrupted")
	ErrVaultHeaderVersionUnsup  = errors.New("unsupported vault header version")
	ErrVaultKeyFingerprintMatch = errors.New("private key fingerprint mismatch")
	ErrVaultAlreadyExists       = errors.New("vault already exists")

	// Config errors
	ErrConfigHTTPPortZero        = errors.New("httpPort cannot be 0 in production")
	ErrConfigHTTPSPortZero       = errors.New("httpsPort cannot be 0 in production")
	ErrConfigPortsMustDiffer     = errors.New("httpPort and httpsPort must be different")
	ErrConfigInvalidWorkingDir   = errors.New("invalid working directory")
	ErrConfigConsensusIDRequired = errors.New("consensus posture requires --consensus-id")
	ErrConfigConsensusQuorumLow  = errors.New("consensus posture requires consensus quorum >= 1")

	// Operator main initialization errors
	ErrPathsInitFailed        = errors.New("failed to initialize paths")
	ErrWorkingDirFailed       = errors.New("failed to determine working directory")
	ErrUnrecognizedCommand    = errors.New("unrecognized command or flag")
	ErrMutuallyExclusiveFlags = errors.New("only one of --doctrine, --consensus, or --notary may be specified")
	ErrFetchTrustBundle       = errors.New("failed to fetch trust bundle from Operator")
	ErrNoTrustBundle          = errors.New("no trust bundle available")
	ErrPrivateKeyRequired     = errors.New("private key is required")
	ErrClientCertRequired     = errors.New("client certificate is required")
	ErrReadClientCert         = errors.New("failed to read client certificate")
	ErrReadPrivateKey         = errors.New("failed to read private key")
	ErrLoadCertKeyPair        = errors.New("failed to load client certificate/key pair")

	// JWKS errors
	ErrJWKSRequestCreate    = errors.New("jwks: failed to create request")
	ErrJWKSFetchKeys        = errors.New("jwks: failed to fetch keys")
	ErrJWKSUnexpectedStatus = errors.New("jwks: unexpected status code")
	ErrJWKSDecodeResponse   = errors.New("jwks: failed to decode response")
	ErrJWKSKeyNotFound      = errors.New("jwks: key not found")

	// JWT errors
	ErrJWTInvalidFormat    = errors.New("invalid JWT format")
	ErrJWTUnsupportedAlg   = errors.New("unsupported signing algorithm")
	ErrJWTMissingKid       = errors.New("missing kid in header")
	ErrJWTNotYetValid      = errors.New("token is not yet valid")
	ErrJWTIssuerMismatch   = errors.New("token issuer mismatch")
	ErrJWTAudienceMismatch = errors.New("token audience mismatch")

	// Bootstrap service errors
	ErrBootstrapTLSConfig                   = errors.New("bootstrap: failed to configure TLS")
	ErrBootstrapFingerprint                 = errors.New("bootstrap: failed to generate system fingerprint")
	ErrBootstrapAuth                        = errors.New("bootstrap: failed to authenticate")
	ErrBootstrapRequestMarshal              = errors.New("bootstrap: failed to marshal auth request")
	ErrIdentityBindingFailed                = errors.New("identity binding failed")
	ErrMTLSRequired                         = errors.New("mTLS client certificate required")
	ErrCertURISANMissing                    = errors.New("client certificate missing URI SAN")
	ErrURISANMismatch                       = errors.New("certificate URI SAN does not match envelope identity claims")
	ErrEnvelopeProcessorNotInit             = errors.New("envelope processor not initialized")
	ErrNilReceipt                           = errors.New("envelope processor returned nil receipt without error")
	ErrOperatorSessionIDMissing             = errors.New("operator_session_id required")
	ErrOperatorIDMissing                    = errors.New("operator_id required")
	ErrSourceComponentMissing               = errors.New("source_component required")
	ErrBootstrapRequestBuild                = errors.New("bootstrap: failed to build auth request")
	ErrBootstrapRequestExecute              = errors.New("bootstrap: authentication request failed")
	ErrBootstrapResponseRead                = errors.New("bootstrap: failed to read auth response")
	ErrBootstrapResponseClose               = errors.New("bootstrap: failed to close response body")
	ErrBootstrapResponseStatus              = errors.New("bootstrap: authentication failed with status")
	ErrBootstrapResponseDecode              = errors.New("bootstrap: failed to decode auth response")
	ErrBootstrapAuthFailed                  = errors.New("bootstrap: authentication failed")
	ErrBootstrapInitialSetupOnly            = errors.New("bootstrap only available for initial setup")
	ErrCLIEnrollmentAfterBootstrap          = errors.New("CLI enrollment only available after bootstrap")
	ErrCLICSRRequired                       = errors.New("cli_csr_pem is required")
	ErrFirstCredentialOnly                  = errors.New("first-credential registration only")
	ErrUserIDMismatch                       = errors.New("user_id mismatch")
	ErrCredentialIDRequired                 = errors.New("credential_id required")
	ErrCSRRequired                          = errors.New("csr_pem is required")
	ErrSystemFingerprintRequired            = errors.New("system_fingerprint is required")
	ErrHostnameRequired                     = errors.New("hostname is required")

	// App enrollment service errors
	ErrAppEnrollCSRRequired       = errors.New("csr_pem is required")
	ErrAppEnrollAppNameRequired   = errors.New("app_name is required")
	ErrAppEnrollAppTypeRequired   = errors.New("app_type is required")
	ErrAppEnrollInvalidAppType    = errors.New("invalid app_type")
	ErrAppEnrollInvalidAppName    = errors.New("app_name must contain only alphanumeric characters")
	ErrAppEnrollInvalidCSRPEM     = errors.New("invalid CSR PEM format")
	ErrAppEnrollParseCSR          = errors.New("failed to parse CSR")
	ErrAppEnrollCSRSignatureCheck = errors.New("CSR signature check failed")
	ErrAppEnrollSignCertificate   = errors.New("failed to sign certificate")
	ErrAppEnrollParseIssuedCert   = errors.New("failed to parse issued certificate")
	ErrAppEnrollNoURISAN          = errors.New("issued certificate has no URI SAN")
	ErrAppEnrollMarshalAppPolicy  = errors.New("failed to marshal app policy")
	ErrAppEnrollPersistAppPolicy  = errors.New("failed to persist app policy")
	ErrBootstrapNoConfig          = errors.New("bootstrap: no configuration returned from Auth Services")
	ErrBootstrapNoSessionID       = errors.New("bootstrap: no operator_session_id returned from Auth Services")
	ErrBootstrapCertParse         = errors.New("bootstrap: failed to parse per-operator cert+key")
	ErrBootstrapTLSConfigDI       = errors.New("bootstrap: failed to get base TLS config from DI")
	ErrBootstrapCertTrust         = errors.New("bootstrap: cert trust failure: per-operator mTLS cert invalid")

	// CLI L3 notary errors
	ErrCLIL3TransactionHashRequired       = errors.New("transaction_hash required for CLI L3 verification")
	ErrCLIL3CertFingerprintRequired       = errors.New("mtls_cert_fingerprint required for CLI L3 verification")
	ErrCLIL3InvalidFingerprintFormat      = errors.New("invalid mtls_cert_fingerprint format")
	ErrCLIL3UserInactive                  = errors.New("user is not active")
	ErrCLIL3SessionIDRequired             = errors.New("cli_session_id required for CLI L3 verification")
	ErrCLIL3SessionLoadFailed             = errors.New("failed to load CLI session")
	ErrCLIL3SessionNotFound               = errors.New("CLI session not found")
	ErrCLIL3SessionMarshalFailed          = errors.New("failed to marshal CLI session")
	ErrCLIL3SessionUnmarshalFailed        = errors.New("failed to unmarshal CLI session")
	ErrCLIL3SessionUserMismatch           = errors.New("CLI session user mismatch")
	ErrCLIL3FingerprintMismatch           = errors.New("certificate fingerprint mismatch")
	ErrCLIL3SessionInactive               = errors.New("CLI session is not active")
	ErrCLIL3SessionExpired                = errors.New("CLI session expired")
	ErrCLIL3CertRevocationCheckFailed     = errors.New("failed to check certificate revocation status")
	ErrCLIL3CertNil                       = errors.New("certificate is nil")
	ErrCLIL3CertExpired                   = errors.New("certificate expired")
	ErrCLIL3CertNotYetValid               = errors.New("certificate not yet valid")
	ErrCLIL3CertVerificationFailed        = errors.New("certificate verification failed")
	ErrCLIL3SPIFFESANMismatch             = errors.New("certificate SPIFFE URI SAN does not match CLI session")
	ErrCLIL3NoSessionIDInCert             = errors.New("no CLI session ID found in certificate SPIFFE URI SANs")
	ErrCLIL3NoUserIDInCert                = errors.New("no user ID found in certificate SPIFFE URI SANs")
	ErrCLIL3PKINotConfigured              = errors.New("PKI authority not configured")
	ErrCLIL3NoSPIFFEURI                   = errors.New("no SPIFFE URI found in certificate")
	ErrCLIL3GetSuspendedTransactionFailed = errors.New("failed to get suspended transaction")
	ErrCLIL3SignatureEncodingFailed       = errors.New("invalid signature encoding")
	ErrCLIL3SignatureVerificationFailed   = errors.New("cryptographic signature verification failed")
	ErrCLIL3PublicKeyMissing              = errors.New("approval public key missing")
	ErrCLIL3PublicKeyInvalid              = errors.New("invalid approval public key")
	ErrCLIL3SignatureRequired             = errors.New("cli_signature required for CLI L3 verification")
	ErrCLIL3SuspendedStoreNotConfigured   = errors.New("suspended transaction store not configured for CLI L3 verification")
	ErrCLIL3TransactionNotApproved        = errors.New("suspended transaction is not approved")
	ErrCLIL3ApprovalExpired               = errors.New("CLI L3 approval has expired")
	ErrCLIL3UserServiceNotConfigured      = errors.New("user service not configured for CLI L3 verification")
	ErrCLISessionDenied                   = errors.New("CLI session denied")
	ErrPasskeyProofRequired               = errors.New("passkey proof required for L3 authorization")

	// File edit service errors
	ErrFileEditUnsupportedOperation   = errors.New("unsupported file operation")
	ErrFileEditContentRequired        = errors.New("content is required for write operation")
	ErrFileEditOldContentRequired     = errors.New("old_content is required for replace operation")
	ErrFileEditNewContentRequired     = errors.New("new_content is required for replace operation")
	ErrFileEditInsertContentRequired  = errors.New("insert_content is required for insert operation")
	ErrFileEditInsertPositionRequired = errors.New("insert_position is required for insert operation")
	ErrFileEditLineRangeRequired      = errors.New("start_line and end_line are required for delete operation")
	ErrFileEditPatchContentRequired   = errors.New("patch_content is required for patch operation")
	ErrFileEditPatchNotImplemented    = errors.New("patch operation not yet implemented")

	// Response writer errors
	ErrResponseEncodeJSON               = errors.New("failed to encode JSON response")
	ErrResponseMarshalJSONRPCResult     = errors.New("failed to marshal JSON-RPC result")
	ErrResponseEncodeJSONRPC            = errors.New("failed to encode JSON-RPC response")
	ErrResponseEncodeJSONRPCError       = errors.New("failed to encode JSON-RPC error response")
	ErrFileEditFileTooLarge             = errors.New("file too large for operation")
	ErrFileEditOldContentNotFound       = errors.New("old_content not found in file")
	ErrFileEditInsertPositionOutOfRange = errors.New("insert position out of range")
	ErrFileEditInvalidLineRange         = errors.New("invalid line range")
	ErrFileEditCreateBackupFailed       = errors.New("failed to create backup")
	ErrFileEditOpenFileFailed           = errors.New("failed to open file")
	ErrFileEditReadFileFailed           = errors.New("failed to read file")
	ErrFileEditWriteFileFailed          = errors.New("failed to write file")
	ErrFileEditReadLinesFailed          = errors.New("failed to read file lines")

	// DB controller errors
	ErrDBControllerKeyRequired         = errors.New("key required")
	ErrDBControllerNamespaceRequired   = errors.New("namespace required")
	ErrDBControllerInvalidNamespace    = errors.New("invalid namespace")
	ErrDBControllerInvalidBlobID       = errors.New("invalid blob id")
	ErrDBControllerInvalidPath         = errors.New("invalid path")
	ErrDBControllerContentTypeRequired = errors.New("Content-Type header required")
	ErrDBControllerBodyReadFailed      = errors.New("failed to read body")
	ErrDBControllerChannelRequired     = errors.New("channel required")
	ErrDBControllerPatternRequired     = errors.New("pattern required")
	ErrDBControllerTTLRequired         = errors.New("ttl required and must be > 0")
	ErrDBControllerInvalidTTL          = errors.New("X-Blob-TTL must be a non-negative integer")
	ErrDBControllerBlobTooLarge        = errors.New("blob exceeds maximum size")
	ErrDBControllerBodyEmpty           = errors.New("body must not be empty")

	// Signer controller errors
	ErrSignerControllerBodyReadFailed  = errors.New("failed to read body")
	ErrSignerControllerInvalidSignerID = errors.New("invalid signer id")

	// Authorization errors
	ErrUnauthorizedNoIdentity       = errors.New("unauthorized: no identity present")
	ErrUnauthorizedAppNamespace     = errors.New("unauthorized: app can only write to its own namespace")
	ErrUnauthorizedOperatorNoUserID = errors.New("unauthorized: operator/CLI identity without user_id")
	ErrUnauthorizedUserNamespace    = errors.New("unauthorized: user can only write to their own namespace")
	ErrUnauthorizedUnknownIdentity  = errors.New("unauthorized: unknown identity type")

	// Document store service errors
	ErrDocumentStoreUnmarshalDocument   = errors.New("failed to unmarshal document")
	ErrDocumentStoreMarshalDocument     = errors.New("failed to marshal document")
	ErrDocumentStoreUnmarshalFields     = errors.New("failed to unmarshal fields")
	ErrDocumentStoreExtractField        = errors.New("failed to extract field")
	ErrDocumentStoreDecodeField         = errors.New("failed to decode field")
	ErrDocumentStoreInvalidFilterField  = errors.New("invalid filter field")
	ErrDocumentStoreInvalidFilterValue  = errors.New("invalid filter value")
	ErrDocumentStoreInvalidOrderByField = errors.New("invalid orderBy field")
	ErrDocumentStoreParseCreatedAt      = errors.New("failed to parse created_at timestamp")
	ErrDocumentStoreParseUpdatedAt      = errors.New("failed to parse updated_at timestamp")
	ErrDocumentStoreUnmarshalData       = errors.New("failed to unmarshal document data")

	// App policy store service errors
	ErrAppPolicyStoreGetFailed       = errors.New("failed to get app policy")
	ErrAppPolicyStoreMarshalFailed   = errors.New("failed to marshal app policy data")
	ErrAppPolicyStoreUnmarshalFailed = errors.New("failed to unmarshal app policy")

	// MCP config errors
	ErrMCPConfigGatewayURLInvalidScheme = errors.New("gateway URL scheme must be https")
	ErrMCPConfigGatewayURLHostEmpty     = errors.New("gateway URL host cannot be empty")
	ErrMCPConfigVerifyHostnameEmpty     = errors.New("verify hostname cannot be empty")
	ErrMCPConfigBinaryPathEmpty         = errors.New("binary path cannot be empty")
	ErrMCPConfigBinaryPathWhitespace    = errors.New("binary path cannot be whitespace only")
	ErrMCPConfigCertPathEmpty           = errors.New("certificate path cannot be empty")
	ErrMCPConfigCertPathWhitespace      = errors.New("certificate path cannot be whitespace only")

	// Fingerprint errors
	ErrFingerprintGetHostname   = errors.New("fingerprint: failed to get hostname")
	ErrFingerprintUnsupportedOS = errors.New("fingerprint: unsupported operating system")
	ErrFingerprintMachineIDRead = errors.New("fingerprint: could not read machine ID from any known path")

	// PKI errors
	ErrPKICreateDirectory        = errors.New("pki: failed to create directory")
	ErrPKILoadRootCA             = errors.New("pki: failed to load root CA")
	ErrPKIGenerateRootCA         = errors.New("pki: failed to generate root CA")
	ErrPKILoadIntermediateCA     = errors.New("pki: failed to load intermediate CA")
	ErrPKIGenerateIntermediateCA = errors.New("pki: failed to generate intermediate CA")
	ErrPKILoadServiceCert        = errors.New("pki: failed to load service certificate")
	ErrPKIGenerateServiceCert    = errors.New("pki: failed to generate service certificate")
	ErrPKIGenerateTrustBundles   = errors.New("pki: failed to generate trust bundles")
	ErrPKIRevokeCertificate      = errors.New("pki: failed to revoke certificate")
	ErrPKIGenerateCRL            = errors.New("pki: failed to generate CRL")
	ErrPKICheckRevocation        = errors.New("pki: failed to check revocation status")
	ErrPKICertificateRevoked     = errors.New("pki: certificate is revoked")
	ErrPKINoCertificate          = errors.New("pki: no certificate provided")
	ErrPKISignCSR                = errors.New("pki: failed to sign CSR")
	ErrPKIInvalidCSR             = errors.New("pki: invalid CSR PEM")
	ErrPKIParseCSR               = errors.New("pki: failed to parse CSR")

	// L5 Actuator errors
	ErrL5ActuatorExecutionHandlerNotSet = errors.New("L5Actuator: ExecutionHandler not set")
	ErrL5ActuatorSigningKeyMissing      = errors.New("L5Actuator: signing key missing")
	ErrL5ActuatorSignReceipt            = errors.New("failed to sign action receipt")
	ErrL5ActuatorLogReceipt             = errors.New("failed to log action receipt")
	ErrL5ActuatorMarshalReceipt         = errors.New("failed to marshal receipt for canonicalization")
	ErrL5ActuatorCanonicalizeReceipt    = errors.New("failed to canonicalize receipt for signing")
	ErrL5ActuatorAuditStore             = errors.New("audit store error")
	ErrL5ActuatorCapabilityMint         = errors.New("L5Actuator: failed to mint execution capability")
	ErrL5ActuatorCapabilityDissolve     = errors.New("L5Actuator: failed to dissolve execution capability")
	ErrL5ActuatorRehydrate              = errors.New("L5Actuator: failed to rehydrate payload")
	ErrL5ActuatorDocStore               = errors.New("L5Actuator: document store error")
	ErrPKICSRSignatureCheck             = errors.New("pki: CSR signature check failed")
	ErrPKIInvalidCurve                  = errors.New("pki: CSR public key must use P-256 curve")
	ErrPKIGenerateSerial                = errors.New("pki: failed to generate serial")

	// State root service errors
	ErrStateRootCalculate        = errors.New("state root calculation failed")
	ErrStateRootPersist          = errors.New("state root persistence failed")
	ErrStateRootFetch            = errors.New("failed to fetch state root from gateway")
	ErrStateRootScanDocuments    = errors.New("failed to scan documents row")
	ErrStateRootHashDocuments    = errors.New("failed to hash documents table")
	ErrStateRootScanKVStore      = errors.New("failed to scan kv_store row")
	ErrStateRootHashKVStore      = errors.New("failed to hash kv_store table")
	ErrStateRootScanBlobs        = errors.New("failed to scan blobs row")
	ErrStateRootHashBlobs        = errors.New("failed to hash blobs table")
	ErrStateRootQueryTable       = errors.New("failed to query table")
	ErrStateRootIterateRows      = errors.New("failed to iterate rows")
	ErrStateRootUnsupportedType  = errors.New("unsupported type for state root hashing")
	ErrPKIGenerateSPIFFEURL      = errors.New("pki: failed to generate SPIFFE URL")
	ErrPKICreateCertificate      = errors.New("pki: failed to create certificate")
	ErrPKIParseCertificate       = errors.New("pki: failed to parse certificate")
	ErrPKIReadCACertificate      = errors.New("pki: failed to read CA certificate")
	ErrPKIInvalidCertPEM         = errors.New("pki: invalid cert PEM")
	ErrPKILoadCAPrivateKey       = errors.New("pki: failed to load CA private key")
	ErrPKIPrivateKeyRequired     = errors.New("pki: secret manager required for private key operations")
	ErrPKIPrivateKeyNotFound     = errors.New("pki: CA private key not found in keystore")
	ErrPKIPrivateKeyParse        = errors.New("pki: failed to parse private key")
	ErrPKIMarshalPrivateKey      = errors.New("pki: failed to marshal private key")
	ErrPKIStorePrivateKey        = errors.New("pki: failed to store private key in keystore")
	ErrPKIWritePEMFile           = errors.New("pki: failed to write PEM file")
	ErrPKIReadRootCA             = errors.New("pki: failed to read root CA")
	ErrPKIReadHubCA              = errors.New("pki: failed to read hub CA")
	ErrPKIReadOperatorCA         = errors.New("pki: failed to read operator CA")
	ErrPKIReadGatewayPeerCA      = errors.New("pki: failed to read gateway peer CA")
	ErrPKIWriteGatewayBundle     = errors.New("pki: failed to write gateway bundle")
	ErrPKIWriteOperatorBundle    = errors.New("pki: failed to write operator bundle")
	ErrPKIWriteRootBundle        = errors.New("pki: failed to write root bundle")
	ErrPKIMarshalTrustDomain     = errors.New("pki: failed to marshal trust domain data")
	ErrPKIWriteTrustDomain       = errors.New("pki: failed to write trust-domain.json")
	ErrPKIDatabaseNotAvailable   = errors.New("pki: database not available")
	ErrPKIOperatorCANotLoaded    = errors.New("pki: operator CA not loaded - call InitializePKI first")
	ErrPKIGatewayPeerCANotLoaded = errors.New("pki: gateway peer CA not loaded - call InitializePKI first")
	ErrPKIHubCANotLoaded         = errors.New("pki: hub CA not loaded - call InitializePKI first")
	ErrPKIUnknownCACommonName    = errors.New("pki: unknown CA common name")
	ErrPKILoadServiceKey         = errors.New("pki: failed to load service private key")
	ErrPKIStoreServiceKey        = errors.New("pki: failed to store service private key")
	ErrPKIRenewServiceCert       = errors.New("pki: failed to renew service certificate")
	ErrPKIEd25519CertRejected    = errors.New("pki: certificate with Ed25519 signature is not permitted in TLS trust chain (FIPS 140-3 exclusion)")

	// Registration service errors
	ErrRegistrationUserIDRequired                  = errors.New("user_id is required")
	ErrRegistrationOperatorIDRequired              = errors.New("operator_id is required")
	ErrRegistrationOperatorNotFound                = errors.New("operator not found")
	ErrRegistrationOperatorNotBelongToUser         = errors.New("operator does not belong to user")
	ErrRegistrationSystemFingerprintRequired       = errors.New("system_fingerprint is required")
	ErrRegistrationOperatorCSRRequired             = errors.New("operator CSR is required")
	ErrRegistrationInvalidSystemFingerprint        = errors.New("invalid system_fingerprint")
	ErrRegistrationFailedToCreateSlot              = errors.New("failed to create Operator slot")
	ErrRegistrationFailedToResolveSlot             = errors.New("failed to resolve Operator slot")
	ErrRegistrationInvalidCSRPEMFormat             = errors.New("invalid CSR PEM format")
	ErrRegistrationCSRParsingFailed                = errors.New("CSR parsing failed")
	ErrRegistrationCSRSignFailed                   = errors.New("failed to sign CSR")
	ErrRegistrationCSRRequired                     = errors.New("CSR required for device registration")
	ErrRegistrationWebSessionIDRequired            = errors.New("web_session_id is required")
	ErrRegistrationOperatorIDsRequired             = errors.New("operator_ids required")
	ErrRegistrationOperatorNoActiveSession         = errors.New("operator has no active session")
	ErrRegistrationFailedToMarshalSessionIDs       = errors.New("failed to marshal session IDs")
	ErrRegistrationFailedToSetKVBinding            = errors.New("failed to set KV binding")
	ErrRegistrationFailedToGetBoundSessions        = errors.New("failed to get bound sessions document")
	ErrRegistrationFailedToMarshalBoundSessions    = errors.New("failed to marshal bound sessions document")
	ErrRegistrationFailedToSetBoundSessions        = errors.New("failed to set bound sessions document")
	ErrRegistrationFailedToMarshalExistingDocument = errors.New("failed to marshal existing document")
	ErrRegistrationFailedToUnmarshalBoundSessions  = errors.New("failed to unmarshal bound sessions document")
	ErrRegistrationFailedToUpdateBoundSessions     = errors.New("failed to update bound sessions document")
	ErrRegistrationFailedToBindOperator            = errors.New("failed to bind Operator for target context")

	// Script template errors
	ErrScriptTemplateNotInitialized = errors.New("script template not initialized - call Init() first")
	ErrScriptTemplateParseFailed    = errors.New("failed to parse script template")
	ErrScriptTemplateRenderFailed   = errors.New("failed to render script template")

	// Governance/Transaction errors
	ErrTxInvalidEnvelope         = errors.New("TX_INVALID_ENVELOPE: failed to decode GovernanceEnvelope JSON")
	ErrTxUnknownActionType       = errors.New("TX_UNKNOWN_ACTION: action type not recognized")
	ErrTxPayloadDecodeFailed     = errors.New("TX_PAYLOAD_DECODE: failed to decode typed payload")
	ErrTxTransactionHashMismatch = errors.New("TX_HASH_MISMATCH: transaction_hash does not match computed hash")
	ErrTxTransactionIDMismatch   = errors.New("TX_ID_MISMATCH: id does not match computed hash")
	ErrTxTransactionExpired      = errors.New("TX_EXPIRED: transaction has expired")
	ErrTxTransactionReplay       = errors.New("TX_REPLAY: nonce already used")
	ErrTxStateRootMissing        = errors.New("TX_STATE_MISSING: state_merkle_root required but missing")
	ErrTxStateRootMismatch       = errors.New("TX_STATE_MISMATCH: state_merkle_root does not match current state")
	ErrTxL2SignatureMissing      = errors.New("TX_QUORUM_L2_SIG_MISSING: Consensus L2 votes required but missing")

	// Governance L1 doctrine errors
	ErrGovernanceJSONDepthExceeded = errors.New("JSON recursion depth exceeded maximum limit")

	ErrTxL2SignatureInvalid           = errors.New("TX_QUORUM_L2_SIG_INVALID: Consensus L2 consensus_signature failed verification")
	ErrTxL2QuorumNotMet               = errors.New("TX_QUORUM_L2_NOT_MET: affirmative distinct signer count below consensus quorum")
	ErrTxL2SignerStoreNotConfigured   = errors.New("TX_QUORUM_L2_SIGNER_STORE_MISSING: signer store required but not configured")
	ErrTxL2ConsensusNotConfigured     = errors.New("TX_QUORUM_L2_CONSENSUS_MISSING: consensus policy not found or disabled")
	ErrTxL2DuplicateSigner            = errors.New("TX_QUORUM_L2_DUP_SIGNER: duplicate signer key in vote set with require_distinct")
	ErrConsensusHashMismatch          = errors.New("CONSENSUS_HASH_MISMATCH: envelope id does not match recomputed transaction hash")
	ErrConsensusInvalidID             = errors.New("CONSENSUS_INVALID_ID: consensus ID must contain only alphanumeric characters, hyphens, and underscores")
	ErrConsensusMustBeEnabled         = errors.New("CONSENSUS_MUST_BE_ENABLED: new consensus must be created with enabled=true")
	ErrConsensusFactoryNilPolicy      = errors.New("CONSENSUS_FACTORY_NIL_POLICY: consensus policy is nil")
	ErrConsensusFactoryNilKeyProvider = errors.New("CONSENSUS_FACTORY_NIL_KEY_PROVIDER: key provider is nil")
	ErrConsensusNotConfigured         = errors.New("CONSENSUS_NOT_CONFIGURED: consensus service not yet initialized")
	ErrConsensusNoSigningMembers      = errors.New("CONSENSUS_NO_SIGNING_MEMBERS: no members with private keys available to sign votes")
	ErrTxL3ProofMissing               = errors.New("TX_NOTARY_L3_PROOF_MISSING: Notary (L3Notary) WebAuthn proof required but missing")
	ErrTxL3ProofInvalid               = errors.New("TX_NOTARY_L3_PROOF_INVALID: Notary (L3Notary) WebAuthn proof failed verification")
	ErrTxL3NotaryNotConfigured        = errors.New("TX_NOTARY_L3_NOTARY_MISSING: Notary (L3Notary) required but not configured")
	ErrTxTransactionHashMissing       = errors.New("TX_HASH_MISSING: transaction_hash required")
	ErrTxTransactionIDMissing         = errors.New("TX_ID_MISSING: id required")
	ErrTxExpiresAtMissing             = errors.New("TX_EXPIRES_AT_MISSING: expires_at required")
	ErrTxNonceMissing                 = errors.New("TX_NONCE_MISSING: nonce required")
	ErrTxReplayStoreMissing           = errors.New("TX_REPLAY_STORE_MISSING: replay store required")
	ErrTxStateRootRequired            = errors.New("TX_STATE_REQUIRED: state_merkle_root required")
	ErrTxPayloadMissing               = errors.New("TX_PAYLOAD_MISSING: typed protobuf payload required")
	ErrTxPayloadActionMismatch        = errors.New("TX_PAYLOAD_ACTION_MISMATCH: action type does not match typed payload")
	ErrTxL1ValidationFailed           = errors.New("TX_DOCTRINE_L1_FAILED: typed payload violates Doctrine (L1Doctrine) forbidden patterns")
	ErrTxDoctrineMissing              = errors.New("TX_DOCTRINE_MISSING: L1Doctrine required but not configured")
	ErrTxInFlight                     = errors.New("TX_IN_FLIGHT: transaction with same nonce already in-flight")
	ErrTxProviderMisconfigured        = errors.New("PROVIDER_MISCONFIGURED: state root is empty")
	ErrTxCanonicalizeFailed           = errors.New("TX_CANONICALIZE_FAILED: unsupported type in intent_data canonicalization")

	// MCP container status errors
	ErrMCPContainerNameRequired = errors.New("container_name required")

	// MCP service status errors
	ErrMCPServiceNameRequired = errors.New("service_name required")

	// Kubernetes MCP tool errors
	ErrMCPK8sCommandFailed        = errors.New("kubectl command failed")
	ErrMCPK8sUnmarshalArguments   = errors.New("failed to unmarshal k8s tool arguments")
	ErrMCPK8sKubectlNotFound      = errors.New("kubectl not found in PATH")
	ErrMCPK8sNameRequired         = errors.New("name is required")
	ErrMCPK8sUnsupportedOperation = errors.New("unsupported k8s operation")
	ErrMCPK8sMarshalResult        = errors.New("failed to marshal k8s result")
	ErrMCPK8sGetPods              = errors.New("failed to get pods")
	ErrMCPK8sParsePods            = errors.New("failed to parse pods")
	ErrMCPK8sGetNodes             = errors.New("failed to get nodes")
	ErrMCPK8sParseNodes           = errors.New("failed to parse nodes")
	ErrMCPK8sGetServices          = errors.New("failed to get services")
	ErrMCPK8sParseServices        = errors.New("failed to parse services")
	ErrMCPK8sGetDeployments       = errors.New("failed to get deployments")
	ErrMCPK8sParseDeployments     = errors.New("failed to parse deployments")
	ErrMCPK8sGetNamespaces        = errors.New("failed to get namespaces")
	ErrMCPK8sParseNamespaces      = errors.New("failed to parse namespaces")
	ErrMCPK8sGetVersion           = errors.New("failed to get cluster version")
	ErrMCPK8sParseVersion         = errors.New("failed to parse cluster version")
	ErrMCPK8sGetPodLogs           = errors.New("failed to get pod logs")
	ErrMCPK8sDescribePod          = errors.New("failed to describe pod")

	// Reporting errors
	ErrReportStoreUnavailable   = errors.New("reporting: store unavailable")
	ErrReportWriteFailed        = errors.New("reporting: write failed")
	ErrReportVerificationFailed = errors.New("reporting: verification failed")
	ErrReportOutputDirFailed    = errors.New("reporting: output directory failed")

	// PubSub client errors
	ErrPubSubURLRequired      = errors.New("pubsub URL is required")
	ErrPubSubTLSConfig        = errors.New("failed to configure TLS")
	ErrPubSubConnect          = errors.New("failed to connect to pubsub")
	ErrPubSubSubscribe        = errors.New("failed to subscribe to channel")
	ErrPubSubSubscriptionACK  = errors.New("failed to ACK subscription")
	ErrPubSubConnectionError  = errors.New("pubsub connection error")
	ErrPubSubPublishConnect   = errors.New("failed to connect for publish")
	ErrPubSubClosed           = errors.New("pubsub connection closed")
	ErrPubSubMarshalPayload   = errors.New("failed to marshal pubsub payload")
	ErrPubSubPublishReconnect = errors.New("failed to reconnect for publish")
	ErrPubSubPublish          = errors.New("failed to publish message")

	// Context errors
	ErrContextCancelled = errors.New("context cancelled")

	// SSH errors
	ErrSSHContextCancelled      = errors.New("ssh: context cancelled")
	ErrSSHRetryBackoffCancelled = errors.New("ssh: context cancelled during retry backoff")
	ErrSSHBeforeRunCancelled    = errors.New("ssh: context cancelled before run")

	// Blob store errors
	ErrBlobStoreCleanupFailed = errors.New("failed to cleanup expired blobs")
	ErrBlobStorePutFailed     = errors.New("failed to store blob")
	ErrBlobStoreGetFailed     = errors.New("failed to retrieve blob")
	ErrBlobStoreDeleteFailed  = errors.New("failed to delete blob")
	ErrBlobStoreScanFailed    = errors.New("failed to scan blob metadata")
	ErrBlobStoreParseTime     = errors.New("failed to parse blob creation time")

	// Auth service errors
	ErrIdentityDisabled           = errors.New("identity disabled")
	ErrOperatorIdentityDisabled   = errors.New("operator identity disabled")
	ErrOperatorSessionExpired     = errors.New("operator session expired")
	ErrMTLSCertRequired           = errors.New("mTLS client certificate required")
	ErrMTLSCertRevoked            = errors.New("mTLS client certificate revoked or invalid")
	ErrProtocolAuthRequired       = errors.New("protocol authentication required")
	ErrMTLSIdentityMismatch       = errors.New("mTLS identity mismatch")
	ErrSessionLoadFailed          = errors.New("failed to load session")
	ErrSessionParseFailed         = errors.New("failed to parse session")
	ErrCLISessionExpired          = errors.New("CLI session expired")
	ErrIdentityValidationFailed   = errors.New("identity validation failed")
	ErrAppPolicyNotFound          = errors.New("app policy not found")
	ErrInvalidAppPolicy           = errors.New("invalid app policy")
	ErrPrivilegedEndpointAccess   = errors.New("external apps cannot access privileged endpoints")
	ErrWebSessionCookieRequired   = errors.New("web session cookie required")
	ErrWebSessionCookieInvalid    = errors.New("invalid web session cookie")
	ErrWebSessionValidationFailed = errors.New("web session validation failed")
	ErrWebSessionNotFound         = errors.New("web session not found")
	ErrWebSessionExpired          = errors.New("web session expired")
	ErrWebSessionAuthRequired     = errors.New("web session authentication required")
	ErrJWTAuthNotConfigured       = errors.New("JWT authentication not configured")
	ErrJWTTokenMissing            = errors.New("missing JWT token")
	ErrJWTSignatureMissing        = errors.New("missing JWT bearer token")
	ErrJWTSessionSubjectMissing   = errors.New("JWT missing subject claim")
	ErrJWTInvalidToken            = errors.New("invalid JWT token")
	ErrUserCreationFailed         = errors.New("user creation failed")
	ErrCLISessionInvalid          = errors.New("invalid CLI session")
	ErrCLICertBindingCheckFailed  = errors.New("CLI cert binding check failed")

	// Stream errors
	ErrStreamMarshalEvent = errors.New("failed to marshal stream event")

	// Consensus bootstrap errors
	ErrConsensusBootstrapMissingFields = errors.New("consensus bootstrap: consensus_id, member_app_ids, and quorum are required")
	ErrInvalidSeedLength               = errors.New("invalid seed length")
	ErrConsensusMemberKeyNotFound      = errors.New("no private key for member")
	ErrConsensusBootstrapParseConfig   = errors.New("consensus bootstrap: parse config")
	ErrConsensusBootstrapReadConfig    = errors.New("consensus bootstrap: read config")
	ErrConsensusBootstrapDecodeSeed    = errors.New("consensus bootstrap: decode seed hex")
	ErrGatewayServiceNil               = errors.New("gateway service is nil")

	// SSE approval errors
	ErrApprovalSSETimeout = errors.New("L3 approval: timed out waiting for SSE event")

	// Agent harness errors
	ErrHarnessNoScenarios       = errors.New("no scenarios selected")
	ErrHarnessGovKitNotInit     = errors.New("gov kit not initialized (call SetGovKit)")
	ErrHarnessGovKitMissingSign = errors.New("gov kit not initialized (need ensemble + principal)")

	// Browser errors
	ErrBrowserURLEmpty = errors.New("browser URL cannot be empty")

	// Field path parser errors
	ErrFieldPathInvalidCollection = errors.New("FIELD_PATH_INVALID_COLLECTION: collection not in schema registry")
	ErrFieldPathInvalid           = errors.New("FIELD_PATH_INVALID: field path not in allowlist")
	ErrFieldPathForbidden         = errors.New("FIELD_PATH_FORBIDDEN: field path in denylist")
	ErrFieldPathSyntax            = errors.New("FIELD_PATH_SYNTAX: invalid dot-notation syntax")
	ErrFieldPathEmpty             = errors.New("FIELD_PATH_EMPTY: field path cannot be empty")
	ErrFieldPathEmptyCollection   = errors.New("FIELD_PATH_EMPTY_COLLECTION: collection cannot be empty")
	ErrFieldPathDocumentNil       = errors.New("document is nil")
	ErrFieldPathComponentNotFound = errors.New("field path component not found")
	ErrFieldPathNotObject         = errors.New("cannot access field on non-object type")

	// Lattice adapter errors
	ErrLatticeConfigMissing            = errors.New("lattice config is required")
	ErrLatticeEndpointRequired         = errors.New("lattice endpoint required")
	ErrLatticeClientIDRequired         = errors.New("lattice client_id required")
	ErrLatticeClientSecretRequired     = errors.New("lattice client_secret required")
	ErrLatticeTokenAcquireFailed       = errors.New("lattice: failed to acquire token")
	ErrLatticeTokenRefreshFailed       = errors.New("lattice: failed to refresh token")
	ErrLatticeTokenExpired             = errors.New("lattice: token expired and refresh failed")
	ErrLatticeEntityIDRequired         = errors.New("lattice: entity_id required")
	ErrLatticeEntityIDPersistFailed    = errors.New("lattice: failed to persist entity_id")
	ErrLatticeEntityIDReadFailed       = errors.New("lattice: failed to read entity_id")
	ErrLatticeDialFailed               = errors.New("lattice: gRPC dial failed")
	ErrLatticePresencePublishFailed    = errors.New("lattice: failed to publish entity presence")
	ErrLatticeStreamClosed             = errors.New("lattice: task stream closed")
	ErrLatticeStreamReconnectFailed    = errors.New("lattice: task stream reconnect failed")
	ErrLatticeStatusReportFailed       = errors.New("lattice: failed to report task status")
	ErrLatticeHeartbeatIntervalInvalid = errors.New("lattice: heartbeat interval must be > 0 and < 4 minutes")
	ErrLatticePostureFloorViolated     = errors.New("lattice: active posture below configured floor")
	ErrLatticeNotInitialized           = errors.New("lattice: adapter not initialized")
	ErrLatticeAlreadyRunning           = errors.New("lattice: adapter already running")

	// Gateway database initialization errors
	ErrGatewayDBAuditStoreInit = errors.New("gateway database audit store initialization failed")
	ErrGatewayDBSchemaInit     = errors.New("gateway database schema initialization failed")
	ErrGatewayDBStateRootInit  = errors.New("gateway database state root initialization failed")

	// Console SPA errors
	ErrConsoleStaticFS = errors.New("console: failed to sub static FS")

	// Compliance KSI errors
	ErrKSICatalogInvalid     = errors.New("KSI catalog invalid")
	ErrOverlayCatalogInvalid = errors.New("overlay catalog invalid")
	ErrOverlayReadFailed     = errors.New("overlay read failed")
	ErrOverlayParseFailed    = errors.New("overlay parse failed")

	// Compliance KSI history errors
	ErrKSIHistoryWriteFailed = errors.New("KSI history: write failed")
	ErrKSIHistoryReadFailed  = errors.New("KSI history: read failed")
	ErrKSIHistoryParseFailed = errors.New("KSI history: parse failed")
	ErrKSIHistoryEmpty       = errors.New("KSI history: no snapshots found")
)
