# Copyright (c) 2026 Lateralus Labs, LLC.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging
from uuid import uuid4

from app.models.settings import G8eePlatformSettings
from app.constants import (
    DB_COLLECTION_CASES,
    DB_COLLECTION_TASKS,
    CaseStatus,
    ComponentName,
    EntityType,
    ErrorCode,
    EventType,
    TaskStatus,
)
from app.errors import (
    BusinessLogicError,
    DatabaseError,
    ResourceNotFoundError,
    ValidationError,
    G8eError,
)
from app.models import (
    CaseCreateRequest,
    CaseEventPayload,
    CaseUpdateRequest,
)
from app.models.cache import FieldFilter
from app.models.cases import CaseModel, HistoryEntry
from app.models.events import SessionEvent
from app.models.db_queries import CaseHistoryQuery
from app.services.cache.cache_aside import CacheAsideService
from app.services.infra.g8ed_event_service import EventService
from app.utils.timestamp import now

logger = logging.getLogger(__name__)

class CaseDataService:
    """Domain service for Case and Task data management using CacheAsideService."""

    def __init__(
        self, 
        settings: G8eePlatformSettings, 
        cache: CacheAsideService,
        event_service: EventService
    ):
        self.settings = settings
        self.cache = cache
        self.event_service = event_service
        self.cases_collection = settings.database.cases_collection or DB_COLLECTION_CASES
        self.tasks_collection = settings.database.tasks_collection or DB_COLLECTION_TASKS

    async def create_case(self, case_data: CaseCreateRequest, generated_title: str) -> CaseModel:
        """
        Create a new case.

        SECURITY: Case ID is ALWAYS generated server-side. Never accept from client.
        Title is AI-generated by internal_router before calling this method.
        Description is derived from initial_message.

        Args:
            case_data: Case creation data (with server-injected session fields)
            generated_title: AI-generated title from initial_message (optional)

        Returns:
            Created CaseModel
        """
        case_id = str(uuid4())

        title = generated_title
        if not title and case_data.initial_message:
            title = case_data.initial_message[:100].strip()
            if len(case_data.initial_message) > 100:
                title += "..."
        if not title:
            title = "Untitled Case"

        description = case_data.initial_message or "No description provided"

        logger.info(f"Creating case: {case_id}", extra={
            "case_id": case_id,
            "user_id": case_data.user_id,
            "source": case_data.source,
            "title_source": "ai" if generated_title else "derived"
        })

        ts = now()
        case = CaseModel(
            id=case_id,
            title=title,
            description=description,
            user_id=case_data.user_id,
            user_email=case_data.user_email,
            web_session_id=case_data.web_session_id,
            status=CaseStatus.NEW,
            priority=case_data.priority,
            severity=case_data.severity,
            source=case_data.source,
            tags=[],
            metadata={},
            created_at=ts,
            updated_at=ts,
        )

        try:
            await self.cache.create_document(
                collection=self.cases_collection,
                document_id=case_id,
                data=case.model_dump(mode="json"),
            )

            logger.info(f"Case created: {case_id}", extra={"case_id": case_id})
            return case

        except G8eError:
            raise
        except Exception as e:
            logger.error(f"Failed to create case {case_id}: {e}", exc_info=True)
            raise DatabaseError(
                message=f"Failed to create case: {e}",
                code=ErrorCode.DB_WRITE_ERROR,
                details={"case_id": case_id},
                cause=e,
                component=ComponentName.G8EE
            )

    async def get_case(self, case_id: str) -> CaseModel:
        """
        Get a case by ID.

        Args:
            case_id: Case ID

        Returns:
            CaseModel
        """
        if not case_id:
            raise ValidationError("Case ID is required")

        logger.info(f"Retrieving case: {case_id}", extra={"case_id": case_id})

        try:
            doc_data = await self.cache.get_document(
                collection=self.cases_collection,
                document_id=case_id,
            )
            if not doc_data:
                raise ResourceNotFoundError(
                    message="Case not found",
                    resource_type=EntityType.CASE,
                    resource_id=case_id,
                    component=ComponentName.G8EE
                )

            doc_data["id"] = case_id
            return CaseModel.model_validate(doc_data)

        except G8eError:
            raise
        except Exception as e:
            logger.error(f"Failed to retrieve case {case_id}: {e}", exc_info=True)
            raise DatabaseError(
                message=f"Failed to retrieve case: {e}",
                code=ErrorCode.DB_QUERY_ERROR,
                details={"case_id": case_id},
                cause=e,
                component=ComponentName.G8EE
            )

    async def update_case(self, case_id: str, updates: CaseUpdateRequest) -> CaseModel:
        """
        Update a case.

        Args:
            case_id: Case ID
            updates: Validated update request

        Returns:
            Updated CaseModel
        """
        update_fields = updates.model_dump(mode="json")

        if not update_fields:
            raise BusinessLogicError(
                message="No updates provided",
                code=ErrorCode.MISSING_REQUIRED_FIELD,
                details={"case_id": case_id},
                component=ComponentName.G8EE
            )

        logger.info(f"Updating case: {case_id}", extra={
            "case_id": case_id,
            "fields": list(update_fields.keys())
        })

        existing = await self.get_case(case_id)
        updated_at = now()

        updated = existing.model_copy(update={**update_fields, "updated_at": updated_at})

        try:
            db_payload = updated.model_dump(mode="json")
            await self.cache.update_document(
                collection=self.cases_collection,
                document_id=case_id,
                data=db_payload,
                merge=True,
            )

            logger.info(f"Case updated: {case_id}", extra={"case_id": case_id})
            return updated

        except G8eError:
            raise
        except Exception as e:
            logger.error(f"Failed to update case {case_id}: {e}", exc_info=True)
            raise DatabaseError(
                message=f"Failed to update case: {e}",
                code=ErrorCode.DB_WRITE_ERROR,
                details={"case_id": case_id},
                cause=e,
                component=ComponentName.G8EE
            )

    async def delete_case(self, case_id: str) -> None:
        """
        Delete a case.

        Args:
            case_id: Case ID
        """
        logger.info(f"Deleting case: {case_id}", extra={"case_id": case_id})

        await self.get_case(case_id)

        try:
            await self.cache.delete_document(
                collection=self.cases_collection,
                document_id=case_id,
            )

            logger.info(f"Case deleted: {case_id}", extra={"case_id": case_id})

        except G8eError:
            raise
        except Exception as e:
            logger.error(f"Failed to delete case {case_id}: {e}", exc_info=True)
            raise DatabaseError(
                message=f"Failed to delete case: {e}",
                code=ErrorCode.DB_WRITE_ERROR,
                details={"case_id": case_id},
                cause=e,
                component=ComponentName.G8EE
            )

    async def publish_case_update_sse(
        self,
        case_id: str,
        web_session_id: str,
        payload: CaseEventPayload,
        user_id: str,
        event_type: EventType = EventType.CASE_UPDATED
    ) -> None:
        """
        Publish SSE event when case data changes.

        Args:
            case_id: Case ID
            web_session_id: WebSession ID for routing
            payload: Typed case event payload
            event_type: Event type
        """
        if not self.event_service:
            logger.warning("Event service not configured in CaseDataService, skipping SSE publish")
            return

        try:
            await self.event_service.publish(
                SessionEvent(
                    event_type=event_type,
                    payload=payload,
                    web_session_id=web_session_id,
                    user_id=user_id,
                    case_id=case_id,
                )
            )

            logger.info("Published case SSE update", extra={
                "case_id": case_id,
                "web_session_id": web_session_id[:8] + "...",
            })

        except Exception as e:
            logger.warning(f"Failed to publish case SSE: {e}", extra={
                "case_id": case_id,
                "web_session_id": web_session_id[:8] + "..."
            })

    async def get_case_history(self, query: CaseHistoryQuery) -> list[HistoryEntry]:
        filters = [
            FieldFilter(field="case_id", op="==", value=query.case_id)
        ]

        if query.start_time:
            filters.append(FieldFilter(field="created_at", op=">=", value=query.start_time))

        if query.end_time:
            filters.append(FieldFilter(field="created_at", op="<=", value=query.end_time))

        if query.event_type:
            filters.append(FieldFilter(field="event_type", op="==", value=query.event_type))

        results = await self.cache.query_documents(
            collection=self.cases_collection,
            field_filters=[f.model_dump(mode="json") for f in filters],
            order_by={"created_at": "asc"},
            limit=query.limit
        )

        return [HistoryEntry.model_validate(entry) for entry in results]

    async def get_case_tasks(self, case_id: str, task_status: TaskStatus) -> list[dict[str, object]]:
        if not case_id:
            raise ValidationError("Case ID is required")

        filters = [
            FieldFilter(field="case_id", op="==", value=case_id)
        ]

        if task_status:
            filters.append(FieldFilter(field="status", op="==", value=task_status))

        return await self.cache.query_documents(
            collection=self.tasks_collection,
            field_filters=[f.model_dump(mode="json") for f in filters],
            order_by={"created_at": "desc"}
        )
