# Copyright (c) 2026 Lateralus Labs, LLC.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from datetime import datetime
from typing import Any

from pydantic import Field

from app.constants import CaseStatus, ComponentName, EventType, Priority, Severity

from .attachments import AttachmentMetadata
from .base import VSOBaseModel, VSOIdentifiableModel


class HistoryEntry(VSOBaseModel):
    """Entry in the case history trail"""
    timestamp: datetime = Field(..., description="When the event occurred")
    event_type: EventType = Field(..., description="Type of event")
    source_component: ComponentName = Field(..., description="Component that initiated the event")
    summary: str = Field(..., description="Human-readable description of the event")
    actor_id: str | None = Field(default=None, description="ID of the entity that performed the action")
    related_ids: dict[str, str] | None = Field(default=None, description="Related entity IDs")
    details: dict[str, Any] | None = Field(default=None, description="Full event details")

class CaseModel(VSOIdentifiableModel):
    """Canonical case model used by ALL components"""
    title: str = Field(..., min_length=1, max_length=500)
    description: str = Field(..., min_length=1)
    user_id: str | None = Field(default=None, description="User identifier who created the case")
    user_email: str | None = Field(default=None, description="Email of the user who created the case")
    status: CaseStatus = Field(default=CaseStatus.NEW)
    priority: Priority = Field(default=Priority.MEDIUM)
    severity: Severity = Field(default=Severity.MEDIUM)
    web_session_id: str | None = Field(default=None, description="Session ID associated with the case (from session cookie)")
    assignee: str | None = Field(default=None, description="User/component assigned")
    related_case_ids: list[str] = Field(default_factory=list)
    investigation_id: str | None = Field(default=None, description="Associated investigation ID")
    tags: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)
    source: str | None = Field(default=None, description="Source system/channel")
    last_processed_by: str | None = Field(default=None, description="Last component to process")
    history_trail: list[HistoryEntry] = Field(default_factory=list, description="Chronological list of key events")
    attachments: list[str] = Field(default_factory=list, description="List of Google Cloud Storage URLs for attached files")

class CaseCreateRequest(VSOBaseModel):
    """
    Request model for creating a case.
    
    SECURITY MODEL (Adversarial Client Design):
    - Client input is treated as potentially adversarial
    - Only essential user-controlled fields are accepted from client
    - All identity/security fields are injected server-side by VSOD from authenticated session
    - All generated fields (id, title) are created server-side by VSE
    
    CLIENT-PROVIDED (user input):
    - initial_message: Required - the user's message
    - attachments: Optional - user-uploaded files  
    - sentinel_mode: Optional - user preference for data scrubbing
    
    SERVER-INJECTED BY VSOD (from authenticated session - never trust client):
    - user_id: From session.user_id
    - user_email: From session.user_data.email
    - web_session_id: From validated session cookie
    - organization_id: From session.organization_id
    
    SERVER-GENERATED BY VSE (never accept from client):
    - id: Always generated server-side (uuid4)
    - title: AI-generated from initial_message
    - description: Derived from initial_message
    - priority, severity, source: Server defaults
    """

    initial_message: str = Field(..., min_length=1, description="Initial chat message - REQUIRED")
    attachments: list[AttachmentMetadata] | None = Field(
        default_factory=list,
        description="List of attachment metadata objects for upload"
    )
    sentinel_mode: bool = Field(
        default=True,
        description="Sentinel mode - when True, data is scrubbed before storage and AI sees redacted data."
    )
    user_id: str = Field(..., min_length=1, description="User ID - MUST be injected by VSOD from authenticated session")
    user_email: str | None = Field(default=None, description="User email - injected by VSOD from session")
    web_session_id: str = Field(..., min_length=1, description="Session ID - MUST be injected by VSOD from validated session cookie")
    organization_id: str | None = Field(default=None, description="Organization ID - injected by VSOD from session")
    priority: Priority = Field(default=Priority.MEDIUM, description="Server default - not client controllable")
    severity: Severity = Field(default=Severity.MEDIUM, description="Server default - not client controllable")
    source: str = Field(default="g8e.ai", description="Server default - not client controllable")


class CaseUpdateRequest(VSOBaseModel):
    """Request model for updating a case"""
    title: str | None = Field(default=None, min_length=1, max_length=500)
    description: str | None = Field(default=None, min_length=1)
    status: CaseStatus | None = None
    priority: Priority | None = None
    severity: Severity | None = None
    assignee: str | None = None
    tags: list[str] | None = None
    metadata: dict[str, Any] | None = None


class CaseCreatedPayload(VSOBaseModel):
    """Typed payload for the CASE_CREATED SSE event."""
    title: str | None = Field(default=None, description="Case title")


class CaseEventPayload(VSOBaseModel):
    """Typed payload for case SSE events pushed to VSOD."""
    updated_at: datetime = Field(..., description="When the case was last updated")
    title: str | None = Field(default=None, description="Updated title")
    description: str | None = Field(default=None, description="Updated description")
    status: CaseStatus | None = Field(default=None, description="Updated status")
    priority: Priority | None = Field(default=None, description="Updated priority")
    severity: Severity | None = Field(default=None, description="Updated severity")
    assignee: str | None = Field(default=None, description="Updated assignee")
